.github/workflows/request.yml
add id to accepted inputs of requst github action
=> chore: add id

scripts/github-script.js
format script and move return into try block
=> fix: return

terraform/keycloak-dev/realms/onestopauth/client-test-project.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for test-project

scripts/github-script.js
=> fix: params

terraform/keycloak-dev/realms/onestopauth/client-jon-test-1.tf
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
</details>
=> request: add client files for jon-test-1

.github/workflows/terraform.yml
grab pr number from API since not available for the push event
=> fix: prnumber

.github/workflows/request.yml, scripts/generate-clients.js, scripts/github-script.js
change idps to realm in github actions
=> chore: idps

.github/workflows/terraform.yml
remove description field from step, not allowed
=> fix: description

terraform/keycloak-dev/realms/onestopauth/client-testclient-10.tf, terraform/keycloak-prod/realms/onestopauth/client-testclient-10.tf, terraform/keycloak-test/realms/onestopauth/client-testclient-10.tf
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
</details>
=> request: add client files for testclient-10

terraform/keycloak-dev/realms/onestopauth/client-test-1.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1.tf, terraform/keycloak-test/realms/onestopauth/client-test-1.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://prod.com</li></ul>```
</details>
=> request: add client files for test-1

scripts/github-script.js
add the action number to the initial api hit
=> chore: status

terraform/keycloak-dev/realms/onestopauth/client-new-test.tf, terraform/keycloak-prod/realms/onestopauth/client-new-test.tf, terraform/keycloak-test/realms/onestopauth/client-new-test.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://prod.com</li></ul>```
</details>
=> request: add client files for new-test

terraform/keycloak-dev/realms/onestopauth/client-junmin-client.tf, terraform/keycloak-prod/realms/onestopauth/client-junmin-client.tf, terraform/keycloak-test/realms/onestopauth/client-junmin-client.tf
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example.com</li></ul>```
</details>
=> request: add client files for junmin-client

terraform/keycloak-dev/realms/onestopauth/client-junmin-client-test-101.tf, terraform/keycloak-prod/realms/onestopauth/client-junmin-client-test-101.tf, terraform/keycloak-test/realms/onestopauth/client-junmin-client-test-101.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-client-test-101

terraform/keycloak-dev/realms/onestopauth/client-junmin-client-test-111.tf, terraform/keycloak-prod/realms/onestopauth/client-junmin-client-test-111.tf, terraform/keycloak-test/realms/onestopauth/client-junmin-client-test-111.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3003</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3003</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3003</li></ul>```
</details>
=> request: add client files for junmin-client-test-111

terraform/keycloak-dev/realms/onestopauth/client-jon-test-3-35.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-3-35.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-3-35.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
</details>
=> request: add client files for jon-test-3-35

terraform/keycloak-dev/realms/onestopauth/client-demo-1-38.tf, terraform/keycloak-prod/realms/onestopauth/client-demo-1-38.tf, terraform/keycloak-test/realms/onestopauth/client-demo-1-38.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://prod</li></ul>```
</details>
=> request: add client files for demo-1-38

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-34.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-34.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-34.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-34

terraform/keycloak-dev/realms/onestopauth/client-jumintestclientclient-36.tf, terraform/keycloak-prod/realms/onestopauth/client-jumintestclientclient-36.tf, terraform/keycloak-test/realms/onestopauth/client-jumintestclientclient-36.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for jumintestclientclient-36

terraform/keycloak-dev/realms/onestopauth/client-test-7-28-2021-133.tf, terraform/keycloak-prod/realms/onestopauth/client-test-7-28-2021-133.tf, terraform/keycloak-test/realms/onestopauth/client-test-7-28-2021-133.tf
```<ul>✔️Valid Redirect Urls<li>http://dAA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dAA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dAA</li></ul>```
</details>
=> request: add client files for test-7-28-2021-133

.github/workflows/terraform.yml, scripts/terraform-plan.js
see information returned from terraform plan
=> chore: plan

terraform/keycloak-dev/realms/onestopauth/client-test-07-28-2021-1.tf, terraform/keycloak-prod/realms/onestopauth/client-test-07-28-2021-1.tf, terraform/keycloak-test/realms/onestopauth/client-test-07-28-2021-1.tf
```<ul>✔️Valid Redirect Urls<li>http://t</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://t</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://t</li></ul>```
</details>
=> request: add client files for test-07-28-2021-1

terraform/keycloak-dev/realms/onestopauth/client-test-07-28-2021-1.tf, terraform/keycloak-prod/realms/onestopauth/client-test-07-28-2021-1.tf, terraform/keycloak-test/realms/onestopauth/client-test-07-28-2021-1.tf
```<ul>✔️Valid Redirect Urls<li>http://tr</li>,<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://tdsds</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://t</li></ul>```
</details>
=> request: update client files for test-07-28-2021-1

terraform/keycloak-dev/realms/onestopauth/client-junminclienttest-100-67.tf, terraform/keycloak-prod/realms/onestopauth/client-junminclienttest-100-67.tf, terraform/keycloak-test/realms/onestopauth/client-junminclienttest-100-67.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junminclienttest-100-67

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunabcedfg-100.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunabcedfg-100.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunabcedfg-100.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for testprojectjunabcedfg-100

terraform/keycloak-dev/realms/onestopauth/client-mytestprojectname-133.tf, terraform/keycloak-prod/realms/onestopauth/client-mytestprojectname-133.tf, terraform/keycloak-test/realms/onestopauth/client-mytestprojectname-133.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for mytestprojectname-133

terraform/keycloak-dev/realms/onestopauth/client-mylastproject-166.tf, terraform/keycloak-prod/realms/onestopauth/client-mylastproject-166.tf, terraform/keycloak-test/realms/onestopauth/client-mylastproject-166.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for mylastproject-166

.github/workflows/terraform.yml, scripts/github-script.js
add labels to auto generated prs
=> chore: labels

.github/workflows/terraform.yml
wakeup the lambda API at the beginning of actions to prevent timeouts
=> feat: heartbeat

terraform/keycloak-dev/realms/onestopauth/client-test-232.tf, terraform/keycloak-prod/realms/onestopauth/client-test-232.tf, terraform/keycloak-test/realms/onestopauth/client-test-232.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for test-232

.github/workflows/terraform.yml
=> fix: quotes

terraform/keycloak-dev/realms/onestopauth/client-jon-test-1-235.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-1-235.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-1-235.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-1-235

terraform/keycloak-dev/realms/onestopauth/client-jon-test-2-265.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-2-265.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-2-265.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-2-265

terraform/keycloak-dev/realms/onestopauth/client-test-3-07-29-2021-266.tf, terraform/keycloak-prod/realms/onestopauth/client-test-3-07-29-2021-266.tf, terraform/keycloak-test/realms/onestopauth/client-test-3-07-29-2021-266.tf
```<ul>✔️Valid Redirect Urls<li>http://dd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dd</li></ul>```
</details>
=> request: add client files for test-3-07-29-2021-266

.github/workflows/terraform.yml
=> fix: timeout

terraform/keycloak-dev/realms/onestopauth/client-negajjangproject-1.tf, terraform/keycloak-prod/realms/onestopauth/client-negajjangproject-1.tf, terraform/keycloak-test/realms/onestopauth/client-negajjangproject-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost/</li></ul>```
</details>
=> request: add client files for negajjangproject-1

terraform/keycloak-dev/realms/onestopauth/client-test-2-7-29-2021-234.tf, terraform/keycloak-prod/realms/onestopauth/client-test-2-7-29-2021-234.tf, terraform/keycloak-test/realms/onestopauth/client-test-2-7-29-2021-234.tf
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
</details>
=> request: add client files for test-2-7-29-2021-234

terraform/keycloak-dev/realms/onestopauth/client-test-07-29-2021-233.tf, terraform/keycloak-prod/realms/onestopauth/client-test-07-29-2021-233.tf, terraform/keycloak-test/realms/onestopauth/client-test-07-29-2021-233.tf
```<ul>✔️Valid Redirect Urls<li>http://fd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fd</li></ul>```
</details>
=> request: add client files for test-07-29-2021-233

terraform/keycloak-dev/realms/onestopauth/client-test-1-07-30-2021-34.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1-07-30-2021-34.tf, terraform/keycloak-test/realms/onestopauth/client-test-1-07-30-2021-34.tf
```<ul>✔️Valid Redirect Urls<li>http://tr</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://tr</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://tr</li></ul>```
</details>
=> request: add client files for test-1-07-30-2021-34

.github/workflows/terraform.yml
add logs to see why label is not being read
=> test: logs

terraform/keycloak-dev/realms/onestopauth/client-jon-test-7-107.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-7-107.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-7-107.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-7-107

terraform/keycloak-dev/realms/onestopauth/client-jon-test-8-108.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-8-108.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-8-108.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-8-108

terraform/keycloak-dev/realms/onestopauth/client-jon-test-10-110.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-10-110.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-10-110.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-10-110

terraform/keycloak-dev/realms/onestopauth/client-automergetestproject-133.tf, terraform/keycloak-prod/realms/onestopauth/client-automergetestproject-133.tf, terraform/keycloak-test/realms/onestopauth/client-automergetestproject-133.tf
```<ul>✔️Valid Redirect Urls<li>http://locahost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://locahost/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://locahost/</li></ul>```
</details>
=> request: add client files for automergetestproject-133

terraform/keycloak-dev/realms/onestopauth/client-automergetestjun-1.tf, terraform/keycloak-prod/realms/onestopauth/client-automergetestjun-1.tf, terraform/keycloak-test/realms/onestopauth/client-automergetestjun-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for automergetestjun-1

terraform/keycloak-dev/realms/onestopauth/client-junmin-request-34.tf, terraform/keycloak-prod/realms/onestopauth/client-junmin-request-34.tf, terraform/keycloak-test/realms/onestopauth/client-junmin-request-34.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li>,<li>http://localhost:1001</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for junmin-request-34

terraform/keycloak-dev/realms/onestopauth/client-asdf-2222222222-1.tf, terraform/keycloak-prod/realms/onestopauth/client-asdf-2222222222-1.tf, terraform/keycloak-test/realms/onestopauth/client-asdf-2222222222-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for asdf-2222222222-1

terraform/keycloak-dev/realms/onestopauth/client-ztest-134.tf, terraform/keycloak-prod/realms/onestopauth/client-ztest-134.tf, terraform/keycloak-test/realms/onestopauth/client-ztest-134.tf
```<ul>✔️Valid Redirect Urls<li>https://googleredirect.om</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://googleredirect.om</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://googleredirect.om</li></ul>```
</details>
=> request: add client files for ztest-134

terraform/keycloak-dev/realms/onestopauth/client-test-133.tf, terraform/keycloak-prod/realms/onestopauth/client-test-133.tf, terraform/keycloak-test/realms/onestopauth/client-test-133.tf
```<ul>✔️Valid Redirect Urls<li>https://redirecttest.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://redirecttest.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://redirecttest.ca</li></ul>```
</details>
=> request: add client files for test-133

terraform/keycloak-dev/realms/onestopauth/client-mytestclientaaaa-135.tf, terraform/keycloak-prod/realms/onestopauth/client-mytestclientaaaa-135.tf, terraform/keycloak-test/realms/onestopauth/client-mytestclientaaaa-135.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for mytestclientaaaa-135

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-222-67.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-222-67.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-222-67.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-222-67

terraform/keycloak-dev/realms/onestopauth/client-test-08-4-2021-166.tf, terraform/keycloak-prod/realms/onestopauth/client-test-08-4-2021-166.tf, terraform/keycloak-test/realms/onestopauth/client-test-08-4-2021-166.tf
```<ul>✔️Valid Redirect Urls<li>http://fdgd.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdgd.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdgd.com</li></ul>```
</details>
=> request: add client files for test-08-4-2021-166

terraform/keycloak-dev/realms/onestopauth/client-testing-for-v-1-199.tf, terraform/keycloak-prod/realms/onestopauth/client-testing-for-v-1-199.tf, terraform/keycloak-test/realms/onestopauth/client-testing-for-v-1-199.tf
```<ul>✔️Valid Redirect Urls<li>http://test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.gov.bc.ca</li></ul>```
</details>
=> request: add client files for testing-for-v-1-199

terraform/keycloak-dev/realms/onestopauth/client-3-test-for-v-1-238.tf, terraform/keycloak-prod/realms/onestopauth/client-3-test-for-v-1-238.tf, terraform/keycloak-test/realms/onestopauth/client-3-test-for-v-1-238.tf
```<ul>✔️Valid Redirect Urls<li>http://3test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://3test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://3test.gov.bc.ca</li></ul>```
</details>
=> request: add client files for 3-test-for-v-1-238

terraform/keycloak-dev/realms/onestopauth/client-3-test-for-v-1-239.tf, terraform/keycloak-prod/realms/onestopauth/client-3-test-for-v-1-239.tf, terraform/keycloak-test/realms/onestopauth/client-3-test-for-v-1-239.tf
```<ul>✔️Valid Redirect Urls<li>http://3test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://3test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://3test.gov.bc.ca</li></ul>```
</details>
=> request: add client files for 3-test-for-v-1-239

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-100.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-100.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-100.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-100

terraform/keycloak-dev/realms/onestopauth/client-asdfaaaaaaaaaaaaaaaaaaaaaaaaa-67.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfaaaaaaaaaaaaaaaaaaaaaaaaa-67.tf, terraform/keycloak-test/realms/onestopauth/client-asdfaaaaaaaaaaaaaaaaaaaaaaaaa-67.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for asdfaaaaaaaaaaaaaaaaaaaaaaaaa-67

terraform/keycloak-dev/realms/onestopauth/client-jbnbab-ndx-1.tf, terraform/keycloak-prod/realms/onestopauth/client-jbnbab-ndx-1.tf, terraform/keycloak-test/realms/onestopauth/client-jbnbab-ndx-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost/</li></ul>```
</details>
=> request: add client files for jbnbab-ndx-1

terraform/keycloak-dev/realms/onestopauth/client-test-1-67.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1-67.tf, terraform/keycloak-test/realms/onestopauth/client-test-1-67.tf
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
</details>
=> request: add client files for test-1-67

terraform/keycloak-dev/realms/onestopauth/client-test-69.tf, terraform/keycloak-prod/realms/onestopauth/client-test-69.tf, terraform/keycloak-test/realms/onestopauth/client-test-69.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for test-69

terraform/keycloak-dev/realms/onestopauth/client-6-test-for-release-v-1-70.tf, terraform/keycloak-prod/realms/onestopauth/client-6-test-for-release-v-1-70.tf, terraform/keycloak-test/realms/onestopauth/client-6-test-for-release-v-1-70.tf
```<ul>✔️Valid Redirect Urls<li>http://5test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://5test.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://5test.gov.bc.ca</li></ul>```
</details>
=> request: add client files for 6-test-for-release-v-1-70

terraform/keycloak-dev/realms/onestopauth/client-asdfeeeeeeeeeeeeeeeee-36.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfeeeeeeeeeeeeeeeee-36.tf, terraform/keycloak-test/realms/onestopauth/client-asdfeeeeeeeeeeeeeeeee-36.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for asdfeeeeeeeeeeeeeeeee-36

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-aaaaeaav-39.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-aaaaeaav-39.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-aaaaeaav-39.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-aaaaeaav-39

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-aaaaeaav-39.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-aaaaeaav-39.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-aaaaeaav-39.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:100022</li>,<li>http://localhost:10011</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:100022</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: update client files for testprojectjunmin-2222-aaaaeaav-39

terraform/keycloak-dev/realms/onestopauth/client-test-68.tf, terraform/keycloak-prod/realms/onestopauth/client-test-68.tf, terraform/keycloak-test/realms/onestopauth/client-test-68.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-68

terraform/keycloak-dev/realms/onestopauth/client-asdfeeeeeeeee-42.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfeeeeeeeee-42.tf, terraform/keycloak-test/realms/onestopauth/client-asdfeeeeeeeee-42.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for asdfeeeeeeeee-42

terraform/keycloak-dev/realms/onestopauth/client-test-123-test-100.tf, terraform/keycloak-prod/realms/onestopauth/client-test-123-test-100.tf, terraform/keycloak-test/realms/onestopauth/client-test-123-test-100.tf
```<ul>✔️Valid Redirect Urls<li>http://kjkjkj</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdjf</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
</details>
=> request: add client files for test-123-test-100

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-38.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-38.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-38.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost/</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost/</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-38

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-133.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-133.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-133.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-133

terraform/keycloak-dev/realms/onestopauth/client-test-08-09-2021-199.tf, terraform/keycloak-prod/realms/onestopauth/client-test-08-09-2021-199.tf, terraform/keycloak-test/realms/onestopauth/client-test-08-09-2021-199.tf
```<ul>✔️Valid Redirect Urls<li>http://testA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testA</li></ul>```
</details>
=> request: add client files for test-08-09-2021-199

terraform/keycloak-dev/realms/onestopauth/client-asdfaaaaaaaaaa-232.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfaaaaaaaaaa-232.tf, terraform/keycloak-test/realms/onestopauth/client-asdfaaaaaaaaaa-232.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for asdfaaaaaaaaaa-232

terraform/keycloak-dev/realms/onestopauth/client-jon-test-2-298.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-2-298.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-2-298.tf
```<ul>✔️Valid Redirect Urls<li>https://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an</li></ul>```
</details>
=> request: add client files for jon-test-2-298

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-qqq-41.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-qqq-41.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-qqq-41.tf
```<ul>✔️Valid Redirect Urls<li>https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://stackoverflow.com/questions/3809401/what-is-a-good-regular-expression-to-match-a-url</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-qqq-41

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-2222-bbzz-40.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-2222-bbzz-40.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-2222-bbzz-40.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000111</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000111</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000111</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-bbzz-40

terraform/keycloak-dev/realms/onestopauth/client-test-2-08-09-2021-332.tf, terraform/keycloak-prod/realms/onestopauth/client-test-2-08-09-2021-332.tf, terraform/keycloak-test/realms/onestopauth/client-test-2-08-09-2021-332.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com </li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com </li></ul>```
</details>
=> request: add client files for test-2-08-09-2021-332

terraform/keycloak-dev/realms/onestopauth/client-test-3-08-09-2021-334.tf, terraform/keycloak-prod/realms/onestopauth/client-test-3-08-09-2021-334.tf, terraform/keycloak-test/realms/onestopauth/client-test-3-08-09-2021-334.tf
```<ul>✔️Valid Redirect Urls<li>http://test3A</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test3A</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test3A</li></ul>```
</details>
=> request: add client files for test-3-08-09-2021-334

terraform/keycloak-prod/realms/onestopauth/client-test-2-08-09-2021-332.tf, terraform/keycloak-test/realms/onestopauth/client-test-2-08-09-2021-332.tf
=> test: url space

terraform/keycloak-dev/realms/onestopauth/client-jon-test-5-336.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-5-336.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-5-336.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-5-336

terraform/keycloak-dev/realms/onestopauth/client-jon-test-6-337.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-6-337.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-6-337.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-6-337

terraform/keycloak-dev/realms/onestopauth/client-test-5-08-09-2021-338.tf, terraform/keycloak-prod/realms/onestopauth/client-test-5-08-09-2021-338.tf, terraform/keycloak-test/realms/onestopauth/client-test-5-08-09-2021-338.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
</details>
=> request: add client files for test-5-08-09-2021-338

terraform/keycloak-dev/realms/onestopauth/client-test-6-340.tf, terraform/keycloak-prod/realms/onestopauth/client-test-6-340.tf, terraform/keycloak-test/realms/onestopauth/client-test-6-340.tf
```<ul>✔️Valid Redirect Urls<li>http://testAA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testAA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testAA</li></ul>```
</details>
=> request: add client files for test-6-340

terraform/keycloak-dev/realms/onestopauth/client-test-9-341.tf, terraform/keycloak-prod/realms/onestopauth/client-test-9-341.tf, terraform/keycloak-test/realms/onestopauth/client-test-9-341.tf
```<ul>✔️Valid Redirect Urls<li>http://test123</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://one</li></ul>```
</details>
=> request: add client files for test-9-341

terraform/keycloak-dev/realms/onestopauth/client-test-10-342.tf, terraform/keycloak-prod/realms/onestopauth/client-test-10-342.tf, terraform/keycloak-test/realms/onestopauth/client-test-10-342.tf
```<ul>✔️Valid Redirect Urls<li>http://</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://</li></ul>```
</details>
=> request: add client files for test-10-342

terraform/keycloak-dev/realms/onestopauth/client-jon-test-10-463.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-10-463.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-10-463.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://c</li></ul>```
</details>
=> request: add client files for jon-test-10-463

terraform/keycloak-dev/realms/onestopauth/client-jon-test-11-464.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-11-464.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-11-464.tf
```<ul>✔️Valid Redirect Urls<li>http://a </li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://a </li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://a </li></ul>```
</details>
=> request: add client files for jon-test-11-464

.github/workflows/pre-commit.yml
reduce the code commit checks to pr only
=> fix: actions

terraform/keycloak-dev/realms/onestopauth/client-test-3-08-10-2021-465.tf, terraform/keycloak-prod/realms/onestopauth/client-test-3-08-10-2021-465.tf, terraform/keycloak-test/realms/onestopauth/client-test-3-08-10-2021-465.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-3-08-10-2021-465

terraform/keycloak-dev/realms/onestopauth/client-jon-test-12-466.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-12-466.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-12-466.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-12-466

terraform/keycloak-dev/realms/onestopauth/client-aug-10-4-pm-470.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-10-4-pm-470.tf, terraform/keycloak-test/realms/onestopauth/client-aug-10-4-pm-470.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-10-4-pm-470

terraform/keycloak-dev/realms/onestopauth/client-test-6-08-10-2021-471.tf, terraform/keycloak-prod/realms/onestopauth/client-test-6-08-10-2021-471.tf, terraform/keycloak-test/realms/onestopauth/client-test-6-08-10-2021-471.tf
```<ul>✔️Valid Redirect Urls<li>http://ds</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://ds</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://ds</li></ul>```
</details>
=> request: add client files for test-6-08-10-2021-471

terraform/keycloak-dev/realms/onestopauth/client-beforerelease-472.tf, terraform/keycloak-prod/realms/onestopauth/client-beforerelease-472.tf, terraform/keycloak-test/realms/onestopauth/client-beforerelease-472.tf
```<ul>✔️Valid Redirect Urls<li>http://localhsssdddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhSSdddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhSSdddd</li></ul>```
</details>
=> request: add client files for beforerelease-472

terraform/keycloak-dev/realms/onestopauth/client-aug-11-test-843-529.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-11-test-843-529.tf, terraform/keycloak-test/realms/onestopauth/client-aug-11-test-843-529.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-11-test-843-529

terraform/keycloak-dev/realms/onestopauth/client-asdfaaaaaaaaaaeeee-563.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfaaaaaaaaaaeeee-563.tf, terraform/keycloak-test/realms/onestopauth/client-asdfaaaaaaaaaaeeee-563.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for asdfaaaaaaaaaaeeee-563

terraform/keycloak-dev/realms/onestopauth/client-jon-test-12-473.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-12-473.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-12-473.tf
```<ul>✔️Valid Redirect Urls<li>http://djaskdjklsdj</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
</details>
=> request: add client files for jon-test-12-473

terraform/keycloak-dev/realms/onestopauth/client-jon-test-3-331.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-3-331.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-3-331.tf
```<ul>✔️Valid Redirect Urls<li>http://tdadds</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for jon-test-3-331

terraform/keycloak-dev/realms/onestopauth/client-april-17-test-595.tf, terraform/keycloak-prod/realms/onestopauth/client-april-17-test-595.tf, terraform/keycloak-test/realms/onestopauth/client-april-17-test-595.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for april-17-test-595

terraform/keycloak-dev/realms/onestopauth/client-aug-17-test-email-596.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-17-test-email-596.tf, terraform/keycloak-test/realms/onestopauth/client-aug-17-test-email-596.tf
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-17-test-email-596

terraform/keycloak-dev/realms/onestopauth/client-jon-email-test-597.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-email-test-597.tf, terraform/keycloak-test/realms/onestopauth/client-jon-email-test-597.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-email-test-597

terraform/keycloak-dev/realms/onestopauth/client-test-email-notification-598.tf, terraform/keycloak-prod/realms/onestopauth/client-test-email-notification-598.tf, terraform/keycloak-test/realms/onestopauth/client-test-email-notification-598.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-email-notification-598

terraform/keycloak-dev/realms/onestopauth/client-august-17th-4-pm-599.tf, terraform/keycloak-prod/realms/onestopauth/client-august-17th-4-pm-599.tf, terraform/keycloak-test/realms/onestopauth/client-august-17th-4-pm-599.tf
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
</details>
=> request: add client files for august-17th-4-pm-599

terraform/keycloak-dev/realms/onestopauth/client-august-17-4-pm-2-600.tf, terraform/keycloak-prod/realms/onestopauth/client-august-17-4-pm-2-600.tf, terraform/keycloak-test/realms/onestopauth/client-august-17-4-pm-2-600.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for august-17-4-pm-2-600

terraform/keycloak-dev/realms/onestopauth/client-jon-1-265.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-1-265.tf, terraform/keycloak-test/realms/onestopauth/client-jon-1-265.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://stackoverflow.com/questions/58579426/in-useeffect-whats-the-difference-between-providing-no-dependency-array-and-an</li></ul>```
</details>
=> request: add client files for jon-1-265

terraform/keycloak-dev/realms/onestopauth/client-a-601.tf, terraform/keycloak-prod/realms/onestopauth/client-a-601.tf, terraform/keycloak-test/realms/onestopauth/client-a-601.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for a-601

terraform/keycloak-dev/realms/onestopauth/client-jon-test-13-661.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-test-13-661.tf, terraform/keycloak-test/realms/onestopauth/client-jon-test-13-661.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for jon-test-13-661

terraform/keycloak-dev/realms/onestopauth/client-test-project-1-663.tf, terraform/keycloak-prod/realms/onestopauth/client-test-project-1-663.tf, terraform/keycloak-test/realms/onestopauth/client-test-project-1-663.tf
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-project-1-663

terraform/keycloak-dev/realms/onestopauth/client-test-project-2-664.tf, terraform/keycloak-prod/realms/onestopauth/client-test-project-2-664.tf, terraform/keycloak-test/realms/onestopauth/client-test-project-2-664.tf
```<ul>✔️Valid Redirect Urls<li>https://ensembleca.ent.cgi.com/client/56524/adsacctdocs/Project%20Documentation/Forms/AllItems.aspx?View=%7B585E2036-92F2-4701-85BC-35DCD8967E15%7D</li>,<li>http://test</li>,<li>http://test</li>,<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-project-2-664

terraform/keycloak-dev/realms/onestopauth/client-august-19-741-pm-694.tf, terraform/keycloak-prod/realms/onestopauth/client-august-19-741-pm-694.tf, terraform/keycloak-test/realms/onestopauth/client-august-19-741-pm-694.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for august-19-741-pm-694

terraform/keycloak-dev/realms/onestopauth/client-aug-18-744-pm-695.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-18-744-pm-695.tf, terraform/keycloak-test/realms/onestopauth/client-aug-18-744-pm-695.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-18-744-pm-695

terraform/keycloak-dev/realms/onestopauth/client-aug-18-748-test-diff-email-696.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-18-748-test-diff-email-696.tf, terraform/keycloak-test/realms/onestopauth/client-aug-18-748-test-diff-email-696.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-18-748-test-diff-email-696

terraform/keycloak-dev/realms/onestopauth/client-test-2-aug-19-728.tf, terraform/keycloak-prod/realms/onestopauth/client-test-2-aug-19-728.tf, terraform/keycloak-test/realms/onestopauth/client-test-2-aug-19-728.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-2-aug-19-728

terraform/keycloak-dev/realms/onestopauth/client-email-test-729.tf, terraform/keycloak-prod/realms/onestopauth/client-email-test-729.tf, terraform/keycloak-test/realms/onestopauth/client-email-test-729.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for email-test-729

terraform/keycloak-dev/realms/onestopauth/client-test-5-730.tf, terraform/keycloak-prod/realms/onestopauth/client-test-5-730.tf, terraform/keycloak-test/realms/onestopauth/client-test-5-730.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-5-730

terraform/keycloak-dev/realms/onestopauth/client-e-test-1-08-19-760.tf, terraform/keycloak-prod/realms/onestopauth/client-e-test-1-08-19-760.tf, terraform/keycloak-test/realms/onestopauth/client-e-test-1-08-19-760.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li>,<li>https://bcgov.github.io/sso-terraform-dev/request/760</li>,<li>https://bcgov.github.io/sso-terraform-dev/request/760</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li>,<li>https://bcgov.github.io/sso-terraform-dev/request/760</li>,<li>https://bcgov.github.io/sso-terraform-dev/request/760</li>,<li>https://bcgov.github.io/sso-terraform-dev/request/760</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for e-test-1-08-19-760

terraform/keycloak-dev/realms/onestopauth/client-test-958.tf, terraform/keycloak-prod/realms/onestopauth/client-test-958.tf, terraform/keycloak-test/realms/onestopauth/client-test-958.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for test-958

terraform/keycloak-dev/realms/onestopauth/client-a-793.tf, terraform/keycloak-prod/realms/onestopauth/client-a-793.tf, terraform/keycloak-test/realms/onestopauth/client-a-793.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for a-793

terraform/keycloak-dev/realms/onestopauth/client-test-859.tf, terraform/keycloak-prod/realms/onestopauth/client-test-859.tf, terraform/keycloak-test/realms/onestopauth/client-test-859.tf
```<ul>✔️Valid Redirect Urls<li>http://iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii</li></ul>```
```<ul>✔️Valid Redirect …
```
=> request: add client files for test-859

terraform/keycloak-dev/realms/onestopauth/client-test-08-20-21-892.tf, terraform/keycloak-prod/realms/onestopauth/client-test-08-20-21-892.tf, terraform/keycloak-test/realms/onestopauth/client-test-08-20-21-892.tf
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
</details>
=> request: add client files for test-08-20-21-892

terraform/keycloak-dev/realms/onestopauth/client-test-project-2-08-20-959.tf, terraform/keycloak-prod/realms/onestopauth/client-test-project-2-08-20-959.tf, terraform/keycloak-test/realms/onestopauth/client-test-project-2-08-20-959.tf
```<ul>✔️Valid Redirect Urls<li>http://test123A</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test123A</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test123A</li></ul>```
</details>
=> request: add client files for test-project-2-08-20-959

terraform/keycloak-dev/realms/onestopauth/client-project-test-23-08-20-2021-961.tf, terraform/keycloak-prod/realms/onestopauth/client-project-test-23-08-20-2021-961.tf, terraform/keycloak-test/realms/onestopauth/client-project-test-23-08-20-2021-961.tf
```<ul>✔️Valid Redirect Urls<li>http://test234</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test234</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test234</li></ul>```
</details>
=> request: add client files for project-test-23-08-20-2021-961

terraform/keycloak-dev/realms/onestopauth/client-project-962.tf, terraform/keycloak-prod/realms/onestopauth/client-project-962.tf, terraform/keycloak-test/realms/onestopauth/client-project-962.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for project-962

terraform/keycloak-dev/realms/onestopauth/client-test-2-992.tf, terraform/keycloak-prod/realms/onestopauth/client-test-2-992.tf, terraform/keycloak-test/realms/onestopauth/client-test-2-992.tf
```<ul>✔️Valid Redirect Urls<li>http://testA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testA</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testA</li></ul>```
</details>
=> request: add client files for test-2-992

terraform/keycloak-dev/realms/onestopauth/client-jon-1-265.tf, terraform/keycloak-prod/realms/onestopauth/client-jon-1-265.tf, terraform/keycloak-test/realms/onestopauth/client-jon-1-265.tf
=> request: delete client files for jon-1-265

terraform/keycloak-dev/realms/onestopauth/client-project-1-991.tf, terraform/keycloak-prod/realms/onestopauth/client-project-1-991.tf, terraform/keycloak-test/realms/onestopauth/client-project-1-991.tf
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://fdfd</li></ul>```
</details>
=> request: add client files for project-1-991

terraform/keycloak-dev/realms/onestopauth/client-test-994.tf, terraform/keycloak-prod/realms/onestopauth/client-test-994.tf, terraform/keycloak-test/realms/onestopauth/client-test-994.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-994

terraform/keycloak-dev/realms/onestopauth/client-test-project-2-08-20-959.tf, terraform/keycloak-prod/realms/onestopauth/client-test-project-2-08-20-959.tf, terraform/keycloak-test/realms/onestopauth/client-test-project-2-08-20-959.tf
=> request: delete client files for test-project-2-08-20-959

terraform/keycloak-dev/realms/onestopauth/client-project-test-23-08-20-2021-961.tf, terraform/keycloak-prod/realms/onestopauth/client-project-test-23-08-20-2021-961.tf, terraform/keycloak-test/realms/onestopauth/client-project-test-23-08-20-2021-961.tf
=> request: delete client files for project-test-23-08-20-2021-961

terraform/keycloak-dev/realms/onestopauth/client-project-962.tf, terraform/keycloak-prod/realms/onestopauth/client-project-962.tf, terraform/keycloak-test/realms/onestopauth/client-project-962.tf
=> request: delete client files for project-962

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-222211111111111111-925.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-222211111111111111-925.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-222211111111111111-925.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-222211111111111111-925

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-222211111111111111-925.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-222211111111111111-925.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-222211111111111111-925.tf
=> request: delete client files for testprojectjunmin-222211111111111111-925

terraform/keycloak-dev/realms/onestopauth/client-asdfaaaaaaaaaa-232.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfaaaaaaaaaa-232.tf, terraform/keycloak-test/realms/onestopauth/client-asdfaaaaaaaaaa-232.tf
=> request: delete client files for asdfaaaaaaaaaa-232

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-22221111-1059.tf, terraform/keycloak-prod/realms/onestopauth/client-testprojectjunmin-22221111-1059.tf, terraform/keycloak-test/realms/onestopauth/client-testprojectjunmin-22221111-1059.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-22221111-1059

terraform/keycloak-dev/realms/onestopauth/client-test-1061.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1061.tf, terraform/keycloak-test/realms/onestopauth/client-test-1061.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-1061

terraform/keycloak-dev/realms/onestopauth/client-test-1060.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1060.tf, terraform/keycloak-test/realms/onestopauth/client-test-1060.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://prod</li></ul>```
</details>
=> request: add client files for test-1060

terraform/keycloak-dev/realms/onestopauth/client-august-30-902-am-test-1255.tf, terraform/keycloak-prod/realms/onestopauth/client-august-30-902-am-test-1255.tf, terraform/keycloak-test/realms/onestopauth/client-august-30-902-am-test-1255.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for august-30-902-am-test-1255

terraform/keycloak-dev/realms/onestopauth/client-email-test-jon-1256.tf, terraform/keycloak-prod/realms/onestopauth/client-email-test-jon-1256.tf, terraform/keycloak-test/realms/onestopauth/client-email-test-jon-1256.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for email-test-jon-1256

terraform/keycloak-dev/realms/onestopauth/client-test-regression-1257.tf, terraform/keycloak-prod/realms/onestopauth/client-test-regression-1257.tf, terraform/keycloak-test/realms/onestopauth/client-test-regression-1257.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-regression-1257

terraform/keycloak-dev/realms/onestopauth/client-aug-201242-test-1258.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-201242-test-1258.tf, terraform/keycloak-test/realms/onestopauth/client-aug-201242-test-1258.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-201242-test-1258

terraform/keycloak-dev/realms/onestopauth/client-aug-201242-test-1258.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-201242-test-1258.tf, terraform/keycloak-test/realms/onestopauth/client-aug-201242-test-1258.tf
=> request: delete client files for aug-201242-test-1258

terraform/keycloak-dev/realms/onestopauth/client-test-project-1260.tf, terraform/keycloak-prod/realms/onestopauth/client-test-project-1260.tf, terraform/keycloak-test/realms/onestopauth/client-test-project-1260.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-project-1260

terraform/keycloak-dev/realms/onestopauth/client-test-1259.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1259.tf, terraform/keycloak-test/realms/onestopauth/client-test-1259.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-1259

terraform/keycloak-dev/realms/onestopauth/client-aug-31-424-pm-1323.tf, terraform/keycloak-prod/realms/onestopauth/client-aug-31-424-pm-1323.tf, terraform/keycloak-test/realms/onestopauth/client-aug-31-424-pm-1323.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for aug-31-424-pm-1323

terraform/keycloak-dev/realms/onestopauth/client-test-2-1388.tf, terraform/keycloak-prod/realms/onestopauth/client-test-2-1388.tf, terraform/keycloak-test/realms/onestopauth/client-test-2-1388.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-2-1388

terraform/keycloak-dev/realms/onestopauth/client-testemailss-1421.tf, terraform/keycloak-prod/realms/onestopauth/client-testemailss-1421.tf, terraform/keycloak-test/realms/onestopauth/client-testemailss-1421.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testemailss-1421

terraform/keycloak-dev/realms/onestopauth/client-create-test-02-09-2021-1454.tf, terraform/keycloak-prod/realms/onestopauth/client-create-test-02-09-2021-1454.tf, terraform/keycloak-test/realms/onestopauth/client-create-test-02-09-2021-1454.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for create-test-02-09-2021-1454

terraform/keycloak-dev/realms/onestopauth/client-test-9-3-21-1486.tf, terraform/keycloak-prod/realms/onestopauth/client-test-9-3-21-1486.tf, terraform/keycloak-test/realms/onestopauth/client-test-9-3-21-1486.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-9-3-21-1486

terraform/keycloak-dev/realms/onestopauth/client-email-test-jon-1519.tf, terraform/keycloak-prod/realms/onestopauth/client-email-test-jon-1519.tf, terraform/keycloak-test/realms/onestopauth/client-email-test-jon-1519.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for email-test-jon-1519

terraform/keycloak-dev/realms/onestopauth/client-test-1520.tf, terraform/keycloak-prod/realms/onestopauth/client-test-1520.tf, terraform/keycloak-test/realms/onestopauth/client-test-1520.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-1520

terraform/keycloak-dev/realms/onestopauth/client-asdfsafa-1322.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfsafa-1322.tf, terraform/keycloak-test/realms/onestopauth/client-asdfsafa-1322.tf
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
</details>
=> request: add client files for asdfsafa-1322

terraform/keycloak-dev/realms/onestopauth/client-https-bcgov-github-io-sso-terraform-dev-requestd-1521.tf, terraform/keycloak-prod/realms/onestopauth/client-https-bcgov-github-io-sso-terraform-dev-requestd-1521.tf, terraform/keycloak-test/realms/onestopauth/client-https-bcgov-github-io-sso-terraform-dev-requestd-1521.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for https-bcgov-github-io-sso-terraform-dev-requestd-1521

terraform/keycloak-dev/realms/onestopauth/client-test-3-1552.tf, terraform/keycloak-prod/realms/onestopauth/client-test-3-1552.tf, terraform/keycloak-test/realms/onestopauth/client-test-3-1552.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-3-1552

terraform/keycloak-dev/realms/onestopauth/client-sasa-1553.tf, terraform/keycloak-prod/realms/onestopauth/client-sasa-1553.tf, terraform/keycloak-test/realms/onestopauth/client-sasa-1553.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for sasa-1553

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1626.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1626.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1626.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1626

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1651.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1651.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1651.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1651

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1684.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1684.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1684.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1684

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1685.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1685.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1685.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1685

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1686.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1686.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1686.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1686

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1687.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1687.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1687.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1687

terraform/keycloak-dev/realms/onestopauth/client-test-09-10-2021-1688.tf, terraform/keycloak-prod/realms/onestopauth/client-test-09-10-2021-1688.tf, terraform/keycloak-test/realms/onestopauth/client-test-09-10-2021-1688.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-09-10-2021-1688

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1689.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1689.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1689.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1689

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1690.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1690.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1690.tf
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1690

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1717.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1717.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1717.tf
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1717

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-1783.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-1783.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-1783.tf
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-1783

terraform/keycloak-dev/realms/onestopauth/client-test-31-1552.tf, terraform/keycloak-prod/realms/onestopauth/client-test-31-1552.tf, terraform/keycloak-test/realms/onestopauth/client-test-31-1552.tf
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-31-1552

terraform/keycloak-dev/realms/onestopauth/client-https-bcgov-github-io-sso-1521.tf, terraform/keycloak-prod/realms/onestopauth/client-https-bcgov-github-io-sso-1521.tf, terraform/keycloak-test/realms/onestopauth/client-https-bcgov-github-io-sso-1521.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for https-bcgov-github-io-sso-1521

.github/workflows/terraform-apply.yml, .github/workflows/terraform-plan.yml
set time limit on terraform jobs and retry if failing apply
=> chore: tf action

terraform/keycloak-dev/realms/onestopauth/client-sprint-demo-1882.tf, terraform/keycloak-prod/realms/onestopauth/client-sprint-demo-1882.tf, terraform/keycloak-test/realms/onestopauth/client-sprint-demo-1882.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for sprint-demo-1882

terraform/keycloak-dev/realms/onestopauth/client-aet-1981.tf, terraform/keycloak-prod/realms/onestopauth/client-aet-1981.tf, terraform/keycloak-test/realms/onestopauth/client-aet-1981.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for aet-1981

.github/workflows/terraform-plan.yml
bumpo up total allowed additions
=> fix: additions

terraform/keycloak-dev/realms/onestopauth/client-aet-2-1982.tf, terraform/keycloak-prod/realms/onestopauth/client-aet-2-1982.tf, terraform/keycloak-test/realms/onestopauth/client-aet-2-1982.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for aet-2-1982

terraform/keycloak-dev/realms/onestopauth/client-test-2080.tf, terraform/keycloak-prod/realms/onestopauth/client-test-2080.tf, terraform/keycloak-test/realms/onestopauth/client-test-2080.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-2080

terraform/keycloak-dev/realms/onestopauth/client-usability-testing-09-22-2014.tf, terraform/keycloak-prod/realms/onestopauth/client-usability-testing-09-22-2014.tf, terraform/keycloak-test/realms/onestopauth/client-usability-testing-09-22-2014.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test2</li></ul>```
</details>
=> request: add client files for usability-testing-09-22-2014

terraform/keycloak-dev/realms/onestopauth/client-test-sept-21-2113.tf, terraform/keycloak-prod/realms/onestopauth/client-test-sept-21-2113.tf, terraform/keycloak-test/realms/onestopauth/client-test-sept-21-2113.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: add client files for test-sept-21-2113

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-2114.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-2114.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-2114.tf
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-2114

terraform/keycloak-dev/realms/onestopauth/client-cypress-test-2115.tf, terraform/keycloak-prod/realms/onestopauth/client-cypress-test-2115.tf, terraform/keycloak-test/realms/onestopauth/client-cypress-test-2115.tf
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://cypress</li></ul>```
</details>
=> request: add client files for cypress-test-2115

terraform/keycloak-dev/realms/onestopauth/client-email-test-2146.tf, terraform/keycloak-prod/realms/onestopauth/client-email-test-2146.tf, terraform/keycloak-test/realms/onestopauth/client-email-test-2146.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for email-test-2146

terraform/keycloak-dev/realms/onestopauth/client-test-09-23-2147.tf, terraform/keycloak-prod/realms/onestopauth/client-test-09-23-2147.tf, terraform/keycloak-test/realms/onestopauth/client-test-09-23-2147.tf
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for test-09-23-2147

terraform/keycloak-dev/realms/onestopauth/client-test-sept-21-2113.tf, terraform/keycloak-prod/realms/onestopauth/client-test-sept-21-2113.tf, terraform/keycloak-test/realms/onestopauth/client-test-sept-21-2113.tf
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://c</li></ul>```
</details>
=> request: update client files for test-sept-21-2113

terraform/keycloak-dev/realms/onestopauth-business/client-email-with-clear-queue-2775.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for email-with-clear-queue-2775

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-2776.tf
```<ul>✔️Valid Redirect Urls<li>https://..</li></ul>```
</details>
=> request: add client files for zz-2776

terraform/keycloak-dev/realms/onestopauth-both/client-test-2774.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for test-2774

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-2806.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-2806.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-2806

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-2807.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-2807.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li>,<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-2807

terraform/keycloak-dev/realms/onestopauth-basic/client-asde-2808.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for asde-2808

terraform/keycloak-dev/realms/onestopauth-basic/client-hjhj-2809.tf
```<ul>✔️Valid Redirect Urls<li>http://bceid</li></ul>```
</details>
=> request: add client files for hjhj-2809

terraform/keycloak-dev/realms/onestopauth-basic/client-ztest-2-2810.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ztest-2-2810.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for ztest-2-2810

terraform/keycloak-dev/realms/onestopauth-basic/client-email-test-2811.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for email-test-2811

terraform/keycloak-dev/realms/onestopauth/client-conf-2-2872.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for conf-2-2872

terraform/keycloak-dev/realms/onestopauth/client-zz-2873.tf, terraform/keycloak-prod/realms/onestopauth/client-zz-2873.tf, terraform/keycloak-test/realms/onestopauth/client-zz-2873.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-2873

terraform/keycloak-dev/realms/onestopauth/client-conf-2-2872.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li>,<li>http://localhost:3000</li>,<li>http://localhost:3000/*</li></ul>```
</details>
=> request: update client files for conf-2-2872

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-2971.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceid-test-2971.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
</details>
=> request: add client files for bceid-test-2971

terraform/keycloak-dev/realms/onestopauth-basic/client-a-2938.tf, terraform/keycloak-test/realms/onestopauth-basic/client-a-2938.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for a-2938

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-prod-3004.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
</details>
=> request: add client files for bceid-prod-3004

terraform/keycloak-dev/realms/onestopauth/client-bceid-dev-test-3005.tf, terraform/keycloak-test/realms/onestopauth/client-bceid-dev-test-3005.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for bceid-dev-test-3005

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-no-prod-3103.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceid-no-prod-3103.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for bceid-no-prod-3103

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-with-prod-3104.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for bceid-with-prod-3104

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3137.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-3137.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3137

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3136.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-3136.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3136

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3136.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-3136.tf
=> request: delete client files for zz-3136

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3037.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-3037.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3037

terraform/keycloak-dev/realms/onestopauth-basic/client-test-3070.tf, terraform/keycloak-test/realms/onestopauth-basic/client-test-3070.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
=> request: add client files for test-3070

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3169.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-3169.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3169

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-3202.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceid-test-3202.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://b</li></ul>```
</details>
=> request: add client files for bceid-test-3202

terraform/keycloak-dev/realms/onestopauth-basic/client-nov-16-3204.tf, terraform/keycloak-test/realms/onestopauth-basic/client-nov-16-3204.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for nov-16-3204

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-3205.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceid-test-3205.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test</li></ul>```
</details>
=> request: add client files for bceid-test-3205

terraform/keycloak-dev/realms/onestopauth/client-hhjgfj-3071.tf
```<ul>✔️Valid Redirect Urls<li>http://www.google.ca</li></ul>```
</details>
=> request: add client files for hhjgfj-3071

terraform/keycloak-dev/realms/onestopauth-both/client-test-2641.tf, terraform/keycloak-test/realms/onestopauth-both/client-test-2641.tf
```<ul>✔️Valid Redirect Urls<li>https://www.DEV</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.TEST</li></ul>```
</details>
=> request: add client files for test-2641

terraform/keycloak-dev/realms/onestopauth-basic/client-start-b-cei-d-dev-3302.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/sso-terraform-dev/request/2410</li></ul>```
</details>
=> request: add client files for start-b-cei-d-dev-3302

terraform/keycloak-dev/realms/onestopauth-basic/client-bce-id-dev-canedit-test-3301.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/DEV</li></ul>```
</details>
=> request: add client files for bce-id-dev-canedit-test-3301

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-prod-test-3400.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for bceid-prod-test-3400

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-prod-911-3433.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
</details>
=> request: add client files for bceid-prod-911-3433

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3268.tf, terraform/keycloak-test/realms/onestopauth-basic/client-zz-3268.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li>,<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3268

terraform/keycloak-dev/realms/onestopauth/client-zz-3466.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3466

terraform/keycloak-dev/realms/onestopauth/client-zz-3467.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3467

terraform/keycloak-dev/realms/onestopauth-basic/client-zz-3468.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-3468

terraform/keycloak-dev/realms/onestopauth-basic/client-sdfa-3334.tf, terraform/keycloak-test/realms/onestopauth-basic/client-sdfa-3334.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/sso-terraform-dev/request/2410</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/sso-terraform-dev/request/2410</li></ul>```
</details>
=> request: add client files for sdfa-3334

terraform/keycloak-dev/realms/onestopauth/client-idir-test-dev-3565.tf, terraform/keycloak-prod/realms/onestopauth/client-idir-test-dev-3565.tf, terraform/keycloak-test/realms/onestopauth/client-idir-test-dev-3565.tf
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/prod</li></ul>```
</details>
=> request: add client files for idir-test-dev-3565

terraform/keycloak-dev/realms/onestopauth-business/client-bceidbasic-idir-devtestprod-3567.tf, terraform/keycloak-test/realms/onestopauth-business/client-bceidbasic-idir-devtestprod-3567.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/dev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/test</li></ul>```
</details>
=> request: add client files for bceidbasic-idir-devtestprod-3567

.github/workflows/request.yml, .github/workflows/terraform-plan.yml
bump action version to most recent
=> chore: bump gh action

terraform/keycloak-dev/realms/onestopauth/client-123-3532.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for 123-3532

terraform/keycloak-dev/realms/onestopauth-basic/client-bceidbasic-idir-dev-test-3566.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceidbasic-idir-dev-test-3566.tf
=> request: delete client files for bceidbasic-idir-dev-test-3566

terraform/keycloak-dev/realms/onestopauth-basic/client-testprojectjunmin-2222-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testprojectjunmin-2222-1

terraform/keycloak-dev/realms/onestopauth-basic/client-test-3070.tf, terraform/keycloak-test/realms/onestopauth-basic/client-test-3070.tf
=> request: delete client files for test-3070

terraform/keycloak-dev/realms/onestopauth-basic/client-ztest-2-2810.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ztest-2-2810.tf
=> request: delete client files for ztest-2-2810

terraform/keycloak-dev/realms/onestopauth-basic/client-test-mappers-3699.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for test-mappers-3699

terraform/keycloak-dev/realms/onestopauth-basic/client-b-ce-id-prod-3730.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for b-ce-id-prod-3730

terraform/keycloak-dev/realms/onestopauth/client-idir-azure-3796.tf
```<ul>✔️Valid Redirect Urls<li>http://a</li></ul>```
</details>
=> request: add client files for idir-azure-3796

terraform/keycloak-dev/realms/onestopauth/client-test-zorin-jan-4-3961.tf
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/dev</li></ul>```
</details>
=> request: add client files for test-zorin-jan-4-3961

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-apprval-test-4060.tf
```<ul>✔️Valid Redirect Urls<li>http://dev</li></ul>```
</details>
=> request: add client files for bceid-apprval-test-4060

terraform/keycloak-dev/realms/onestopauth/client-jon-junmin-test-01-04-22-4027.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost</li></ul>```
</details>
=> request: add client files for jon-junmin-test-01-04-22-4027

terraform/keycloak-dev/realms/onestopauth/client-sample-project-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for sample-project-1

terraform/keycloak-dev/realms/onestopauth/client-zorin-test-jan-4-teams-take-2-4291.tf, terraform/keycloak-test/realms/onestopauth/client-zorin-test-jan-4-teams-take-2-4291.tf
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/devChanged</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/testCHANGED</li></ul>```
</details>
=> request: add client files for zorin-test-jan-4-teams-take-2-4291

terraform/keycloak-dev/realms/onestopauth/client-zorin-test-teams-jan-17-2-4292.tf
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/dev</li></ul>```
</details>
=> request: add client files for zorin-test-teams-jan-17-2-4292

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-4258.tf
```<ul>✔️Valid Redirect Urls<li>http://example.cca</li></ul>```
</details>
=> request: add client files for tians-testing-4258

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-2-4324.tf
```<ul>✔️Valid Redirect Urls<li>https://example.abc</li></ul>```
</details>
=> request: add client files for tians-testing-2-4324

terraform/keycloak-dev/realms/onestopauth/client-demo-for-n-8-ntt-4457.tf, terraform/keycloak-test/realms/onestopauth/client-demo-for-n-8-ntt-4457.tf
=> request: delete client files for demo-for-n-8-ntt-4457

terraform/keycloak-dev/realms/onestopauth-basic/client-testing-4-4523.tf, terraform/keycloak-test/realms/onestopauth-basic/client-testing-4-4523.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for testing-4-4523

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-single-member-4524.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-single-member-4524

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-multiple-members-4525.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-4525

terraform/keycloak-dev/realms/onestopauth/client-ztest-single-member-4527.tf
```<ul>✔️Valid Redirect Urls<li>https://test</li></ul>```
</details>
=> request: add client files for ztest-single-member-4527

terraform/keycloak-dev/realms/onestopauth/client-ztest-multiple-member-4528.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/update</li></ul>```
</details>
=> request: add client files for ztest-multiple-member-4528

terraform/keycloak-dev/realms/onestopauth/client-sample-project-11-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for sample-project-11-1

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-multiple-members-2-4588.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-multiple-members-2-4588.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-2-4588

terraform/keycloak-dev/realms/onestopauth/client-ztest-jan-30-4753.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for ztest-jan-30-4753

terraform/keycloak-dev/realms/onestopauth/client-ztest-jan-30-4753.tf
=> request: delete client files for ztest-jan-30-4753

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-multiple-members-2-4588.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-multiple-members-2-4588.tf
=> request: delete client files for tians-testing-multiple-members-2-4588

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-multiple-members-4786.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-multiple-members-4786.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-4786

terraform/keycloak-dev/realms/onestopauth/client-jan-31-test-team-role-edit-4819.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for jan-31-test-team-role-edit-4819

terraform/keycloak-dev/realms/onestopauth/client-jan-31-test-team-role-edit-2-4820.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for jan-31-test-team-role-edit-2-4820

terraform/keycloak-dev/realms/onestopauth/client-jan-31-test-team-role-edit-3-4821.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for jan-31-test-team-role-edit-3-4821

terraform/keycloak-dev/realms/onestopauth/client-test-zorin-dec-15-3829.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for test-zorin-dec-15-3829

terraform/keycloak-dev/realms/onestopauth/client-jan-31-test-5-delete-4852.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for jan-31-test-5-delete-4852

terraform/keycloak-dev/realms/onestopauth/client-jan-31-test-6-delete-4853.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for jan-31-test-6-delete-4853

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-feb-1-4885.tf
```<ul>✔️Valid Redirect Urls<li>https://url.com</li></ul>```
</details>
=> request: add client files for bceid-test-feb-1-4885

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-feb-1-2-4886.tf
```<ul>✔️Valid Redirect Urls<li>https://example1</li></ul>```
</details>
=> request: add client files for bceid-test-feb-1-2-4886

terraform/keycloak-dev/realms/onestopauth-basic/client-bceid-test-feb-1-3-4887.tf
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca</li></ul>```
</details>
=> request: add client files for bceid-test-feb-1-3-4887

terraform/keycloak-dev/realms/onestopauth/client-feb-2-test-team-access-to-json-4918.tf
```<ul>✔️Valid Redirect Urls<li>https://testindev</li></ul>```
</details>
=> request: add client files for feb-2-test-team-access-to-json-4918

terraform/keycloak-dev/realms/onestopauth/client-feb-3-test-team-access-to-files-4951.tf
```<ul>✔️Valid Redirect Urls<li>http://www.test.ca</li></ul>```
</details>
=> request: add client files for feb-3-test-team-access-to-files-4951

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-3367.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3001</li></ul>```
</details>
=> request: add client files for testprojectjunmin-3367

terraform/keycloak-dev/realms/onestopauth/client-testprojectjunmin-3367.tf
=> request: delete client files for testprojectjunmin-3367

terraform/keycloak-dev/realms/onestopauth-business/client-feb-4-test-4-h-5019.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-4-test-4-h-5019

terraform/keycloak-dev/realms/onestopauth-business/client-tians-testing-bceid-5017.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-bceid-5017

terraform/keycloak-dev/realms/onestopauth-business/client-feb-4-test-4-h-5019.tf, terraform/keycloak-test/realms/onestopauth-business/client-feb-4-test-4-h-5019.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: update client files for feb-4-test-4-h-5019

terraform/keycloak-dev/realms/onestopauth/client-realm-profile-app-2608.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for realm-profile-app-2608

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-multiple-members-2-9-5083.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-multiple-members-2-9-5083.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-2-9-5083

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-multiple-members-no-prod-5086.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-multiple-members-no-prod-5086.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-no-prod-5086

terraform/keycloak-dev/realms/onestopauth/client-jon-s-test-5050.tf, terraform/keycloak-test/realms/onestopauth/client-jon-s-test-5050.tf
```<ul>✔️Valid Redirect Urls<li>https://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://test.test.com</li></ul>```
</details>
=> request: add client files for jon-s-test-5050

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-idir-only-with-team-5149.tf, terraform/keycloak-prod/realms/onestopauth/client-tians-testing-idir-only-with-team-5149.tf, terraform/keycloak-test/realms/onestopauth/client-tians-testing-idir-only-with-team-5149.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-idir-only-with-team-5149

terraform/keycloak-dev/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-5182.tf, terraform/keycloak-test/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-5182.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-dev-test-5182

terraform/keycloak-dev/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-5182.tf, terraform/keycloak-test/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-5182.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: update client files for tians-testing-b-ce-id-dev-test-5182

terraform/keycloak-dev/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-5182.tf, terraform/keycloak-test/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-5182.tf
=> request: delete client files for tians-testing-b-ce-id-dev-test-5182

terraform/keycloak-dev/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-prod-5183.tf, terraform/keycloak-test/realms/onestopauth-both/client-tians-testing-b-ce-id-dev-test-prod-5183.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-dev-test-prod-5183

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-single-member-2-5248.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-single-member-2-5248

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-single-member-3-5281.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-single-member-3-5281

terraform/keycloak-dev/realms/onestopauth-basic/client-test-feb-15-5283.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for test-feb-15-5283

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-single-member-4524.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleaa2</li></ul>```
</details>
=> request: update client files for tians-testing-single-member-4524

terraform/keycloak-dev/realms/onestopauth/client-test-feb-15-2-5314.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for test-feb-15-2-5314

terraform/keycloak-dev/realms/onestopauth/client-realm-profile-app-2608.tf, terraform/keycloak-prod/realms/onestopauth/client-realm-profile-app-2608.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: update client files for realm-profile-app-2608

terraform/keycloak-dev/realms/onestopauth-basic/client-bceidbasic-2-5414.tf, terraform/keycloak-test/realms/onestopauth-basic/client-bceidbasic-2-5414.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for bceidbasic-2-5414

terraform/keycloak-dev/realms/onestopauth-basic/client-bceidtest-5446.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for bceidtest-5446

terraform/keycloak-dev/realms/onestopauth/client-feb-21-test-sso-admin-redirect-edit-5479.tf, terraform/keycloak-test/realms/onestopauth/client-feb-21-test-sso-admin-redirect-edit-5479.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
</details>
=> request: add client files for feb-21-test-sso-admin-redirect-edit-5479

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-21-test-sso-admin-web-origin-update-5480.tf
```<ul>✔️Valid Redirect Urls<li>http://www.test.ca</li></ul>```
</details>
=> request: add client files for feb-21-test-sso-admin-web-origin-update-5480

terraform/keycloak-dev/realms/onestopauth/client-feb-21-test-sso-admin-redirect-edit-5479.tf, terraform/keycloak-test/realms/onestopauth/client-feb-21-test-sso-admin-redirect-edit-5479.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:6000</li>,<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
</details>
=> request: update client files for feb-21-test-sso-admin-redirect-edit-5479

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-21-test-sso-admin-web-origin-update-5480.tf
=> request: delete client files for feb-21-test-sso-admin-web-origin-update-5480

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-single-member-3-5281.tf
=> request: delete client files for tians-testing-single-member-3-5281

terraform/keycloak-dev/realms/onestopauth-both/client-tians-testing-bceid-dev-and-test-5513.tf, terraform/keycloak-test/realms/onestopauth-both/client-tians-testing-bceid-dev-and-test-5513.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-bceid-dev-and-test-5513

terraform/keycloak-dev/realms/onestopauth-business/client-tians-testing-b-ce-id-dev-test-and-prod-5514.tf, terraform/keycloak-test/realms/onestopauth-business/client-tians-testing-b-ce-id-dev-test-and-prod-5514.tf
```<ul>✔️Valid Redirect Urls<li>https://testDev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://testTest</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-dev-test-and-prod-5514

terraform/keycloak-dev/realms/onestopauth/client-play-ground-public-5515.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for play-ground-public-5515

terraform/keycloak-dev/realms/onestopauth/client-test-1-5579.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for test-1-5579

terraform/keycloak-dev/realms/onestopauth/client-test-feb-23-5380.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:4040</li></ul>```
</details>
=> request: add client files for test-feb-23-5380

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-single-2-25-5710.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-single-2-25-5710

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-24-test-5-5648.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-24-test-5-5648

terraform/keycloak-dev/realms/onestopauth/client-testidirrealm-5650.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for testidirrealm-5650

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-24-test-4-5647.tf, terraform/keycloak-test/realms/onestopauth-basic/client-feb-24-test-4-5647.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
</details>
=> request: add client files for feb-24-test-4-5647

terraform/keycloak-dev/realms/onestopauth/client-feb-24-test-3-5646.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-24-test-3-5646

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-24-test-2-5645.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-24-test-2-5645

terraform/keycloak-dev/realms/onestopauth/client-feb-24-test-1-5644.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-24-test-1-5644

terraform/keycloak-dev/realms/onestopauth/client-test-feb-23-5380.tf
=> request: delete client files for test-feb-23-5380

terraform/keycloak-dev/realms/onestopauth/client-feb-24-jonathan-aiden-demo-5612.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-24-jonathan-aiden-demo-5612

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-single-member-4524.tf
=> request: delete client files for tians-testing-single-member-4524

terraform/keycloak-dev/realms/onestopauth/client-firstproject-13.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for firstproject-13

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-single-2-25-a-5711.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledfsasd</li></ul>```
</details>
=> request: add client files for tians-testing-single-2-25-a-5711

terraform/keycloak-dev/realms/onestopauth/client-feb-27-idir-only-5745.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-27-idir-only-5745

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-27-test-2-5744.tf, terraform/keycloak-test/realms/onestopauth-basic/client-feb-27-test-2-5744.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/testCHANGED</li></ul>```
</details>
=> request: add client files for feb-27-test-2-5744

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-27-test-1-5743.tf, terraform/keycloak-test/realms/onestopauth-basic/client-feb-27-test-1-5743.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-27-test-1-5743

terraform/keycloak-dev/realms/onestopauth/client-mytestproject-5776.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for mytestproject-5776

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-2-28-5809.tf
```<ul>✔️Valid Redirect Urls<li>http://example.ccaa</li></ul>```
</details>
=> request: add client files for tians-testing-2-28-5809

terraform/keycloak-dev/realms/onestopauth/client-mysamplerequest-1.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for mysamplerequest-1

terraform/keycloak-dev/realms/onestopauth/client-feb-28-test-idir-5842.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for feb-28-test-idir-5842

terraform/keycloak-dev/realms/onestopauth/client-asdfsafa-1322.tf, terraform/keycloak-prod/realms/onestopauth/client-asdfsafa-1322.tf, terraform/keycloak-test/realms/onestopauth/client-asdfsafa-1322.tf
=> request: delete client files for asdfsafa-1322

terraform/keycloak-dev/realms/onestopauth/client-feb-28-pm-test-1-idir-5908.tf, terraform/keycloak-prod/realms/onestopauth/client-feb-28-pm-test-1-idir-5908.tf, terraform/keycloak-test/realms/onestopauth/client-feb-28-pm-test-1-idir-5908.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/prod</li></ul>```
</details>
=> request: add client files for feb-28-pm-test-1-idir-5908

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-27-test-1-5743.tf, terraform/keycloak-test/realms/onestopauth-basic/client-feb-27-test-1-5743.tf
=> request: delete client files for feb-27-test-1-5743

terraform/keycloak-dev/realms/onestopauth/client-feb-24-jonathan-aiden-demo-5612.tf
=> request: delete client files for feb-24-jonathan-aiden-demo-5612

terraform/keycloak-dev/realms/onestopauth/client-feb-2-test-team-access-to-json-4918.tf
=> request: delete client files for feb-2-test-team-access-to-json-4918

terraform/keycloak-dev/realms/onestopauth/client-feb-28-pm-test-2-idir-sso-admin-edits-5909.tf, terraform/keycloak-prod/realms/onestopauth/client-feb-28-pm-test-2-idir-sso-admin-edits-5909.tf, terraform/keycloak-test/realms/onestopauth/client-feb-28-pm-test-2-idir-sso-admin-edits-5909.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/prod</li></ul>```
</details>
=> request: add client files for feb-28-pm-test-2-idir-sso-admin-edits-5909

terraform/keycloak-dev/realms/onestopauth/client-feb-28-pm-test-3-idir-5910.tf, terraform/keycloak-prod/realms/onestopauth/client-feb-28-pm-test-3-idir-5910.tf, terraform/keycloak-test/realms/onestopauth/client-feb-28-pm-test-3-idir-5910.tf
```<ul>✔️Valid Redirect Urls<li>http://www.test.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/testCHANGED</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:10023</li></ul>```
</details>
=> request: add client files for feb-28-pm-test-3-idir-5910

terraform/keycloak-dev/realms/onestopauth-basic/client-feb-28-test-4-b-ce-id-non-prod-5911.tf, terraform/keycloak-test/realms/onestopauth-basic/client-feb-28-test-4-b-ce-id-non-prod-5911.tf
```<ul>✔️Valid Redirect Urls<li>http://www.test.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for feb-28-test-4-b-ce-id-non-prod-5911

terraform/keycloak-dev/realms/onestopauth-basic/client-mar-1-test-1-b-ce-id-5941.tf, terraform/keycloak-test/realms/onestopauth-basic/client-mar-1-test-1-b-ce-id-5941.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/testCHANGED</li></ul>```
</details>
=> request: add client files for mar-1-test-1-b-ce-id-5941

terraform/keycloak-dev/realms/onestopauth/client-march-1-create-with-teams-5974.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for march-1-create-with-teams-5974

terraform/keycloak-dev/realms/onestopauth/client-march-1-create-with-teams-2-5975.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for march-1-create-with-teams-2-5975

terraform/keycloak-dev/realms/onestopauth/client-march-1-teams-test-6-5745.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for march-1-teams-test-6-5745

terraform/keycloak-dev/realms/onestopauth/client-march-1-teams-test-6-5745.tf
=> request: delete client files for march-1-teams-test-6-5745

terraform/keycloak-dev/realms/onestopauth/client-march-1-test-7-all-admins-6008.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
</details>
=> request: add client files for march-1-test-7-all-admins-6008

terraform/keycloak-dev/realms/onestopauth/client-newtest-6041.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for newtest-6041

terraform/keycloak-dev/realms/onestopauth/client-march-1-test-9-z-t-6042.tf
```<ul>✔️Valid Redirect Urls<li>http://www.test.ca</li></ul>```
</details>
=> request: add client files for march-1-test-9-z-t-6042

terraform/keycloak-dev/realms/onestopauth/client-march-1-idir-sso-admin-5909.tf, terraform/keycloak-prod/realms/onestopauth/client-march-1-idir-sso-admin-5909.tf, terraform/keycloak-test/realms/onestopauth/client-march-1-idir-sso-admin-5909.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/prod</li></ul>```
</details>
=> request: add client files for march-1-idir-sso-admin-5909

terraform/keycloak-dev/realms/onestopauth-basic/client-march-2-b-ce-id-non-prod-to-prod-6043.tf, terraform/keycloak-test/realms/onestopauth-basic/client-march-2-b-ce-id-non-prod-to-prod-6043.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:10004</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange123</li></ul>```
</details>
=> request: add client files for march-2-b-ce-id-non-prod-to-prod-6043

terraform/keycloak-dev/realms/onestopauth-basic/client-march-3-jon-b-ce-id-basic-test-6073.tf, terraform/keycloak-test/realms/onestopauth-basic/client-march-3-jon-b-ce-id-basic-test-6073.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://bceidTest.com</li></ul>```
</details>
=> request: add client files for march-3-jon-b-ce-id-basic-test-6073

terraform/keycloak-dev/realms/onestopauth/client-mar-02-idir-test-6074.tf, terraform/keycloak-prod/realms/onestopauth/client-mar-02-idir-test-6074.tf, terraform/keycloak-test/realms/onestopauth/client-mar-02-idir-test-6074.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for mar-02-idir-test-6074

terraform/keycloak-dev/realms/onestopauth-basic/client-jon-mar-3-b-ce-id-basic-non-prod-to-prod-6075.tf, terraform/keycloak-test/realms/onestopauth-basic/client-jon-mar-3-b-ce-id-basic-non-prod-to-prod-6075.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://bceidTest.com</li></ul>```
</details>
=> request: add client files for jon-mar-3-b-ce-id-basic-non-prod-to-prod-6075

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-single-member-3-2-6076.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-single-member-3-2-6076

terraform/keycloak-dev/realms/onestopauth/client-kuro-mar-02-idir-test-6077.tf, terraform/keycloak-prod/realms/onestopauth/client-kuro-mar-02-idir-test-6077.tf, terraform/keycloak-test/realms/onestopauth/client-kuro-mar-02-idir-test-6077.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for kuro-mar-02-idir-test-6077

terraform/keycloak-dev/realms/onestopauth/client-junmin-newintegration-6106.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-newintegration-6106

terraform/keycloak-dev/realms/onestopauth-basic/client-march-3-test-b-ce-id-non-p-rod-6139.tf, terraform/keycloak-test/realms/onestopauth-basic/client-march-3-test-b-ce-id-non-p-rod-6139.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/testCHANGED</li></ul>```
</details>
=> request: add client files for march-3-test-b-ce-id-non-p-rod-6139

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-b-ce-id-add-prod-later-6172.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-add-prod-later-6172

terraform/keycloak-dev/realms/onestopauth-basic/client-kuro-mar-03-b-ce-id-basic-test-6205.tf, terraform/keycloak-test/realms/onestopauth-basic/client-kuro-mar-03-b-ce-id-basic-test-6205.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://bceidTest.com</li></ul>```
</details>
=> request: add client files for kuro-mar-03-b-ce-id-basic-test-6205

terraform/keycloak-dev/realms/onestopauth-business/client-kuro-mar-03-b-ce-id-business-test-6238.tf, terraform/keycloak-test/realms/onestopauth-business/client-kuro-mar-03-b-ce-id-business-test-6238.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bceidTest.com</li></ul>```
</details>
=> request: add client files for kuro-mar-03-b-ce-id-business-test-6238

terraform/keycloak-dev/realms/onestopauth-both/client-kuro-mar-03-b-ce-id-both-test-6239.tf, terraform/keycloak-test/realms/onestopauth-both/client-kuro-mar-03-b-ce-id-both-test-6239.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bceidTest.com</li></ul>```
</details>
=> request: add client files for kuro-mar-03-b-ce-id-both-test-6239

terraform/keycloak-dev/realms/onestopauth/client-kuro-link-error-test-6271.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for kuro-link-error-test-6271

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-3-4-6304.tf
```<ul>✔️Valid Redirect Urls<li>http://example.ccaa</li></ul>```
</details>
=> request: add client files for tians-testing-3-4-6304

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-3-4-add-prod-later-6306.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-3-4-add-prod-later-6306

terraform/keycloak-dev/realms/onestopauth-basic/client-kuro-mar-04-b-ce-id-basic-non-prod-6305.tf, terraform/keycloak-test/realms/onestopauth-basic/client-kuro-mar-04-b-ce-id-basic-non-prod-6305.tf
```<ul>✔️Valid Redirect Urls<li>http://DevBCeID.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://TestBCeID.com</li></ul>```
</details>
=> request: add client files for kuro-mar-04-b-ce-id-basic-non-prod-6305

terraform/keycloak-dev/realms/onestopauth-business/client-march-4-zorin-test-1-6337.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost.8080</li></ul>```
</details>
=> request: add client files for march-4-zorin-test-1-6337

terraform/keycloak-dev/realms/onestopauth-business/client-march-4-test-2-6338.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8080</li></ul>```
</details>
=> request: add client files for march-4-test-2-6338

terraform/keycloak-dev/realms/onestopauth-basic/client-kuro-mar-07-b-ce-id-basic-test-6370.tf, terraform/keycloak-test/realms/onestopauth-basic/client-kuro-mar-07-b-ce-id-basic-test-6370.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://bceidTest.com</li></ul>```
</details>
=> request: add client files for kuro-mar-07-b-ce-id-basic-test-6370

terraform/keycloak-dev/realms/onestopauth-business/client-kuro-mar-07-b-ce-id-business-test-6371.tf, terraform/keycloak-test/realms/onestopauth-business/client-kuro-mar-07-b-ce-id-business-test-6371.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://bceidTest.com</li></ul>```
</details>
=> request: add client files for kuro-mar-07-b-ce-id-business-test-6371

terraform/keycloak-dev/realms/onestopauth-both/client-kuro-mar-07-b-ce-id-both-test-6372.tf, terraform/keycloak-test/realms/onestopauth-both/client-kuro-mar-07-b-ce-id-both-test-6372.tf
```<ul>✔️Valid Redirect Urls<li>http://bceidDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://bceidTest.com</li></ul>```
</details>
=> request: add client files for kuro-mar-07-b-ce-id-both-test-6372

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-multiple-members-3-8-6403.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledfsasd</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-3-8-6403

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-with-existing-team-3-8-6436.tf
```<ul>✔️Valid Redirect Urls<li>https://existingTeam</li></ul>```
</details>
=> request: add client files for tians-testing-with-existing-team-3-8-6436

terraform/keycloak-dev/realms/onestopauth/client-junmin-newintegration-6106.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: update client files for junmin-newintegration-6106

terraform/keycloak-dev/realms/onestopauth/client-junmin-createnewonewithteam-6469.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-createnewonewithteam-6469

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-on-davids-case-6535.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledfsasd</li></ul>```
</details>
=> request: add client files for tians-testing-on-davids-case-6535

terraform/keycloak-dev/realms/onestopauth/client-ent-user-notification-for-non-b-ce-id-6536.tf
```<ul>✔️Valid Redirect Urls<li>http://devRedirect.com</li></ul>```
</details>
=> request: add client files for ent-user-notification-for-non-b-ce-id-6536

terraform/keycloak-dev/realms/onestopauth/client-ent-team-notification-for-non-b-ce-id-6537.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
</details>
=> request: add client files for ent-team-notification-for-non-b-ce-id-6537

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-user-notification-for-b-ce-id-in-non-prod-6538.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
</details>
=> request: add client files for ent-user-notification-for-b-ce-id-in-non-prod-6538

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-team-notification-for-b-ce-id-in-non-prod-6539.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
</details>
=> request: add client files for ent-team-notification-for-b-ce-id-in-non-prod-6539

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-user-notification-for-b-ce-id-in-prod-6540.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
</details>
=> request: add client files for ent-user-notification-for-b-ce-id-in-prod-6540

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-team-notification-for-b-ce-id-in-prod-6541.tf
```<ul>✔️Valid Redirect Urls<li>http://dev.com</li></ul>```
</details>
=> request: add client files for ent-team-notification-for-b-ce-id-in-prod-6541

terraform/keycloak-dev/realms/onestopauth/client-ent-part-2-user-notification-for-non-b-ce-id-6542.tf
```<ul>✔️Valid Redirect Urls<li>http://devchange.com</li></ul>```
</details>
=> request: add client files for ent-part-2-user-notification-for-non-b-ce-id-6542

terraform/keycloak-dev/realms/onestopauth/client-ent-part-2-team-notification-for-non-b-ce-id-6543.tf
```<ul>✔️Valid Redirect Urls<li>http://devchange.com</li></ul>```
</details>
=> request: add client files for ent-part-2-team-notification-for-non-b-ce-id-6543

terraform/keycloak-dev/realms/onestopauth/client-newtest-6041.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: update client files for newtest-6041

terraform/keycloak-dev/realms/onestopauth/client-testemailagain-1555.tf, terraform/keycloak-prod/realms/onestopauth/client-testemailagain-1555.tf, terraform/keycloak-test/realms/onestopauth/client-testemailagain-1555.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:1000</li></ul>```
</details>
=> request: add client files for testemailagain-1555

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-2-user-notification-for-b-ce-id-in-non-prod-6601.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-2-user-notification-for-b-ce-id-in-non-prod-6601

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-2-team-notification-for-b-ce-id-in-non-prod-6602.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-2-team-notification-for-b-ce-id-in-non-prod-6602

terraform/keycloak-dev/realms/onestopauth-basic/client-march-10-test-6603.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:10004</li></ul>```
</details>
=> request: add client files for march-10-test-6603

terraform/keycloak-dev/realms/onestopauth-basic/client-march-10-ent-part-2-6604.tf, terraform/keycloak-test/realms/onestopauth-basic/client-march-10-ent-part-2-6604.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
</details>
=> request: add client files for march-10-ent-part-2-6604

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-2-user-notification-for-b-ce-id-in-prod-6607.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ent-part-2-user-notification-for-b-ce-id-in-prod-6607.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-2-user-notification-for-b-ce-id-in-prod-6607

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-2-team-notification-for-b-ce-id-in-prod-6608.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ent-part-2-team-notification-for-b-ce-id-in-prod-6608.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-2-team-notification-for-b-ce-id-in-prod-6608

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-terraform-apply-1-6609.tf
```<ul>✔️Valid Redirect Urls<li>http://example.ccaa</li></ul>```
</details>
=> request: add client files for tians-testing-terraform-apply-1-6609

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-terraform-apply-3-6611.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleaa</li></ul>```
</details>
=> request: add client files for tians-testing-terraform-apply-3-6611

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-terraform-apply-4-6612.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledfsasd</li></ul>```
</details>
=> request: add client files for tians-testing-terraform-apply-4-6612

terraform/keycloak-dev/realms/onestopauth-basic/client-march-10-test-2-zorin-6613.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
=> request: add client files for march-10-test-2-zorin-6613

terraform/keycloak-dev/realms/onestopauth/client-march-10-test-3-zorin-6614.tf, terraform/keycloak-prod/realms/onestopauth/client-march-10-test-3-zorin-6614.tf, terraform/keycloak-test/realms/onestopauth/client-march-10-test-3-zorin-6614.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/prod</li></ul>```
</details>
=> request: add client files for march-10-test-3-zorin-6614

terraform/keycloak-dev/realms/onestopauth/client-junminnewint-6568.tf
=> request: delete client files for junminnewint-6568

terraform/keycloak-dev/realms/onestopauth/client-testemailagain-1555.tf, terraform/keycloak-prod/realms/onestopauth/client-testemailagain-1555.tf, terraform/keycloak-test/realms/onestopauth/client-testemailagain-1555.tf
=> request: delete client files for testemailagain-1555

terraform/keycloak-dev/realms/onestopauth/client-realm-profile-app-2608.tf, terraform/keycloak-prod/realms/onestopauth/client-realm-profile-app-2608.tf
=> request: delete client files for realm-profile-app-2608

terraform/keycloak-dev/realms/onestopauth/client-junminnewintegration-6615.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junminnewintegration-6615

terraform/keycloak-dev/realms/onestopauth/client-tian-part-3-ticket-1-6635.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tian-part-3-ticket-1-6635

terraform/keycloak-dev/realms/onestopauth-business/client-tian-part-3-ticket-2-6636.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledfsasd</li></ul>```
</details>
=> request: add client files for tian-part-3-ticket-2-6636

terraform/keycloak-dev/realms/onestopauth/client-tian-part-3-ticket-3-6637.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddddd</li></ul>```
</details>
=> request: add client files for tian-part-3-ticket-3-6637

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-3-up-additional-email-update-integration-6638.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ent-part-3-up-additional-email-update-integration-6638.tf
```<ul>✔️Valid Redirect Urls<li>http://testchange.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testchange.com</li></ul>```
</details>
=> request: add client files for ent-part-3-up-additional-email-update-integration-6638

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-2-user-notification-for-b-ce-id-6607.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ent-part-2-user-notification-for-b-ce-id-6607.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-2-user-notification-for-b-ce-id-6607

terraform/keycloak-dev/realms/onestopauth/client-tians-bug-fixing-on-team-deletion-6641.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-bug-fixing-on-team-deletion-6641

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-2-team-notification-for-b-ce-id-6608.tf, terraform/keycloak-test/realms/onestopauth-basic/client-ent-part-2-team-notification-for-b-ce-id-6608.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-2-team-notification-for-b-ce-id-6608

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-3-ticket-4-6643.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-3-ticket-4-6643

terraform/keycloak-dev/realms/onestopauth-basic/client-ent-part-3-ticket-4-6644.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for ent-part-3-ticket-4-6644

terraform/keycloak-dev/realms/onestopauth-basic/client-march-10-test-2-zorin-6613.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-march-10-test-2-zorin-6613.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
=> request: update client files for march-10-test-2-zorin-6613

terraform/keycloak-dev/realms/onestopauth/client-junminlocaltest-6667.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junminlocaltest-6667

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-idir-only-6733.tf, terraform/keycloak-prod/realms/onestopauth/client-tians-testing-idir-only-6733.tf, terraform/keycloak-test/realms/onestopauth/client-tians-testing-idir-only-6733.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampletest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleprod</li></ul>```
</details>
=> request: add client files for tians-testing-idir-only-6733

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-non-prod-b-ce-id-6734.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-non-prod-b-ce-id-6734.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampletest</li></ul>```
</details>
=> request: add client files for tians-testing-non-prod-b-ce-id-6734

terraform/keycloak-dev/realms/onestopauth-business/client-tians-testing-b-ce-id-add-prod-later-6736.tf, terraform/keycloak-test/realms/onestopauth-business/client-tians-testing-b-ce-id-add-prod-later-6736.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampletest</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-add-prod-later-6736

terraform/keycloak-dev/realms/onestopauth/client-integration-a-6737.tf
```<ul>✔️Valid Redirect Urls<li>http://example.ccaa</li></ul>```
</details>
=> request: add client files for integration-a-6737

terraform/keycloak-dev/realms/onestopauth/client-march-15-zorin-test-1-6766.tf
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/devChanged</li></ul>```
</details>
=> request: add client files for march-15-zorin-test-1-6766

terraform/keycloak-dev/realms/onestopauth-basic/client-march-10-test-2-zorin-6613.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-march-10-test-2-zorin-6613.tf
=> request: delete client files for march-10-test-2-zorin-6613

terraform/keycloak-dev/realms/onestopauth/client-junminlocaltest-6667.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: update client files for junminlocaltest-6667

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-b-ce-id-list-members-6800.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-b-ce-id-list-members-6800.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampletest</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-list-members-6800

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-list-members-multiple-emails-6801.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-list-members-multiple-emails-6801.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-list-members-multiple-emails-6801

terraform/keycloak-dev/realms/onestopauth/client-junmintestintegration-6866.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmintestintegration-6866

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-with-new-team-6867.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-with-new-team-6867

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-multiple-members-3-8-6403.tf
=> request: delete client files for tians-testing-multiple-members-3-8-6403

terraform/keycloak-dev/realms/onestopauth/client-junmintestintegration-11-6866.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmintestintegration-11-6866

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-6964.tf, terraform/keycloak-test/realms/onestopauth/client-jaffer-first-test-6964.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-6964

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-basic-6966.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-basic-6966

terraform/keycloak-dev/realms/onestopauth/client-junmin-test-6970.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-test-6970

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-test-environment-download-6997.tf, terraform/keycloak-prod/realms/onestopauth/client-tians-testing-test-environment-download-6997.tf, terraform/keycloak-test/realms/onestopauth/client-tians-testing-test-environment-download-6997.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for tians-testing-test-environment-download-6997

terraform/keycloak-dev/realms/onestopauth-business/client-jaffer-first-test-mar-24-mor-6969.tf, terraform/keycloak-test/realms/onestopauth-business/client-jaffer-first-test-mar-24-mor-6969.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-mar-24-mor-6969

terraform/keycloak-dev/realms/onestopauth-both/client-jaffer-first-test-mar-24-mor-1-6998.tf, terraform/keycloak-test/realms/onestopauth-both/client-jaffer-first-test-mar-24-mor-1-6998.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-mar-24-mor-1-6998

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-mar-24-aft-6999.tf, terraform/keycloak-prod/realms/onestopauth/client-jaffer-first-test-mar-24-aft-6999.tf, terraform/keycloak-test/realms/onestopauth/client-jaffer-first-test-mar-24-aft-6999.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-mar-24-aft-6999

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-new-mar-24-7000.tf, terraform/keycloak-prod/realms/onestopauth/client-jaffer-first-test-new-mar-24-7000.tf, terraform/keycloak-test/realms/onestopauth/client-jaffer-first-test-new-mar-24-7000.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-new-mar-24-7000

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-mar-24-aft-12-7030.tf, terraform/keycloak-test/realms/onestopauth/client-jaffer-first-test-mar-24-aft-12-7030.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-mar-24-aft-12-7030

terraform/keycloak-dev/realms/onestopauth-business/client-jaffer-first-test-mar-24-aft-12-1-7031.tf, terraform/keycloak-test/realms/onestopauth-business/client-jaffer-first-test-mar-24-aft-12-1-7031.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-mar-24-aft-12-1-7031

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-mar-24-aft-12-7030.tf, terraform/keycloak-prod/realms/onestopauth/client-jaffer-first-test-mar-24-aft-12-7030.tf, terraform/keycloak-test/realms/onestopauth/client-jaffer-first-test-mar-24-aft-12-7030.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: update client files for jaffer-first-test-mar-24-aft-12-7030

terraform/keycloak-dev/realms/onestopauth/client-march-28-zorin-test-terraformflow-7096.tf, terraform/keycloak-prod/realms/onestopauth/client-march-28-zorin-test-terraformflow-7096.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/dev1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/prod1</li></ul>```
</details>
=> request: add client files for march-28-zorin-test-terraformflow-7096

terraform/keycloak-dev/realms/onestopauth/client-march-28-test-2-zorin-7097.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
=> request: add client files for march-28-test-2-zorin-7097

terraform-v2/keycloak-dev/standard-clients/junmin-local-gold-2-7134.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-local-gold-2-7134

terraform-v2/keycloak-dev/standard-clients/kuro-testing-1-7164.tf
```<ul>✔️Valid Redirect Urls<li>http://devchange.com</li></ul>```
</details>
=> request: add client files for kuro-testing-1-7164

terraform-v2/keycloak-dev/standard-clients/kuro-testing-2-7170.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-2-7170.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-2-7170

terraform-v2/keycloak-dev/standard-clients/kuro-testing-1-7171.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-1-7171

terraform-v2/keycloak-dev/standard-clients/kuro-testing-3-7172.tf, terraform-v2/keycloak-prod/standard-clients/kuro-testing-3-7172.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-3-7172

terraform-v2/keycloak-dev/standard-clients/kuro-testing-1-update-7171.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-1-update-7171.tf
```<ul>✔️Valid Redirect Urls<li>http://testupdate.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testupdate.com</li></ul>```
</details>
=> request: add client files for kuro-testing-1-update-7171

terraform-v2/keycloak-dev/standard-clients/kuro-testing-4-7195.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-4-7195

terraform-v2/keycloak-dev/standard-clients/kuro-testing-4-update-7195.tf, terraform-v2/keycloak-prod/standard-clients/kuro-testing-4-update-7195.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-4-update-7195

terraform-v2/keycloak-dev/standard-clients/tians-test-1st-gold-7162.tf, terraform-v2/keycloak-prod/standard-clients/tians-test-1st-gold-7162.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-test-1st-gold-7162

terraform-v2/keycloak-dev/standard-clients/tians-test-2nd-gold-7196.tf, terraform-v2/keycloak-prod/standard-clients/tians-test-2nd-gold-7196.tf, terraform-v2/keycloak-test/standard-clients/tians-test-2nd-gold-7196.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd1</li>,<li>https://exampleddd2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li>,<li>https://exampleProd2</li>,<li>https://exampleProd3</li></ul>```
</details>
=> request: add client files for tians-test-2nd-gold-7196

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-1st-silver-7197.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-tians-testing-1st-silver-7197.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-1st-silver-7197.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-1st-silver-7197

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-silver-1st-7198.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-tians-testing-silver-1st-7198.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-silver-1st-7198.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-silver-1st-7198

terraform-v2/keycloak-dev/standard-clients/kuro-testing-4-7199.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-4-7199.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-4-7199

terraform-v2/keycloak-dev/standard-clients/kuro-testing-5-7200.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-5-7200

terraform/keycloak-dev/realms/onestopauth/client-test-project-7201.tf, terraform/keycloak-test/realms/onestopauth/client-test-project-7201.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for test-project-7201

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-multiple-members-7203.tf, terraform/keycloak-test/realms/onestopauth/client-tians-testing-multiple-members-7203.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-multiple-members-7203

terraform-v2/keycloak-dev/standard-clients/junmin-gold-test-7168.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-gold-test-7168

terraform/keycloak-dev/realms/onestopauth/client-junmin-test-329-7131.tf, terraform/keycloak-prod/realms/onestopauth/client-junmin-test-329-7131.tf, terraform/keycloak-test/realms/onestopauth/client-junmin-test-329-7131.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost3030</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost3030</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost3030</li></ul>```
</details>
=> request: add client files for junmin-test-329-7131

terraform/keycloak-dev/realms/onestopauth/client-april-6-z-test-teams-7098.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
=> request: add client files for april-6-z-test-teams-7098

terraform-v2/keycloak-dev/standard-clients/april-6-testing-teams-2-7204.tf
```<ul>✔️Valid Redirect Urls<li>localhost://dev</li></ul>```
</details>
=> request: add client files for april-6-testing-teams-2-7204

terraform/keycloak-dev/realms/onestopauth/client-fasdfasdf-7202.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for fasdfasdf-7202

terraform-v2/keycloak-dev/standard-clients/junmin-gold-test-7167.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-gold-test-7167

terraform/keycloak-dev/realms/onestopauth/client-jaffer-test-apr-08-7236.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for jaffer-test-apr-08-7236

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-9-7261.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-9-7261

terraform/keycloak-dev/realms/onestopauth/client-jaffer-first-test-9-7262.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-9-7262

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7277.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7277

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7278.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7278

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7279.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7279

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7280.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7280

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7281.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7281

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7283.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7283

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7285.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7285

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7286.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7286

terraform/keycloak-dev/realms/onestopauth/client-zz-7284.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-7284

terraform-v2/keycloak-dev/standard-clients/tians-testing-third-gold-7327.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-third-gold-7327.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-third-gold-7327.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li>,<li>https://example1</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://prod1.com</li></ul>```
</details>
=> request: add client files for tians-testing-third-gold-7327

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7328.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7328

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7329.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7329

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7330.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7330

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7333.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7333

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7334.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7334

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7336.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7336

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7337.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7337

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7339.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7339

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7340.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7340

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7341.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7341

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7342.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7342

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7343.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7343

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7344.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7344

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7345.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7345

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7346.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7346

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7347.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7347

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7348.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7348

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7349.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7349

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7350.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7350

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7352.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7352

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-08-7354.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-08-7354

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7356.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7356

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7357.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7357

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7358.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7358

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7359.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7359

terraform/keycloak-dev/realms/onestopauth-business/client-tians-testing-b-ce-id-7360.tf, terraform/keycloak-test/realms/onestopauth-business/client-tians-testing-b-ce-id-7360.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-7360

terraform-v2/keycloak-dev/standard-clients/junmin-gold-testss-7168.tf, terraform-v2/keycloak-test/standard-clients/junmin-gold-testss-7168.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3003</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-gold-testss-7168

terraform-v2/keycloak-dev/standard-clients/tian-first-gold-7361.tf, terraform-v2/keycloak-prod/standard-clients/tian-first-gold-7361.tf, terraform-v2/keycloak-test/standard-clients/tian-first-gold-7361.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://prod1.com</li></ul>```
</details>
=> request: add client files for tian-first-gold-7361

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7364.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7364

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7365.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7365

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7366.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7366

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7367.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7367

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7368.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7368

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7369.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7369

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-in-silver-7372.tf, terraform/keycloak-test/realms/onestopauth/client-tians-testing-silver-in-silver-7372.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-silver-in-silver-7372

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-in-silver-7372.tf, terraform/keycloak-test/realms/onestopauth/client-tians-testing-silver-in-silver-7372.tf
```<ul>✔️Valid Redirect Urls<li>https://exampledev</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: update client files for tians-testing-silver-in-silver-7372

terraform-v2/keycloak-dev/standard-clients/tians-testing-7371.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-7371.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-7371

terraform-v2/keycloak-dev/standard-clients/junmin-test-integration-7375.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3999</li></ul>```
</details>
=> request: add client files for junmin-test-integration-7375

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7377.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7377

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7378.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7378

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7379.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7379

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-silver-in-silver-2-7380.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-tians-testing-silver-in-silver-2-7380.tf, terraform/keycloak-test/realms/onestopauth-basic/client-tians-testing-silver-in-silver-2-7380.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-silver-in-silver-2-7380

terraform-v2/keycloak-dev/standard-clients/april-25-test-all-environments-7381.tf, terraform-v2/keycloak-prod/standard-clients/april-25-test-all-environments-7381.tf, terraform-v2/keycloak-test/standard-clients/april-25-test-all-environments-7381.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/prod2</li></ul>```
</details>
=> request: add client files for april-25-test-all-environments-7381

terraform-v2/keycloak-dev/standard-clients/april-25-test-b-ce-id-all-environments-7382.tf, terraform-v2/keycloak-prod/standard-clients/april-25-test-b-ce-id-all-environments-7382.tf, terraform-v2/keycloak-test/standard-clients/april-25-test-b-ce-id-all-environments-7382.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/test2</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/prod2</li></ul>```
</details>
=> request: add client files for april-25-test-b-ce-id-all-environments-7382

terraform-v2/keycloak-dev/standard-clients/april-25-b-ce-id-non-prod-7383.tf, terraform-v2/keycloak-test/standard-clients/april-25-b-ce-id-non-prod-7383.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.test.ca/testCHANGED</li></ul>```
</details>
=> request: add client files for april-25-b-ce-id-non-prod-7383

terraform-v2/keycloak-dev/standard-clients/tians-testing-third-gold-7373.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-third-gold-7373

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-in-silver-3-7384.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-silver-in-silver-3-7384

terraform/keycloak-dev/realms/onestopauth-basic/client-tians-testing-silver-in-silver-4-7385.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-silver-in-silver-4-7385

terraform-v2/keycloak-dev/standard-clients/test-april-25-draft-project-7387.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
=> request: add client files for test-april-25-draft-project-7387

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7389.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7389

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7390.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7390

terraform-v2/keycloak-dev/standard-clients/test-7388.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
=> request: add client files for test-7388

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7392.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7392

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7394.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7394

terraform/keycloak-dev/realms/onestopauth-both/client-april-28-silver-b-ce-id-both-7395.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for april-28-silver-b-ce-id-both-7395

terraform/keycloak-dev/realms/onestopauth-business/client-march-2-b-ce-id-all-prod-6044.tf, terraform/keycloak-prod/realms/onestopauth-business/client-march-2-b-ce-id-all-prod-6044.tf, terraform/keycloak-test/realms/onestopauth-business/client-march-2-b-ce-id-all-prod-6044.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: update client files for march-2-b-ce-id-all-prod-6044

terraform/keycloak-dev/realms/onestopauth-basic/client-march-2-b-ce-id-non-prod-to-prod-6043.tf, terraform/keycloak-prod/realms/onestopauth-basic/client-march-2-b-ce-id-non-prod-to-prod-6043.tf, terraform/keycloak-test/realms/onestopauth-basic/client-march-2-b-ce-id-non-prod-to-prod-6043.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange123</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange8888</li></ul>```
</details>
=> request: update client files for march-2-b-ce-id-non-prod-to-prod-6043

terraform/keycloak-dev/realms/onestopauth-basic/client-april-28-silver-idir-b-ce-id-basic-7396.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for april-28-silver-idir-b-ce-id-basic-7396

terraform/keycloak-dev/realms/onestopauth-basic/client-april-18-silver-b-ce-id-basic-7397.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li></ul>```
</details>
=> request: add client files for april-18-silver-b-ce-id-basic-7397

terraform-v2/keycloak-dev/standard-clients/roles-testing-april-29-7398.tf, terraform-v2/keycloak-prod/standard-clients/roles-testing-april-29-7398.tf, terraform-v2/keycloak-test/standard-clients/roles-testing-april-29-7398.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for roles-testing-april-29-7398

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-1-7426.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-1-7426.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-gold-1-7426.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-gold-1-7426

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7429.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7429

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7430.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7430

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7431.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7431

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7432.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7432

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7433.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7433

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-2-7434.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-gold-2-7434.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-gold-2-7434

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7435.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7435

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7436.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7436

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7437.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7437

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-2-7438.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-2-7438.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-gold-2-7438

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7439.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7439

terraform/keycloak-dev/realms/onestopauth-both/client-kuro-testing-7440.tf, terraform/keycloak-test/realms/onestopauth-both/client-kuro-testing-7440.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testchange.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7440

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-1-7442.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-silver-1-7442

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7445.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7445

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7446.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7446

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7459.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7459

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7460.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7460

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7461.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7461

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7462.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7462

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7463.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7463

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7464.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7464

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7465.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7465

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7466.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7466

terraform-v2/keycloak-dev/standard-clients/may-11-test-zorin-7467.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for may-11-test-zorin-7467

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-may-12-7469.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-may-12-7469

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7470.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7470

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-apr-17-7471.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-apr-17-7471

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-7472.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-7472

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-7473.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-7473

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-7474.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-7474

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-7475.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-7475

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7477.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7477

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7482.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7482

terraform-v2/keycloak-dev/standard-clients/jaffer-first-test-9-7492.tf, terraform-v2/keycloak-prod/standard-clients/jaffer-first-test-9-7492.tf, terraform-v2/keycloak-test/standard-clients/jaffer-first-test-9-7492.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-9-7492

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7500.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7500.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7500.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7500

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7513.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7513

terraform-v2/keycloak-dev/standard-clients/may-19-zorin-test-idir-only-7468.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for may-19-zorin-test-idir-only-7468

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7514.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7514

terraform-v2/keycloak-dev/standard-clients/kuro-testing-7515.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-7515.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testchange.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7515

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-in-silver-7516.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-silver-in-silver-7516

terraform/keycloak-dev/realms/onestopauth/client-json-test-20-7517.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for json-test-20-7517

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7518.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7518

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-may-20-7519.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-may-20-7519

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-3-7520.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-3-7520.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-gold-3-7520

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-4-7521.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-gold-4-7521

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-4-7522.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-4-7522.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-gold-4-7522.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-gold-4-7522

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-2-7523.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-2-7523.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-gold-2-7523.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-gold-2-7523

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-3-7524.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-gold-3-7524

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-5-7525.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-gold-5-7525.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-gold-5-7525

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7526.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7526.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7526.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7526

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7527.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7527

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7530.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7530.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7530.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7530

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7531.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7531.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7531.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7531

terraform-v2/keycloak-dev/standard-clients/may-23-zorin-test-7529.tf, terraform-v2/keycloak-test/standard-clients/may-23-zorin-test-7529.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for may-23-zorin-test-7529

terraform-v2/keycloak-dev/standard-clients/kuro-testing-7428.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-7428.tf
```<ul>✔️Valid Redirect Urls<li>http://test2.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testchange.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7428

terraform-v2/keycloak-dev/standard-clients/b-ceid-basic-test-non-prod-no-teams-7533.tf, terraform-v2/keycloak-test/standard-clients/b-ceid-basic-test-non-prod-no-teams-7533.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for b-ceid-basic-test-non-prod-no-teams-7533

terraform-v2/keycloak-dev/standard-clients/kuro-testing-7535.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7535

terraform-v2/keycloak-dev/standard-clients/kuro-testing-7536.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7536

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-1-7537.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-1-7537.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-gold-1-7537.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-gold-1-7537

terraform-v2/keycloak-dev/standard-clients/jaffer-first-test-may-30-7538.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-may-30-7538

terraform-v2/keycloak-dev/standard-clients/zz-7534.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for zz-7534

terraform-v2/keycloak-dev/standard-clients/may-23-zorin-test-7528.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for may-23-zorin-test-7528

terraform-v2/keycloak-dev/standard-clients/may-25-7532.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for may-25-7532

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1-18.tf
=> request: add client files for service-account-team-1-18

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7540.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7540.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7540.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7540

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1519-7558.tf
=> request: add client files for service-account-team-1519-7558

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1553-7559.tf
=> request: add client files for service-account-team-1553-7559

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-31-7562.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-31-7562.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-31-7562

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-31-7565.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-31-7565.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-b-ceid-basic-31-7565

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7591.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7591.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7591.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7591

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7632.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7632.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7632.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7632

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7633.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7633.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7633.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7633

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7634.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7634.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7634.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7634

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7636.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7636

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7638.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7638.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7638.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7638

terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-4-7640.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-gold-4-7640

terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-in-silver-7641.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-silver-in-silver-7641

terraform-v2/keycloak-dev/standard-clients/jaffer-first-test-new-7642.tf, terraform-v2/keycloak-test/standard-clients/jaffer-first-test-new-7642.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-new-7642

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7643.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7643

terraform-v2/keycloak-dev/standard-clients/new-test-b-ceid-may-30-7644.tf, terraform-v2/keycloak-test/standard-clients/new-test-b-ceid-may-30-7644.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for new-test-b-ceid-may-30-7644

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7645.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7645.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7645.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7645

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7646.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7646.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7646.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7646

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7647.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7647.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-b-ceid-basic-02-7647

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7648.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7648

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7649.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7649

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7650.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7650

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7651.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7651.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7651.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7651

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7652.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7652.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7652.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7652

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7653.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7653.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-b-ceid-basic-02-7653

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7654.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7654.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7654.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7654

terraform-v2/keycloak-dev/standard-clients/jaffer-first-test-9-7655.tf, terraform-v2/keycloak-test/standard-clients/jaffer-first-test-9-7655.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:8000</li></ul>```
</details>
=> request: add client files for jaffer-first-test-9-7655

terraform-v2/keycloak-dev/standard-clients/kuro-testing-7656.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-7656.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://testchange.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7656

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7657.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7657

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7658.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7658.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7658.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7658

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7659.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7659.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7659.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7659

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7660.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7660.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-b-ceid-basic-02-7660

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7661.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7661.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7661.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7661

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7662.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7662.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7662.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7662

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7663.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7663.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7663.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7663

terraform/keycloak-dev/realms/onestopauth/client-css-happy-path-end-2-end-final-1-7664.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-final-1-7664

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7665.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7665.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7665.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7665

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7666.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7666.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7666.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7666

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7667.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-b-ceid-basic-02-7667.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-b-ceid-basic-02-7667

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7668.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7668.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7668.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7668

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7669.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7669.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7669.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7669

terraform-v2/keycloak-dev/standard-clients/css-happy-path-end-2-end-gold-7670.tf, terraform-v2/keycloak-prod/standard-clients/css-happy-path-end-2-end-gold-7670.tf, terraform-v2/keycloak-test/standard-clients/css-happy-path-end-2-end-gold-7670.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://localhost:3000</li></ul>```
</details>
=> request: add client files for css-happy-path-end-2-end-gold-7670

terraform-v2/keycloak-dev/standard-clients/demo-request-7672.tf
```<ul>✔️Valid Redirect Urls<li>http://*/*</li></ul>```
</details>
=> request: add client files for demo-request-7672

terraform-v2/keycloak-dev/standard-clients/tian-1-testing-7674.tf, terraform-v2/keycloak-test/standard-clients/tian-1-testing-7674.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tian-1-testing-7674

terraform/keycloak-dev/realms/onestopauth/client-tian-1-testing-silver-7675.tf, terraform/keycloak-prod/realms/onestopauth/client-tian-1-testing-silver-7675.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tian-1-testing-silver-7675

terraform-v2/keycloak-dev/standard-clients/test-7692.tf, terraform-v2/keycloak-prod/standard-clients/test-7692.tf, terraform-v2/keycloak-test/standard-clients/test-7692.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
=> request: add client files for test-7692

terraform-v2/keycloak-dev/standard-clients/may-30-test-demo-7539.tf, terraform-v2/keycloak-prod/standard-clients/may-30-test-demo-7539.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:10004</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for may-30-test-demo-7539

terraform-v2/keycloak-dev/standard-clients/june-20-test-non-prod-to-prod-7693.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
=> request: add client files for june-20-test-non-prod-to-prod-7693

terraform-v2/keycloak-dev/standard-clients/june-23-test-all-prod-7697.tf, terraform-v2/keycloak-prod/standard-clients/june-23-test-all-prod-7697.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for june-23-test-all-prod-7697

terraform-v2/keycloak-dev/standard-clients/june-23-test-edit-non-prod-to-prod-7698.tf, terraform-v2/keycloak-test/standard-clients/june-23-test-edit-non-prod-to-prod-7698.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for june-23-test-edit-non-prod-to-prod-7698

terraform-v2/keycloak-dev/standard-clients/confidential-client-june-23-7700.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for confidential-client-june-23-7700

terraform-v2/keycloak-dev/standard-clients/tians-testing-confidential-7701.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-confidential-7701.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-confidential-7701

terraform-v2/keycloak-dev/standard-clients/kuro-testing-35.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-35

terraform-v2/keycloak-dev/standard-clients/tians-testing-terraform-status-7703.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-terraform-status-7703

terraform-v2/keycloak-dev/standard-clients/kuro-testing-7727.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-7727.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-7727

terraform-v2/keycloak-dev/standard-clients/abhinav-integration-test-7756.tf, terraform-v2/keycloak-test/standard-clients/abhinav-integration-test-7756.tf
```<ul>✔️Valid Redirect Urls<li>https://testingAbhinav.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://Abhinav_testing.com</li></ul>```
</details>
=> request: add client files for abhinav-integration-test-7756

terraform-v2/keycloak-dev/standard-clients/junmin-new-integration-7511.tf, terraform-v2/keycloak-prod/standard-clients/junmin-new-integration-7511.tf, terraform-v2/keycloak-test/standard-clients/junmin-new-integration-7511.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
=> request: add client files for junmin-new-integration-7511

terraform-v2/keycloak-dev/standard-clients/junmin-service-account-7789.tf
```<ul>✔️Valid Redirect Urls<li>http</li></ul>```
</details>
=> request: add client files for junmin-service-account-7789

terraform-v2/keycloak-dev/standard-clients/tians-testing-confidential-standard-flow-7793.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
=> request: add client files for tians-testing-confidential-standard-flow-7793

terraform-v2/keycloak-dev/standard-clients/tians-testing-confidential-service-account-7792.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-confidential-service-account-7792.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for tians-testing-confidential-service-account-7792

terraform-v2/keycloak-dev/standard-clients/tians-testing-confidential-both-7794.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-confidential-both-7794

terraform-v2/keycloak-dev/standard-clients/july-11-test-7726.tf, terraform-v2/keycloak-test/standard-clients/july-11-test-7726.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for july-11-test-7726

terraform-v2/keycloak-dev/standard-clients/july-12-service-accoutn-test-7798.tf, terraform-v2/keycloak-test/standard-clients/july-12-service-accoutn-test-7798.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
=> request: add client files for july-12-service-accoutn-test-7798

terraform-v2/keycloak-dev/standard-clients/july-15-composite-roles-test-7799.tf, terraform-v2/keycloak-test/standard-clients/july-15-composite-roles-test-7799.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for july-15-composite-roles-test-7799

terraform/keycloak-dev/realms/onestopauth/client-confidential-example-app-integration-7801.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for confidential-example-app-integration-7801

terraform-v2/keycloak-dev/standard-clients/gold-sso-7804.tf, terraform-v2/keycloak-test/standard-clients/gold-sso-7804.tf
```<ul>✔️Valid Redirect Urls<li>https://www.goldsso.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.goldssotest.com</li></ul>```
</details>
=> request: add client files for gold-sso-7804

terraform-v2/keycloak-dev/standard-clients/kuro-testing-ui-7805.tf, terraform-v2/keycloak-test/standard-clients/kuro-testing-ui-7805.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
=> request: add client files for kuro-testing-ui-7805

terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-prod-7808.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-prod-7808.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-prod-7808

terraform-v2/keycloak-dev/standard-clients/tians-testing-idir-and-b-ce-id-prod-7810.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-idir-and-b-ce-id-prod-7810.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-idir-and-b-ce-id-prod-7810.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-idir-and-b-ce-id-prod-7810

terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-idir-with-prod-7809.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-idir-with-prod-7809.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-b-ce-id-idir-with-prod-7809.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-idir-with-prod-7809

terraform-v2/keycloak-dev/standard-clients/junmin-test-7795.tf, terraform-v2/keycloak-prod/standard-clients/junmin-test-7795.tf, terraform-v2/keycloak-test/standard-clients/junmin-test-7795.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-test-7795

terraform-v2/keycloak-dev/standard-clients/tians-testing-idir-and-b-ce-id-prod-later-7812.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-idir-and-b-ce-id-prod-later-7812.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-idir-and-b-ce-id-prod-later-7812.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-idir-and-b-ce-id-prod-later-7812

terraform-v2/keycloak-dev/standard-clients/mynewproject-7362.tf, terraform-v2/keycloak-prod/standard-clients/mynewproject-7362.tf, terraform-v2/keycloak-test/standard-clients/mynewproject-7362.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for mynewproject-7362

terraform-v2/keycloak-dev/standard-clients/tians-testing-idir-and-b-ce-id-prod-later-7818.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-idir-and-b-ce-id-prod-later-7818.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
=> request: add client files for tians-testing-idir-and-b-ce-id-prod-later-7818

terraform-v2/keycloak-dev/standard-clients/junmin-test-gold-bceid-7819.tf, terraform-v2/keycloak-prod/standard-clients/junmin-test-gold-bceid-7819.tf, terraform-v2/keycloak-test/standard-clients/junmin-test-gold-bceid-7819.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-test-gold-bceid-7819

terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-prod-approval-7820.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-prod-approval-7820.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-prod-approval-7820

terraform-v2/keycloak-dev/standard-clients/junmin-integration-7821.tf, terraform-v2/keycloak-prod/standard-clients/junmin-integration-7821.tf, terraform-v2/keycloak-test/standard-clients/junmin-integration-7821.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
=> request: add client files for junmin-integration-7821

terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-prod-approval-7823.tf, terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-prod-approval-7823.tf, terraform-v2/keycloak-test/standard-clients/tians-testing-b-ce-id-prod-approval-7823.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
=> request: add client files for tians-testing-b-ce-id-prod-approval-7823

terraform-v2/keycloak-dev/standard-clients/tians-testing-demo-7-21-7822.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
=> request: add client files for tians-testing-demo-7-21-7822

terraform-v2/keycloak-dev/standard-clients/july-20-workflow-test-b-cei-d-nonprod-to-prod-7824.tf, terraform-v2/keycloak-test/standard-clients/july-20-workflow-test-b-cei-d-nonprod-to-prod-7824.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
=> request: add client files for july-20-workflow-test-b-cei-d-nonprod-to-prod-7824
