bcgov/sso-terraform-dev

- terraform-v2/keycloak-dev/standard-clients/july-20-workflow-test-prod-b-ce-id-idir-7825.tf
- terraform-v2/keycloak-prod/standard-clients/july-20-workflow-test-prod-b-ce-id-idir-7825.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for july-20-workflow-test-prod-b-ce-id-idir-7825

- terraform-v2/keycloak-dev/standard-clients/july-20-workflow-test-non-prod-b-ce-id-idir-7826.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for july-20-workflow-test-non-prod-b-ce-id-idir-7826

- terraform-v2/keycloak-dev/standard-clients/july-21-b-ce-id-test-for-abhinav-7827.tf
- terraform-v2/keycloak-prod/standard-clients/july-21-b-ce-id-test-for-abhinav-7827.tf
- terraform-v2/keycloak-test/standard-clients/july-21-b-ce-id-test-for-abhinav-7827.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for july-21-b-ce-id-test-for-abhinav-7827

- terraform-v2/keycloak-dev/standard-clients/tians-another-test-7831.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-another-test-7831

- terraform-v2/keycloak-dev/standard-clients/abhinav-test-7811.tf
- terraform-v2/keycloak-prod/standard-clients/abhinav-test-7811.tf
- terraform-v2/keycloak-test/standard-clients/abhinav-test-7811.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ABCtesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ABCtesting.com</li></ul>```
</details>
> request: add client files for abhinav-test-7811

- terraform-v2/keycloak-dev/standard-clients/tians-testing-heading-test-7856.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-heading-test-7856.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-heading-test-7856.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-heading-test-7856

- terraform-v2/keycloak-dev/standard-clients/tians-testing-redirect-url-7858.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-redirect-url-7858.tf
```<ul>✔️Valid Redirect Urls<li>a.://1</li>,<li>c://3</li>,<li>secure-image://client</li></ul>```
```<ul>✔️Valid Redirect Urls<li>a.://1</li></ul>```
</details>
> request: add client files for tians-testing-redirect-url-7858

- terraform-v2/keycloak-dev/standard-clients/test-1-7855.tf
- terraform-v2/keycloak-test/standard-clients/test-1-7855.tf
```<ul>✔️Valid Redirect Urls<li>abhinav-sharma://dotdot</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://Abhinav_testing1.com</li></ul>```
</details>
> request: add client files for test-1-7855

- terraform-v2/keycloak-dev/standard-clients/abcd-1-test-7859.tf
- terraform-v2/keycloak-test/standard-clients/abcd-1-test-7859.tf
```<ul>✔️Valid Redirect Urls<li>https://ABCD1devtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://ABCD1test.com</li></ul>```
</details>
> request: add client files for abcd-1-test-7859

- terraform-v2/keycloak-dev/standard-clients/tians-another-test-bceid-7860.tf
- terraform-v2/keycloak-prod/standard-clients/tians-another-test-bceid-7860.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-another-test-bceid-7860

- terraform-v2/keycloak-dev/standard-clients/tians-testing-idim-7861.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-idim-7861

- terraform-v2/keycloak-dev/standard-clients/test-nk-svc-acct-47.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-svc-acct-47

- terraform/keycloak-dev/realms/onestopauth-basic/client-test-nk-project-7862.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-project-7862

- terraform-v2/keycloak-dev/standard-clients/sso-test-7864.tf
- terraform-v2/keycloak-test/standard-clients/sso-test-7864.tf
```<ul>✔️Valid Redirect Urls<li>https://cssdevtesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://csstesting.com</li></ul>```
</details>
> request: add client files for sso-test-7864

- terraform/keycloak-dev/realms/onestopauth-basic/client-test-nk-project-7865.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-project-7865

- terraform-v2/keycloak-dev/standard-clients/aug-3-demo-css-api-7868.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for aug-3-demo-css-api-7868

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1857-7869.tf
> request: add client files for service-account-team-1857-7869

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7870.tf
> request: add client files for service-account-team-1858-7870

- terraform-v2/keycloak-dev/standard-clients/test-nk-integration-7871.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-integration-7871

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1854-7872.tf
> request: add client files for service-account-team-1854-7872

- terraform-v2/keycloak-dev/standard-clients/test-nk-project-7873.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-project-7873

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1854-7874.tf
> request: add client files for service-account-team-1854-7874

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-134-7876.tf
> request: add client files for service-account-team-134-7876

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-134-7875.tf
> request: add client files for service-account-team-134-7875

- terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-20220804-7877.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-silver-20220804-7877

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1859-7878.tf
> request: add client files for service-account-team-1859-7878

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1553-7879.tf
> request: add client files for service-account-team-1553-7879

- terraform-v2/keycloak-dev/standard-clients/abhinav-testing-serviceaccount-7881.tf
- terraform-v2/keycloak-test/standard-clients/abhinav-testing-serviceaccount-7881.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for abhinav-testing-serviceaccount-7881

- terraform-v2/keycloak-dev/standard-clients/tians-testing-delete-client-7882.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-delete-client-7882.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-delete-client-7882.tf
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-delete-client-7882

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1857-7869.tf
> request: delete client files for service-account-team-1857-7869

- terraform-v2/keycloak-dev/standard-clients/aug-8-css-api-account-7884.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for aug-8-css-api-account-7884

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1857-7885.tf
> request: add client files for service-account-team-1857-7885

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1857-7885.tf
> request: delete client files for service-account-team-1857-7885

- terraform-v2/keycloak-dev/standard-clients/augh-8-lada-and-zorin-7886.tf
```<ul>✔️Valid Redirect Urls<li>https:///www.test.ca/devChange2</li></ul>```
</details>
> request: add client files for augh-8-lada-and-zorin-7886

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-463-7887.tf
> request: add client files for service-account-team-463-7887

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1854-7889.tf
> request: add client files for service-account-team-1854-7889

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1854-7889.tf
> request: delete client files for service-account-team-1854-7889

- terraform-v2/keycloak-dev/standard-clients/test-nk-int-7890.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-int-7890

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1862-7891.tf
> request: add client files for service-account-team-1862-7891

- terraform-v2/keycloak-dev/standard-clients/kuro-bceid-email-testing-7892.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-bceid-email-testing-7892

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-bceid-email-7893.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-testing-bceid-email-7893

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-idp-email-testing-7894.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-testing-idp-email-testing-7894

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1862-7891.tf
> request: delete client files for service-account-team-1862-7891

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1849-7895.tf
> request: add client files for service-account-team-1849-7895

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-7896.tf
> request: add client files for service-account-team-1861-7896

- terraform/keycloak-dev/realms/onestopauth-both/client-silver-idp-test-7898.tf
- terraform/keycloak-test/realms/onestopauth-both/client-silver-idp-test-7898.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for silver-idp-test-7898

- terraform-v2/keycloak-dev/standard-clients/diff-idp-testing-7899.tf
- terraform-v2/keycloak-test/standard-clients/diff-idp-testing-7899.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for diff-idp-testing-7899

- terraform/keycloak-dev/realms/onestopauth-basic/client-diff-idp-testing-create-in-silver-7900.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for diff-idp-testing-create-in-silver-7900

- terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-both-search-7901.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-b-ce-id-both-search-7901

- terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-basic-business-search-7902.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-b-ce-id-basic-business-search-7902

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7903.tf
> request: add client files for service-account-team-1858-7903

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1553-7879.tf
> request: delete client files for service-account-team-1553-7879

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1863-7904.tf
> request: add client files for service-account-team-1863-7904

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1863-7904.tf
> request: delete client files for service-account-team-1863-7904

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7905.tf
> request: add client files for service-account-team-1864-7905

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1852-7906.tf
> request: add client files for service-account-team-1852-7906

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7905.tf
> request: delete client files for service-account-team-1864-7905

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7907.tf
> request: add client files for service-account-team-1864-7907

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7907.tf
> request: delete client files for service-account-team-1864-7907

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7908.tf
> request: add client files for service-account-team-1864-7908

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7908.tf
> request: delete client files for service-account-team-1864-7908

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7909.tf
> request: add client files for service-account-team-1864-7909

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1864-7909.tf
> request: delete client files for service-account-team-1864-7909

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1487-7910.tf
> request: add client files for service-account-team-1487-7910

- terraform/keycloak-dev/realms/onestopauth-basic/client-idp-testing-silver-7911.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for idp-testing-silver-7911

- terraform/keycloak-dev/realms/onestopauth-both/client-idp-testing-7912.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for idp-testing-7912

- terraform-v2/keycloak-dev/standard-clients/idp-testing-gold-7913.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for idp-testing-gold-7913

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1487-7910.tf
> request: delete client files for service-account-team-1487-7910

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7903.tf
> request: delete client files for service-account-team-1858-7903

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1859-7878.tf
> request: delete client files for service-account-team-1859-7878

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1859-7914.tf
> request: add client files for service-account-team-1859-7914

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7915.tf
> request: add client files for service-account-team-1858-7915

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7915.tf
> request: delete client files for service-account-team-1858-7915

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7916.tf
> request: add client files for service-account-team-1858-7916

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7916.tf
> request: delete client files for service-account-team-1858-7916

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7917.tf
> request: add client files for service-account-team-1858-7917

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-12-b-ce-id-non-prod-7918.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-12-b-ce-id-non-prod-7918.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-8-12-b-ce-id-non-prod-7918

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-12-b-ce-id-with-prod-7919.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-8-12-b-ce-id-with-prod-7919.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-12-b-ce-id-with-prod-7919.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-8-12-b-ce-id-with-prod-7919

- terraform-v2/keycloak-dev/standard-clients/junmin-7888.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3900</li></ul>```
</details>
> request: add client files for junmin-7888

- terraform-v2/keycloak-dev/standard-clients/saml-integration-junmin-7920.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for saml-integration-junmin-7920

- terraform/keycloak-dev/realms/onestopauth-basic/client-idp-test-silver-7921.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for idp-test-silver-7921

- terraform/keycloak-dev/realms/onestopauth-basic/client-idp-testing-7923.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for idp-testing-7923

- terraform-v2/keycloak-dev/standard-clients/aug-16-recording-b-ce-id-7925.tf
- terraform-v2/keycloak-prod/standard-clients/aug-16-recording-b-ce-id-7925.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for aug-16-recording-b-ce-id-7925

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-17-b-ceid-no-prod-7926.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-17-b-ceid-no-prod-7926.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleddd</li></ul>```
</details>
> request: add client files for tians-testing-8-17-b-ceid-no-prod-7926

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-17-b-ce-id-prod-7927.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-8-17-b-ce-id-prod-7927.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-17-b-ce-id-prod-7927.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-8-17-b-ce-id-prod-7927

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-17-b-ce-id-add-both-7928.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-17-b-ce-id-add-both-7928.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-8-17-b-ce-id-add-both-7928

- terraform-v2/keycloak-dev/standard-clients/idir-only-email-test-user-aug-17-7929.tf
- terraform-v2/keycloak-prod/standard-clients/idir-only-email-test-user-aug-17-7929.tf
- terraform-v2/keycloak-test/standard-clients/idir-only-email-test-user-aug-17-7929.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for idir-only-email-test-user-aug-17-7929

- terraform-v2/keycloak-dev/standard-clients/b-cei-d-non-prod-email-test-user-aug-17-7931.tf
- terraform-v2/keycloak-test/standard-clients/b-cei-d-non-prod-email-test-user-aug-17-7931.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for b-cei-d-non-prod-email-test-user-aug-17-7931

- terraform-v2/keycloak-dev/standard-clients/idir-only-email-test-team-aug-17-7930.tf
- terraform-v2/keycloak-test/standard-clients/idir-only-email-test-team-aug-17-7930.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for idir-only-email-test-team-aug-17-7930

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-prod-email-test-user-aug-17-7932.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-prod-email-test-user-aug-17-7932.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-prod-email-test-user-aug-17-7932.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for b-ce-id-prod-email-test-user-aug-17-7932

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-prod-email-test-team-aug-17-7933.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-prod-email-test-team-aug-17-7933.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-prod-email-test-team-aug-17-7933.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for b-ce-id-prod-email-test-team-aug-17-7933

- terraform-v2/keycloak-dev/standard-clients/b-cei-d-non-prod-email-test-team-aug-17-7934.tf
- terraform-v2/keycloak-test/standard-clients/b-cei-d-non-prod-email-test-team-aug-17-7934.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for b-cei-d-non-prod-email-test-team-aug-17-7934

- terraform-v2/keycloak-dev/standard-clients/idir-only-email-test-team-aug-17-7935.tf
- terraform-v2/keycloak-prod/standard-clients/idir-only-email-test-team-aug-17-7935.tf
- terraform-v2/keycloak-test/standard-clients/idir-only-email-test-team-aug-17-7935.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for idir-only-email-test-team-aug-17-7935

- terraform-v2/keycloak-dev/standard-clients/secrettesting-7954.tf
- terraform-v2/keycloak-test/standard-clients/secrettesting-7954.tf
```<ul>✔️Valid Redirect Urls<li>https://secrettesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://secrettesting4test.com</li></ul>```
</details>
> request: add client files for secrettesting-7954

- terraform-v2/keycloak-dev/standard-clients/secrettest-css-api-7955.tf
- terraform-v2/keycloak-test/standard-clients/secrettest-css-api-7955.tf
```<ul>✔️Valid Redirect Urls<li>https://secretcssapidev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://secretcssapitest.com</li></ul>```
</details>
> request: add client files for secrettest-css-api-7955

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1883-7957.tf
> request: add client files for service-account-team-1883-7957

- terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-7956.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-saml-7956.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-saml-7956.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-saml-7956

- terraform-v2/keycloak-dev/standard-clients/css-api-service-account-7958.tf
- terraform-v2/keycloak-test/standard-clients/css-api-service-account-7958.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for css-api-service-account-7958

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1884-7959.tf
> request: add client files for service-account-team-1884-7959

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1882-7960.tf
> request: add client files for service-account-team-1882-7960

- terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-2-with-team-7961.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-saml-2-with-team-7961.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-saml-2-with-team-7961

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1859-7962.tf
> request: add client files for service-account-team-1859-7962

- terraform-v2/keycloak-dev/standard-clients/css-api-service-account-7963.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for css-api-service-account-7963

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1885-7964.tf
> request: add client files for service-account-team-1885-7964

- terraform/keycloak-dev/realms/onestopauth/client-august-19-silver-test-7967.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for august-19-silver-test-7967

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1886-7987.tf
> request: add client files for service-account-team-1886-7987

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1916-7988.tf
> request: add client files for service-account-team-1916-7988

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-7896.tf
> request: delete client files for service-account-team-1861-7896

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-7989.tf
> request: add client files for service-account-team-1861-7989

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-7990.tf
> request: add client files for service-account-team-1861-7990

- terraform-v2/keycloak-dev/standard-clients/abc-7992.tf
- terraform-v2/keycloak-test/standard-clients/abc-7992.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for abc-7992

- terraform-v2/keycloak-dev/standard-clients/junmin-saml-test-2-7922.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for junmin-saml-test-2-7922

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7917.tf
> request: delete client files for service-account-team-1858-7917

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1858-7993.tf
> request: add client files for service-account-team-1858-7993

- terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-7994.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-gold-7994.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-gold-7994

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1859-7962.tf
> request: delete client files for service-account-team-1859-7962

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1886-7987.tf
> request: delete client files for service-account-team-1886-7987

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1916-7988.tf
> request: delete client files for service-account-team-1916-7988

- terraform-v2/keycloak-dev/standard-clients/tians-testing-gold-t-t-3-7995.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-gold-t-t-3-7995.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-gold-t-t-3-7995.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-gold-t-t-3-7995

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1859-7996.tf
> request: add client files for service-account-team-1859-7996

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1886-7997.tf
> request: add client files for service-account-team-1886-7997

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1916-7998.tf
> request: add client files for service-account-team-1916-7998

- terraform/keycloak-dev/realms/onestopauth/client-tians-testing-silver-in-silver-t-t-7999.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-silver-in-silver-t-t-7999

- terraform-v2/keycloak-dev/standard-clients/tians-testing-t-t-2-8000.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-t-t-2-8000.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-t-t-2-8000

- terraform-v2/keycloak-dev/standard-clients/tians-testing-t-t-saml-8001.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-t-t-saml-8001.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-t-t-saml-8001.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-t-t-saml-8001

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1750-8002.tf
> request: add client files for service-account-team-1750-8002

- terraform-v2/keycloak-dev/standard-clients/tians-testing-service-account-8006.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-service-account-8006.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for tians-testing-service-account-8006

- terraform-v2/keycloak-dev/standard-clients/tians-another-test-8007.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-another-test-8007

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1685-8009.tf
> request: add client files for service-account-team-1685-8009

- terraform/keycloak-dev/realms/onestopauth-both/client-tians-testing-silver-b-ce-id-both-8010.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-silver-b-ce-id-both-8010

- terraform-v2/keycloak-dev/standard-clients/test-integration-8021.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for test-integration-8021

- terraform-v2/keycloak-dev/standard-clients/apm-8024.tf
- terraform-v2/keycloak-prod/standard-clients/apm-8024.tf
```<ul>✔️Valid Redirect Urls<li>https://apm.io.nrs.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://apm.io.nrs.gov.bc.ca</li></ul>```
</details>
> request: add client files for apm-8024

- terraform-v2/keycloak-dev/standard-clients/test-2-8023.tf
- terraform-v2/keycloak-test/standard-clients/test-2-8023.tf
```<ul>✔️Valid Redirect Urls<li>https://vault-iit-dev.apps.silver.devops.gov.bc.ca</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://vault-iit-dev.apps.silver.devops.gov.bc.ca</li></ul>```
</details>
> request: add client files for test-2-8023

- terraform-v2/keycloak-dev/standard-clients/tians-testing-service-account-api-test-8026.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-service-account-api-test-8026.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-service-account-api-test-8026.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-service-account-api-test-8026

- terraform-v2/keycloak-dev/standard-clients/tians-testing-service-account-api-test-8027.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-service-account-api-test-8027.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-service-account-api-test-8027.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for tians-testing-service-account-api-test-8027

- terraform-v2/keycloak-dev/standard-clients/tians-testing-test-kc-disable-8029.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-test-kc-disable-8029.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-test-kc-disable-8029.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-test-kc-disable-8029

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-without-team-8030.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-without-team-8030.tf
```<ul>✔️Valid Redirect Urls<li>https://BCeIDdevtestCSS.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://BCeIDtesttestCSS.com</li></ul>```
</details>
> request: add client files for b-ce-id-without-team-8030

- terraform-v2/keycloak-dev/standard-clients/junmin-github-8031.tf
- terraform-v2/keycloak-prod/standard-clients/junmin-github-8031.tf
- terraform-v2/keycloak-test/standard-clients/junmin-github-8031.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for junmin-github-8031

- terraform-v2/keycloak-dev/standard-clients/abc-8008.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for abc-8008

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-with-team-8033.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-with-team-8033.tf
```<ul>✔️Valid Redirect Urls<li>https://BCeidteamdevtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://BCeidteamtesttest.com</li></ul>```
</details>
> request: add client files for b-ce-id-with-team-8033

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-oidc-8035.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-oidc-8035.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-oidc-8035.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-oidc-8035

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-with-team-8036.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-with-team-8036.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-with-team-8036.tf
```<ul>✔️Valid Redirect Urls<li>https://BCeIDdevtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://BCeIDtesttest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://BCeIDprodtest.com</li></ul>```
</details>
> request: add client files for b-ce-id-with-team-8036

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-oidc-public-8037.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-oidc-public-8037.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-oidc-public-8037.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-oidc-public-8037

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-with-no-team-8038.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-with-no-team-8038.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-with-no-team-8038.tf
```<ul>✔️Valid Redirect Urls<li>https://BCeIDdevtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://BCeIDtesttest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://BCeIDprodtest.com</li></ul>```
</details>
> request: add client files for b-ce-id-with-no-team-8038

- terraform-v2/keycloak-dev/standard-clients/saml-test-zorin-7991.tf
- terraform-v2/keycloak-test/standard-clients/saml-test-zorin-7991.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for saml-test-zorin-7991

- terraform-v2/keycloak-dev/standard-clients/idir-with-b-ce-id-8040.tf
- terraform-v2/keycloak-prod/standard-clients/idir-with-b-ce-id-8040.tf
- terraform-v2/keycloak-test/standard-clients/idir-with-b-ce-id-8040.tf
```<ul>✔️Valid Redirect Urls<li>https://IDIRBCeIDdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://IDIRBCeIDtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://IDIRBCeIDprod.com</li></ul>```
</details>
> request: add client files for idir-with-b-ce-id-8040

- terraform-v2/keycloak-dev/standard-clients/junmin-github-8041.tf
- terraform-v2/keycloak-prod/standard-clients/junmin-github-8041.tf
- terraform-v2/keycloak-test/standard-clients/junmin-github-8041.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for junmin-github-8041

- terraform-v2/keycloak-dev/standard-clients/idir-first-then-add-bceid-8043.tf
- terraform-v2/keycloak-prod/standard-clients/idir-first-then-add-bceid-8043.tf
- terraform-v2/keycloak-test/standard-clients/idir-first-then-add-bceid-8043.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for idir-first-then-add-bceid-8043

- terraform-v2/keycloak-dev/standard-clients/junmin-bceid-prod-8044.tf
- terraform-v2/keycloak-prod/standard-clients/junmin-bceid-prod-8044.tf
- terraform-v2/keycloak-test/standard-clients/junmin-bceid-prod-8044.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for junmin-bceid-prod-8044

- terraform-v2/keycloak-dev/standard-clients/api-test-sept-15-2-8046.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for api-test-sept-15-2-8046

- terraform-v2/keycloak-dev/standard-clients/tians-testing-github-oidc-service-acct-8047.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-github-oidc-service-acct-8047.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-github-oidc-service-acct-8047.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for tians-testing-github-oidc-service-acct-8047

- terraform-v2/keycloak-dev/standard-clients/tians-testing-oidc-brower-login-8048.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-oidc-brower-login-8048.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-oidc-brower-login-8048.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-oidc-brower-login-8048

- terraform-v2/keycloak-dev/standard-clients/tians-testing-oidc-both-8049.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-oidc-both-8049.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-oidc-both-8049.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-oidc-both-8049

- terraform-v2/keycloak-dev/standard-clients/tians-testing-oidc-prod-later-8050.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-oidc-prod-later-8050.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-oidc-prod-later-8050

- terraform-v2/keycloak-dev/standard-clients/tians-testing-github-b-ce-id-approval-8053.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-github-b-ce-id-approval-8053.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-github-b-ce-id-approval-8053.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-github-b-ce-id-approval-8053

- terraform-v2/keycloak-dev/standard-clients/sept-16-idir-only-1-a-8054.tf
- terraform-v2/keycloak-prod/standard-clients/sept-16-idir-only-1-a-8054.tf
- terraform-v2/keycloak-test/standard-clients/sept-16-idir-only-1-a-8054.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-16-idir-only-1-a-8054

- terraform-v2/keycloak-dev/standard-clients/sept-16-idir-only-1-b-8055.tf
- terraform-v2/keycloak-prod/standard-clients/sept-16-idir-only-1-b-8055.tf
- terraform-v2/keycloak-test/standard-clients/sept-16-idir-only-1-b-8055.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-16-idir-only-1-b-8055

- terraform-v2/keycloak-dev/standard-clients/tian-1-s-testing-no-team-8056.tf
- terraform-v2/keycloak-prod/standard-clients/tian-1-s-testing-no-team-8056.tf
- terraform-v2/keycloak-test/standard-clients/tian-1-s-testing-no-team-8056.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tian-1-s-testing-no-team-8056

- terraform-v2/keycloak-dev/standard-clients/sept-16-testing-teams-8057.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-16-testing-teams-8057

- terraform-v2/keycloak-dev/standard-clients/test-8059.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for test-8059

- terraform-v2/keycloak-dev/standard-clients/tians-testing-github-b-ce-id-prod-approval-8060.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-github-b-ce-id-prod-approval-8060.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-github-b-ce-id-prod-approval-8060.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-github-b-ce-id-prod-approval-8060

- terraform-v2/keycloak-dev/standard-clients/tians-testing-github-b-ce-id-prod-approval-1-8061.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-github-b-ce-id-prod-approval-1-8061.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-github-b-ce-id-prod-approval-1-8061.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-github-b-ce-id-prod-approval-1-8061

- terraform-v2/keycloak-dev/standard-clients/nk-test-gh-prod-8062.tf
- terraform-v2/keycloak-prod/standard-clients/nk-test-gh-prod-8062.tf
- terraform-v2/keycloak-test/standard-clients/nk-test-gh-prod-8062.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for nk-test-gh-prod-8062

- terraform-v2/keycloak-dev/standard-clients/sept-20-git-hub-test-1-scenario-3-a-8064.tf
- terraform-v2/keycloak-test/standard-clients/sept-20-git-hub-test-1-scenario-3-a-8064.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-git-hub-test-1-scenario-3-a-8064

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-new-test-with-team-8063.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-new-test-with-team-8063.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-new-test-with-team-8063.tf
```<ul>✔️Valid Redirect Urls<li>https://bceidnewdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bceidnewtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bceidneprod.com</li></ul>```
</details>
> request: add client files for b-ce-id-new-test-with-team-8063

- terraform-v2/keycloak-dev/standard-clients/sept-20-git-hub-test-2-scenario-3-b-8065.tf
- terraform-v2/keycloak-test/standard-clients/sept-20-git-hub-test-2-scenario-3-b-8065.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-git-hub-test-2-scenario-3-b-8065

- terraform-v2/keycloak-dev/standard-clients/sept-20-github-test-3-scenario-3-c-8066.tf
- terraform-v2/keycloak-prod/standard-clients/sept-20-github-test-3-scenario-3-c-8066.tf
- terraform-v2/keycloak-test/standard-clients/sept-20-github-test-3-scenario-3-c-8066.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-github-test-3-scenario-3-c-8066

- terraform-v2/keycloak-dev/standard-clients/sept-20-github-test-3-scenario-3-d-8067.tf
- terraform-v2/keycloak-prod/standard-clients/sept-20-github-test-3-scenario-3-d-8067.tf
- terraform-v2/keycloak-test/standard-clients/sept-20-github-test-3-scenario-3-d-8067.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-github-test-3-scenario-3-d-8067

- terraform-v2/keycloak-dev/standard-clients/test-3-8068.tf
```<ul>✔️Valid Redirect Urls<li>https://localhost</li></ul>```
</details>
> request: add client files for test-3-8068

- terraform-v2/keycloak-dev/standard-clients/email-gh-prod-nk-testing-8072.tf
- terraform-v2/keycloak-test/standard-clients/email-gh-prod-nk-testing-8072.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for email-gh-prod-nk-testing-8072

- terraform-v2/keycloak-dev/standard-clients/sept-20-bceid-np-to-p-1-8073.tf
- terraform-v2/keycloak-test/standard-clients/sept-20-bceid-np-to-p-1-8073.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-bceid-np-to-p-1-8073

- terraform-v2/keycloak-dev/standard-clients/sept-20-bceid-prod-8074.tf
- terraform-v2/keycloak-prod/standard-clients/sept-20-bceid-prod-8074.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-bceid-prod-8074

- terraform-v2/keycloak-dev/standard-clients/sept-20-bceid-np-to-p-2-8075.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-bceid-np-to-p-2-8075

- terraform-v2/keycloak-dev/standard-clients/sept-20-github-prod-ztest-1-8077.tf
- terraform-v2/keycloak-prod/standard-clients/sept-20-github-prod-ztest-1-8077.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for sept-20-github-prod-ztest-1-8077

- terraform-v2/keycloak-dev/standard-clients/tians-testing-service-account-8080.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-service-account-8080.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-service-account-8080.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for tians-testing-service-account-8080

- terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-and-git-hub-8081.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-and-git-hub-8081.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-b-ce-id-and-git-hub-8081.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-b-ce-id-and-git-hub-8081

- terraform-v2/keycloak-dev/standard-clients/junmin-bceid-github-8082.tf
- terraform-v2/keycloak-prod/standard-clients/junmin-bceid-github-8082.tf
- terraform-v2/keycloak-test/standard-clients/junmin-bceid-github-8082.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for junmin-bceid-github-8082

- terraform-v2/keycloak-dev/standard-clients/tians-testing-multi-id-ps-8083.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-multi-id-ps-8083.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-multi-id-ps-8083.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-multi-id-ps-8083

- terraform-v2/keycloak-dev/standard-clients/tians-testing-multiple-id-ps-2-8084.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-multiple-id-ps-2-8084.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-multiple-id-ps-2-8084.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-multiple-id-ps-2-8084

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8085.tf
> request: add client files for service-account-team-1953-8085

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8085.tf
> request: delete client files for service-account-team-1953-8085

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1960-8087.tf
> request: add client files for service-account-team-1960-8087

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8088.tf
> request: add client files for service-account-team-1953-8088

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8088.tf
> request: delete client files for service-account-team-1953-8088

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1957-8089.tf
> request: add client files for service-account-team-1957-8089

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1957-8089.tf
> request: delete client files for service-account-team-1957-8089

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8091.tf
> request: add client files for service-account-team-1953-8091

- terraform-v2/keycloak-dev/standard-clients/github-dev-test-no-team-8092.tf
- terraform-v2/keycloak-test/standard-clients/github-dev-test-no-team-8092.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githutest.com</li></ul>```
</details>
> request: add client files for github-dev-test-no-team-8092

- terraform-v2/keycloak-dev/standard-clients/github-dev-test-with-team-8093.tf
- terraform-v2/keycloak-test/standard-clients/github-dev-test-with-team-8093.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
</details>
> request: add client files for github-dev-test-with-team-8093

- terraform-v2/keycloak-dev/standard-clients/github-dev-test-prod-no-team-no-apporval-8094.tf
- terraform-v2/keycloak-prod/standard-clients/github-dev-test-prod-no-team-no-apporval-8094.tf
- terraform-v2/keycloak-test/standard-clients/github-dev-test-prod-no-team-no-apporval-8094.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubprod.com</li></ul>```
</details>
> request: add client files for github-dev-test-prod-no-team-no-apporval-8094

- terraform-v2/keycloak-dev/standard-clients/github-dev-test-prod-team-no-approval-8095.tf
- terraform-v2/keycloak-prod/standard-clients/github-dev-test-prod-team-no-approval-8095.tf
- terraform-v2/keycloak-test/standard-clients/github-dev-test-prod-team-no-approval-8095.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubprod.com</li></ul>```
</details>
> request: add client files for github-dev-test-prod-team-no-approval-8095

- terraform-v2/keycloak-dev/standard-clients/githun-dev-test-prod-no-team-and-prod-approve-8096.tf
- terraform-v2/keycloak-prod/standard-clients/githun-dev-test-prod-no-team-and-prod-approve-8096.tf
- terraform-v2/keycloak-test/standard-clients/githun-dev-test-prod-no-team-and-prod-approve-8096.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubprod.com</li></ul>```
</details>
> request: add client files for githun-dev-test-prod-no-team-and-prod-approve-8096

- terraform-v2/keycloak-dev/standard-clients/githun-dev-test-prod-with-team-and-prod-approve-8097.tf
- terraform-v2/keycloak-prod/standard-clients/githun-dev-test-prod-with-team-and-prod-approve-8097.tf
- terraform-v2/keycloak-test/standard-clients/githun-dev-test-prod-with-team-and-prod-approve-8097.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubprod.com</li></ul>```
</details>
> request: add client files for githun-dev-test-prod-with-team-and-prod-approve-8097

- terraform-v2/keycloak-dev/standard-clients/tians-testing-role-attributes-8099.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-role-attributes-8099.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-role-attributes-8099.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-role-attributes-8099

- terraform-v2/keycloak-dev/standard-clients/s-ept-23-test-email-non-redirect-updates-8100.tf
- terraform-v2/keycloak-prod/standard-clients/s-ept-23-test-email-non-redirect-updates-8100.tf
- terraform-v2/keycloak-test/standard-clients/s-ept-23-test-email-non-redirect-updates-8100.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for s-ept-23-test-email-non-redirect-updates-8100

- terraform-v2/keycloak-dev/standard-clients/s-ept-23-redirect-updates-bceid-prod-8101.tf
- terraform-v2/keycloak-prod/standard-clients/s-ept-23-redirect-updates-bceid-prod-8101.tf
- terraform-v2/keycloak-test/standard-clients/s-ept-23-redirect-updates-bceid-prod-8101.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for s-ept-23-redirect-updates-bceid-prod-8101

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-7990.tf
> request: delete client files for service-account-team-1861-7990

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-8102.tf
> request: add client files for service-account-team-1861-8102

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1959-8103.tf
> request: add client files for service-account-team-1959-8103

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1959-8104.tf
> request: add client files for service-account-team-1959-8104

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-8102.tf
> request: delete client files for service-account-team-1861-8102

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1959-8104.tf
> request: delete client files for service-account-team-1959-8104

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1959-8103.tf
> request: delete client files for service-account-team-1959-8103

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8091.tf
> request: delete client files for service-account-team-1953-8091

- terraform-v2/keycloak-dev/standard-clients/idir-with-github-no-prod-approve-8105.tf
- terraform-v2/keycloak-prod/standard-clients/idir-with-github-no-prod-approve-8105.tf
- terraform-v2/keycloak-test/standard-clients/idir-with-github-no-prod-approve-8105.tf
```<ul>✔️Valid Redirect Urls<li>https://githubdev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubtest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://githubprod.com</li></ul>```
</details>
> request: add client files for idir-with-github-no-prod-approve-8105

- terraform-v2/keycloak-dev/standard-clients/tians-testing-9-26-b-ce-id-with-prod-8107.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-9-26-b-ce-id-with-prod-8107.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-9-26-b-ce-id-with-prod-8107.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-9-26-b-ce-id-with-prod-8107

- terraform-v2/keycloak-dev/standard-clients/tians-testing-9-26-b-ce-id-with-prod-later-8108.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-9-26-b-ce-id-with-prod-later-8108.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-9-26-b-ce-id-with-prod-later-8108

- terraform-v2/keycloak-dev/standard-clients/tians-testing-9-26-git-hub-with-prod-8109.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-9-26-git-hub-with-prod-8109.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-9-26-git-hub-with-prod-8109.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-9-26-git-hub-with-prod-8109

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-prod-later-8110.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-prod-later-8110.tf
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-prod-later-8110

- terraform-v2/keycloak-dev/standard-clients/tians-testing-combo-with-prod-8111.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-combo-with-prod-8111.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-combo-with-prod-8111.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-combo-with-prod-8111

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-8112.tf
> request: add client files for service-account-team-1861-8112

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-8113.tf
> request: add client files for service-account-team-1861-8113

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1861-8113.tf
> request: delete client files for service-account-team-1861-8113

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8115.tf
> request: add client files for service-account-team-1953-8115

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8115.tf
> request: delete client files for service-account-team-1953-8115

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8117.tf
> request: add client files for service-account-team-1953-8117

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-git-hub-prod-with-b-ce-id-approve-8116.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-git-hub-prod-with-b-ce-id-approve-8116.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-git-hub-prod-with-b-ce-id-approve-8116.tf
```<ul>✔️Valid Redirect Urls<li>https://prioirtytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioirtytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioirtytesting.com</li></ul>```
</details>
> request: add client files for b-ce-id-git-hub-prod-with-b-ce-id-approve-8116

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8117.tf
> request: delete client files for service-account-team-1953-8117

- terraform-v2/keycloak-dev/standard-clients/bceid-and-github-prod-only-git-hub-prod-approve-8119.tf
- terraform-v2/keycloak-prod/standard-clients/bceid-and-github-prod-only-git-hub-prod-approve-8119.tf
- terraform-v2/keycloak-test/standard-clients/bceid-and-github-prod-only-git-hub-prod-approve-8119.tf
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
</details>
> request: add client files for bceid-and-github-prod-only-git-hub-prod-approve-8119

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-and-github-test-8120.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-and-github-test-8120.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-and-github-test-8120.tf
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
</details>
> request: add client files for b-ce-id-and-github-test-8120

- terraform-v2/keycloak-dev/standard-clients/b-ce-id-and-github-prod-approve-8121.tf
- terraform-v2/keycloak-prod/standard-clients/b-ce-id-and-github-prod-approve-8121.tf
- terraform-v2/keycloak-test/standard-clients/b-ce-id-and-github-prod-approve-8121.tf
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioritytesting.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://prioirtytesting.com</li></ul>```
</details>
> request: add client files for b-ce-id-and-github-prod-approve-8121

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8122.tf
> request: add client files for service-account-team-1953-8122

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8122.tf
> request: delete client files for service-account-team-1953-8122

- terraform-v2/keycloak-dev/standard-clients/test-o-ct-10-8154.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/sso-requests-test/request/8154?step=1#</li></ul>```
</details>
> request: add client files for test-o-ct-10-8154

- terraform-v2/keycloak-dev/standard-clients/test-8069.tf
- terraform-v2/keycloak-prod/standard-clients/test-8069.tf
- terraform-v2/keycloak-test/standard-clients/test-8069.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
> request: add client files for test-8069

- terraform-v2/keycloak-dev/standard-clients/zz-8005.tf
- terraform-v2/keycloak-prod/standard-clients/zz-8005.tf
- terraform-v2/keycloak-test/standard-clients/zz-8005.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
> request: add client files for zz-8005

- terraform-v2/keycloak-dev/standard-clients/tians-testing-10-13-composite-role-api-8186.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-10-13-composite-role-api-8186.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-10-13-composite-role-api-8186

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1953-8187.tf
> request: add client files for service-account-team-1953-8187

- terraform-v2/keycloak-dev/standard-clients/junmin-project-8185.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for junmin-project-8185

- terraform-v2/keycloak-dev/standard-clients/zz-7676.tf
```<ul>✔️Valid Redirect Urls<li>https://.</li></ul>```
</details>
> request: add client files for zz-7676

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-all-8219.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-all-8219.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-all-8219.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-all-8219

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-non-admin-8220.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-non-admin-8220.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-non-admin-8220.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-non-admin-8220

- terraform-v2/keycloak-dev/standard-clients/tian-testing-git-hub-sso-admin-8222.tf
- terraform-v2/keycloak-prod/standard-clients/tian-testing-git-hub-sso-admin-8222.tf
- terraform-v2/keycloak-test/standard-clients/tian-testing-git-hub-sso-admin-8222.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tian-testing-git-hub-sso-admin-8222

- terraform-v2/keycloak-dev/standard-clients/tian-testing-git-hub-sso-admin-notification-8223.tf
- terraform-v2/keycloak-prod/standard-clients/tian-testing-git-hub-sso-admin-notification-8223.tf
- terraform-v2/keycloak-test/standard-clients/tian-testing-git-hub-sso-admin-notification-8223.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tian-testing-git-hub-sso-admin-notification-8223

- terraform-v2/keycloak-dev/standard-clients/oct-19-test-github-bc-gov-8224.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-19-test-github-bc-gov-8224

- terraform-v2/keycloak-dev/standard-clients/oct-19-test-3-idir-8153.tf
- terraform-v2/keycloak-prod/standard-clients/oct-19-test-3-idir-8153.tf
- terraform-v2/keycloak-test/standard-clients/oct-19-test-3-idir-8153.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-19-test-3-idir-8153

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1986-8225.tf
> request: add client files for service-account-team-1986-8225

- terraform-v2/keycloak-dev/standard-clients/oct-19-idir-and-then-b-cei-d-both-w-tian-8226.tf
- terraform-v2/keycloak-prod/standard-clients/oct-19-idir-and-then-b-cei-d-both-w-tian-8226.tf
- terraform-v2/keycloak-test/standard-clients/oct-19-idir-and-then-b-cei-d-both-w-tian-8226.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-19-idir-and-then-b-cei-d-both-w-tian-8226

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1986-8225.tf
> request: delete client files for service-account-team-1986-8225

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1986-8227.tf
> request: add client files for service-account-team-1986-8227

- terraform-v2/keycloak-dev/standard-clients/oct-19-github-all-sso-admin-created-8228.tf
- terraform-v2/keycloak-test/standard-clients/oct-19-github-all-sso-admin-created-8228.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-19-github-all-sso-admin-created-8228

- terraform-v2/keycloak-dev/standard-clients/oct-19-non-sso-admin-git-hub-8229.tf
```<ul>✔️Valid Redirect Urls<li>https://www.google.ca</li></ul>```
</details>
> request: add client files for oct-19-non-sso-admin-git-hub-8229

- terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-demo-8251.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-saml-demo-8251.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-saml-demo-8251

- terraform-v2/keycloak-dev/standard-clients/tians-testing-saml-8252.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-saml-8252.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-saml-8252

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8253.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8253.tf
```<ul>✔️Valid Redirect Urls<li>https://example.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
</details>
> request: add client files for tians-testing-8253

- terraform-v2/keycloak-dev/standard-clients/css-app-k-6-cicd-project-8254.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for css-app-k-6-cicd-project-8254

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2016-8255.tf
> request: add client files for service-account-team-2016-8255

- terraform-v2/keycloak-dev/standard-clients/oct-21-test-idir-and-then-b-ce-id-8256.tf
- terraform-v2/keycloak-prod/standard-clients/oct-21-test-idir-and-then-b-ce-id-8256.tf
- terraform-v2/keycloak-test/standard-clients/oct-21-test-idir-and-then-b-ce-id-8256.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-21-test-idir-and-then-b-ce-id-8256

- terraform-v2/keycloak-dev/standard-clients/tians-testing-idir-all-environment-8257.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-idir-all-environment-8257.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-idir-all-environment-8257.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-idir-all-environment-8257

- terraform-v2/keycloak-dev/standard-clients/oct-21-test-idir-prod-and-b-ce-id-non-prod-8258.tf
- terraform-v2/keycloak-test/standard-clients/oct-21-test-idir-prod-and-b-ce-id-non-prod-8258.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-21-test-idir-prod-and-b-ce-id-non-prod-8258

- terraform-v2/keycloak-dev/standard-clients/oct-21-idir-non-prods-and-then-bceid-non-prods-8259.tf
- terraform-v2/keycloak-test/standard-clients/oct-21-idir-non-prods-and-then-bceid-non-prods-8259.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-21-idir-non-prods-and-then-bceid-non-prods-8259

- terraform-v2/keycloak-dev/standard-clients/kuro-email-usecase-8261.tf
- terraform-v2/keycloak-test/standard-clients/kuro-email-usecase-8261.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-email-usecase-8261

- terraform-v2/keycloak-dev/standard-clients/tians-testing-10-24-git-hub-bc-gov-8263.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-10-24-git-hub-bc-gov-8263

- terraform-v2/keycloak-dev/standard-clients/tians-testing-10-24-git-hub-public-8264.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-10-24-git-hub-public-8264

- terraform-v2/keycloak-dev/standard-clients/tians-testing-10-24-git-hub-non-admin-8265.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-10-24-git-hub-non-admin-8265

- terraform-v2/keycloak-dev/standard-clients/kuro-email-usecase-auth-type-8266.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-email-usecase-auth-type-8266

- terraform-v2/keycloak-dev/standard-clients/tians-testing-tab-jumping-8267.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-tab-jumping-8267

- terraform-v2/keycloak-dev/standard-clients/tians-testing-service-account-email-8268.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-service-account-email-8268.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for tians-testing-service-account-email-8268

- terraform-v2/keycloak-dev/standard-clients/kuro-auth-type-service-account-8269.tf
- terraform-v2/keycloak-test/standard-clients/kuro-auth-type-service-account-8269.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for kuro-auth-type-service-account-8269

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-8271.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for kuro-testing-8271

- terraform-v2/keycloak-dev/standard-clients/service-account-team-8272.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for service-account-team-8272

- terraform-v2/keycloak-dev/standard-clients/auth-type-testing-8273.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for auth-type-testing-8273

- terraform-v2/keycloak-dev/standard-clients/auth-type-team-test-8274.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for auth-type-team-test-8274

- terraform-v2/keycloak-dev/standard-clients/tians-testing-10-28-service-account-email-8275.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-10-28-service-account-email-8275.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-10-28-service-account-email-8275.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for tians-testing-10-28-service-account-email-8275

- terraform-v2/keycloak-dev/standard-clients/tians-testing-10-28-mixed-account-email-8276.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-10-28-mixed-account-email-8276.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-10-28-mixed-account-email-8276.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-10-28-mixed-account-email-8276

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-bc-gov-8277.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-bc-gov-8277.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-bc-gov-8277.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-bc-gov-8277

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1820-8291.tf
> request: add client files for service-account-team-1820-8291

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-4-git-hub-bc-gov-8293.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-4-git-hub-bc-gov-8293.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-4-git-hub-bc-gov-8293.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-4-git-hub-bc-gov-8293

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-4-git-hub-public-8294.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-4-git-hub-public-8294.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-4-git-hub-public-8294.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-4-git-hub-public-8294

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-4-git-hub-saml-8295.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-4-git-hub-saml-8295.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-4-git-hub-saml-8295.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-4-git-hub-saml-8295

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-4-git-hub-bc-gov-8296.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-4-git-hub-bc-gov-8296.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-4-git-hub-bc-gov-8296.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-4-git-hub-bc-gov-8296

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-b-ce-id-8297.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-b-ce-id-8297.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-b-ce-id-8297.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-b-ce-id-8297

- terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-git-hub-8298.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-git-hub-8298.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-b-ce-id-git-hub-8298.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-b-ce-id-git-hub-8298

- terraform-v2/keycloak-dev/standard-clients/tians-testing-b-ce-id-8299.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-b-ce-id-8299.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-b-ce-id-8299.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-b-ce-id-8299

- terraform-v2/keycloak-dev/standard-clients/tians-testing-new-b-ce-id-git-hub-8300.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-new-b-ce-id-git-hub-8300.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-new-b-ce-id-git-hub-8300.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-new-b-ce-id-git-hub-8300

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-7-test-timeout-8301.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-7-test-timeout-8301.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-7-test-timeout-8301.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-11-7-test-timeout-8301

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1123-8302.tf
> request: add client files for service-account-team-1123-8302

- terraform-v2/keycloak-dev/standard-clients/nov-9-test-8303.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-9-test-8303

- terraform-v2/keycloak-dev/standard-clients/test-mds-script-nk-8304.tf
- terraform-v2/keycloak-test/standard-clients/test-mds-script-nk-8304.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-mds-script-nk-8304

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-8306.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-8306.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-8306.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-8306

- terraform-v2/keycloak-dev/standard-clients/tians-testing-git-hub-demo-8309.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-git-hub-demo-8309.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-git-hub-demo-8309.tf
```<ul>✔️Valid Redirect Urls<li>https://exmapleDev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exmapleTest.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exmapleProd.com</li></ul>```
</details>
> request: add client files for tians-testing-git-hub-demo-8309

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-8308.tf
- terraform-v2/keycloak-test/standard-clients/kuro-testing-8308.tf
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-testing-8308

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8311.tf
> request: add client files for service-account-team-2014-8311

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8311.tf
> request: delete client files for service-account-team-2014-8311

- terraform-v2/keycloak-dev/standard-clients/oct-19-sso-admin-2-8230.tf
- terraform-v2/keycloak-test/standard-clients/oct-19-sso-admin-2-8230.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for oct-19-sso-admin-2-8230

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2048-8312.tf
> request: add client files for service-account-team-2048-8312

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2048-8312.tf
> request: delete client files for service-account-team-2048-8312

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-22-b-ce-id-client-role-search-8313.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-22-b-ce-id-client-role-search-8313.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-22-b-ce-id-client-role-search-8313.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-22-b-ce-id-client-role-search-8313

- terraform-v2/keycloak-dev/standard-clients/junmin-tests-8152.tf
```<ul>✔️Valid Redirect Urls<li>https://dev.loginproxy.gov.bc.ca/auth/realms/my-realm/*</li></ul>```
</details>
> request: add client files for junmin-tests-8152

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-23-b-ce-id-client-role-searching-8314.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-23-b-ce-id-client-role-searching-8314.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-23-b-ce-id-client-role-searching-8314.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-23-b-ce-id-client-role-searching-8314

- terraform-v2/keycloak-dev/standard-clients/zorin-test-nov-23-non-prod-b-ce-id-8315.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for zorin-test-nov-23-non-prod-b-ce-id-8315

- terraform-v2/keycloak-dev/standard-clients/nov-23-zorin-test-2-8316.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-23-zorin-test-2-8316

- terraform-v2/keycloak-dev/standard-clients/nov-23-zorin-test-3-8317.tf
- terraform-v2/keycloak-prod/standard-clients/nov-23-zorin-test-3-8317.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-23-zorin-test-3-8317

- terraform-v2/keycloak-dev/standard-clients/zorin-test-b-ce-id-p-rod-emails-5-8318.tf
- terraform-v2/keycloak-prod/standard-clients/zorin-test-b-ce-id-p-rod-emails-5-8318.tf
- terraform-v2/keycloak-test/standard-clients/zorin-test-b-ce-id-p-rod-emails-5-8318.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for zorin-test-b-ce-id-p-rod-emails-5-8318

- terraform-v2/keycloak-dev/standard-clients/junmin-test-8123.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000</li></ul>```
</details>
> request: add client files for junmin-test-8123

- terraform-v2/keycloak-dev/standard-clients/test-with-junmin-8319.tf
- terraform-v2/keycloak-prod/standard-clients/test-with-junmin-8319.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for test-with-junmin-8319

- terraform-v2/keycloak-dev/standard-clients/november-23-test-b-ce-id-8320.tf
- terraform-v2/keycloak-prod/standard-clients/november-23-test-b-ce-id-8320.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for november-23-test-b-ce-id-8320

- terraform-v2/keycloak-dev/standard-clients/nov-28-test-bceid-non-prod-8321.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-28-test-bceid-non-prod-8321

- terraform-v2/keycloak-dev/standard-clients/nov-29-test-b-ce-id-prod-8322.tf
- terraform-v2/keycloak-prod/standard-clients/nov-29-test-b-ce-id-prod-8322.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-29-test-b-ce-id-prod-8322

- terraform-v2/keycloak-dev/standard-clients/nov-28-test-bceid-non-prod-2-8323.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-28-test-bceid-non-prod-2-8323

- terraform-v2/keycloak-dev/standard-clients/nov-28-test-bceid-non-prod-3-8324.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for nov-28-test-bceid-non-prod-3-8324

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-463-7887.tf
> request: delete client files for service-account-team-463-7887

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1123-8302.tf
> request: delete client files for service-account-team-1123-8302

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-29-b-ce-id-edit-8325.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-29-b-ce-id-edit-8325.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-29-b-ce-id-edit-8325.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-11-29-b-ce-id-edit-8325

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-29-b-ce-id-edit-8326.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-29-b-ce-id-edit-8326.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-29-b-ce-id-edit-8326.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-11-29-b-ce-id-edit-8326

- terraform-v2/keycloak-dev/standard-clients/junmin-test-2-8328.tf
- terraform-v2/keycloak-prod/standard-clients/junmin-test-2-8328.tf
- terraform-v2/keycloak-test/standard-clients/junmin-test-2-8328.tf
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:8080</li></ul>```
</details>
> request: add client files for junmin-test-2-8328

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-29-b-ce-id-update-8329.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-29-b-ce-id-update-8329.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-29-b-ce-id-update-8329.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-11-29-b-ce-id-update-8329

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-30-b-ce-id-email-flow-8330.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-30-b-ce-id-email-flow-8330.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-30-b-ce-id-email-flow-8330.tf
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-11-30-b-ce-id-email-flow-8330

- terraform-v2/keycloak-dev/standard-clients/test-hide-header-title-idir-8332.tf
- terraform-v2/keycloak-prod/standard-clients/test-hide-header-title-idir-8332.tf
- terraform-v2/keycloak-test/standard-clients/test-hide-header-title-idir-8332.tf
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-hide-header-title-idir-8332

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-30-post-release-8331.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-30-post-release-8331.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-11-30-post-release-8331

- terraform-v2/keycloak-dev/standard-clients/test-service-account-idir-nk-8333.tf
```<ul>✔️Valid Redirect Urls<li></li></ul>```
</details>
> request: add client files for test-service-account-idir-nk-8333

- terraform-v2/keycloak-dev/standard-clients/dec-4-zorin-git-hub-test-8335.tf
- terraform-v2/keycloak-prod/standard-clients/dec-4-zorin-git-hub-test-8335.tf
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for dec-4-zorin-git-hub-test-8335

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8338.tf
> request: add client files for service-account-team-2014-8338

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8339.tf
> request: add client files for service-account-team-2014-8339

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8340.tf
> request: add client files for service-account-team-2014-8340

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8339.tf
> request: delete client files for service-account-team-2014-8339

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2014-8341.tf
> request: add client files for service-account-team-2014-8341

- terraform-v2/keycloak-dev/standard-clients/test-pr-content-nk-8343.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-pr-content-nk-8343

- terraform-v2/keycloak-dev/standard-clients/test-new-pr-content-nk-8344.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-new-pr-content-nk-8344

- terraform-v2/keycloak-dev/standard-clients/dec-5-zorin-test-service-account-8345.tf
> request: add client files for dec-5-zorin-test-service-account-8345

- terraform-v2/keycloak-dev/standard-clients/tian-testing-12-06-b-ce-id-search-8346.tf
- terraform-v2/keycloak-test/standard-clients/tian-testing-12-06-b-ce-id-search-8346.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tian-testing-12-06-b-ce-id-search-8346

- terraform-v2/keycloak-dev/standard-clients/assign-role-test-8347.tf
- terraform-v2/keycloak-test/standard-clients/assign-role-test-8347.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://www.assignroledev.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://www.assignroletest.com</li></ul>```
</details>
> request: add client files for assign-role-test-8347

- terraform-v2/keycloak-dev/standard-clients/tians-testing-12-09-8348.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
</details>
> request: add client files for tians-testing-12-09-8348

- terraform-v2/keycloak-dev/standard-clients/test-nk-email-8349.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for test-nk-email-8349

- terraform-v2/keycloak-dev/standard-clients/tians-testing-12-15-demo-8351.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-12-15-demo-8351.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-12-15-demo-8351.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleTest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleProd</li></ul>```
</details>
> request: add client files for tians-testing-12-15-demo-8351

- terraform-v2/keycloak-dev/standard-clients/test-gs-attempt-1-8350.tf
- terraform-v2/keycloak-prod/standard-clients/test-gs-attempt-1-8350.tf
- terraform-v2/keycloak-test/standard-clients/test-gs-attempt-1-8350.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampletest</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://exampleprod</li></ul>```
</details>
> request: add client files for test-gs-attempt-1-8350

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2056-8352.tf
> request: add client files for service-account-team-2056-8352

- terraform-v2/keycloak-dev/standard-clients/gs-test-2-8353.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for gs-test-2-8353

- terraform-v2/keycloak-dev/standard-clients/gs-test-3-8354.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for gs-test-3-8354

- terraform-v2/keycloak-dev/standard-clients/tians-testing-12-19-sandbox-login-8383.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-12-19-sandbox-login-8383.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-12-19-sandbox-login-8383.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for tians-testing-12-19-sandbox-login-8383

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2081-8385.tf
> request: add client files for service-account-team-2081-8385

- terraform-v2/keycloak-dev/standard-clients/css-api-k-6-load-testing-8417.tf
- terraform-v2/keycloak-prod/standard-clients/css-api-k-6-load-testing-8417.tf
- terraform-v2/keycloak-test/standard-clients/css-api-k-6-load-testing-8417.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for css-api-k-6-load-testing-8417

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2113-8418.tf
> request: add client files for service-account-team-2113-8418

- terraform-v2/keycloak-dev/standard-clients/kuro-tech-detail-test-8421.tf
- terraform-v2/keycloak-test/standard-clients/kuro-tech-detail-test-8421.tf
> request: add client files for kuro-tech-detail-test-8421

- terraform-v2/keycloak-dev/standard-clients/kuro-test-submitted-state-8307.tf
- terraform-v2/keycloak-test/standard-clients/kuro-test-submitted-state-8307.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://test.com</li></ul>```
</details>
> request: add client files for kuro-test-submitted-state-8307

- terraform-v2/keycloak-dev/standard-clients/test-saml-brower-login-idir-8422.tf
<details>
```<ul>✔️Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li></ul>```
</details>
> request: add client files for test-saml-brower-login-idir-8422

- terraform-v2/keycloak-dev/standard-clients/sso-open-sprint-demo-nk-8423.tf
- terraform-v2/keycloak-test/standard-clients/sso-open-sprint-demo-nk-8423.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://example</li></ul>```
</details>
> request: add client files for sso-open-sprint-demo-nk-8423

- terraform-v2/keycloak-dev/standard-clients/keycloak-example-apps-nk-8424.tf
- terraform-v2/keycloak-test/standard-clients/keycloak-example-apps-nk-8424.tf
<details>
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
```<ul>✔️Valid Redirect Urls<li>http://localhost:3000/*</li></ul>```
</details>
> request: add client files for keycloak-example-apps-nk-8424

- terraform-v2/keycloak-dev/standard-clients/test-presrvd-claims-nk-8426.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
> request: add client files for test-presrvd-claims-nk-8426

- terraform-v2/keycloak-dev/standard-clients/tians-testing-1-26-b-ce-id-and-git-hub-8427.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-1-26-b-ce-id-and-git-hub-8427.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://exampleTest</li>
</ul>
</details>
> request: add client files for tians-testing-1-26-b-ce-id-and-git-hub-8427

- terraform-v2/keycloak-dev/standard-clients/tians-testing-1-26-b-ce-id-only-8428.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-1-26-b-ce-id-only-8428.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://exampleTest</li>
</ul>
</details>
> request: add client files for tians-testing-1-26-b-ce-id-only-8428

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2115-8429.tf
> request: add client files for service-account-team-2115-8429

- terraform-v2/keycloak-dev/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-8430.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-8430.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-8430.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-1-27-keycloak-7-6-1-upgrade-8430

- terraform-v2/keycloak-dev/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-2-8431.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-2-8431.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-2-8431.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-1-27-keycloak-7-6-1-upgrade-2-8431

- terraform-v2/keycloak-dev/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-3-8432.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-3-8432.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-1-27-keycloak-7-6-1-upgrade-3-8432.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-1-27-keycloak-7-6-1-upgrade-3-8432

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2048-8433.tf
> request: add client files for service-account-team-2048-8433

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2114-8434.tf
> request: add client files for service-account-team-2114-8434

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1959-8435.tf
> request: add client files for service-account-team-1959-8435

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-draft-status-8425.tf
> request: add client files for kuro-testing-draft-status-8425

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2114-8434.tf
> request: delete client files for service-account-team-2114-8434

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2114-8436.tf
> request: add client files for service-account-team-2114-8436

- terraform-v2/keycloak-dev/standard-clients/role-mag-refreshing-issue-8437.tf
> request: add client files for role-mag-refreshing-issue-8437

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-7-service-account-8438.tf
> request: add client files for tians-testing-2-7-service-account-8438

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-7-browser-login-8439.tf
> request: add client files for tians-testing-2-7-browser-login-8439

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-7-both-8440.tf
> request: add client files for tians-testing-2-7-both-8440

- terraform-v2/keycloak-dev/standard-clients/ui-testing-my-teams-panel-8442.tf
- terraform-v2/keycloak-test/standard-clients/ui-testing-my-teams-panel-8442.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for ui-testing-my-teams-panel-8442

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1651-8443.tf
> request: add client files for service-account-team-1651-8443

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-8-refreshing-8444.tf
> request: add client files for tians-testing-2-8-refreshing-8444

- terraform-v2/keycloak-dev/standard-clients/test-client-nk-8446.tf
- terraform-v2/keycloak-test/standard-clients/test-client-nk-8446.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
> request: add client files for test-client-nk-8446

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2115-8429.tf
> request: delete client files for service-account-team-2115-8429

- terraform-v2/keycloak-dev/standard-clients/email-test-b-ce-id-8447.tf
- terraform-v2/keycloak-test/standard-clients/email-test-b-ce-id-8447.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-b-ce-id-8447

- terraform-v2/keycloak-dev/standard-clients/email-test-b-ce-id-prod-8448.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-b-ce-id-prod-8448.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-b-ce-id-prod-8448

- terraform-v2/keycloak-dev/standard-clients/email-test-b-ce-id-dev-test-prod-8449.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-b-ce-id-dev-test-prod-8449.tf
- terraform-v2/keycloak-test/standard-clients/email-test-b-ce-id-dev-test-prod-8449.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-b-ce-id-dev-test-prod-8449

- terraform-v2/keycloak-dev/standard-clients/email-test-github-dev-test-8450.tf
- terraform-v2/keycloak-test/standard-clients/email-test-github-dev-test-8450.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-github-dev-test-8450

- terraform-v2/keycloak-dev/standard-clients/email-test-github-prod-8451.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-github-prod-8451.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-github-prod-8451

- terraform-v2/keycloak-dev/standard-clients/email-test-b-ce-id-github-dev-8452.tf
- terraform-v2/keycloak-test/standard-clients/email-test-b-ce-id-github-dev-8452.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-b-ce-id-github-dev-8452

- terraform-v2/keycloak-dev/standard-clients/email-test-b-ce-id-github-prod-8453.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-b-ce-id-github-prod-8453.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-b-ce-id-github-prod-8453

- terraform-v2/keycloak-dev/standard-clients/email-test-idir-dev-test-8454.tf
- terraform-v2/keycloak-test/standard-clients/email-test-idir-dev-test-8454.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-idir-dev-test-8454

- terraform-v2/keycloak-dev/standard-clients/email-test-idir-prod-8455.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-idir-prod-8455.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-idir-prod-8455

- terraform-v2/keycloak-dev/standard-clients/email-test-idir-b-ce-id-github-prod-8456.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-idir-b-ce-id-github-prod-8456.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-idir-b-ce-id-github-prod-8456

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-13-git-hub-and-idir-8457.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-2-13-git-hub-and-idir-8457.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-2-13-git-hub-and-idir-8457

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-13-git-hub-only-8458.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-2-13-git-hub-only-8458.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-2-13-git-hub-only-8458

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-13-git-hub-only-2-8459.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-2-13-git-hub-only-2-8459.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-2-13-git-hub-only-2-8459

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2119-8482.tf
> request: add client files for service-account-team-2119-8482

- terraform-v2/keycloak-dev/standard-clients/test-svc-acct-nk-8483.tf
> request: add client files for test-svc-acct-nk-8483

- terraform-v2/keycloak-dev/standard-clients/test-both-auths-nk-8486.tf
- terraform-v2/keycloak-prod/standard-clients/test-both-auths-nk-8486.tf
- terraform-v2/keycloak-test/standard-clients/test-both-auths-nk-8486.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>
> request: add client files for test-both-auths-nk-8486

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8484.tf
> request: add client files for tians-testing-8484

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2050-8487.tf
> request: add client files for service-account-team-2050-8487

- terraform-v2/keycloak-dev/standard-clients/zorin-test-feb-24-service-account-toles-8488.tf
> request: add client files for zorin-test-feb-24-service-account-toles-8488

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-24-b-ce-id-dev-8489.tf
> request: add client files for tians-testing-2-24-b-ce-id-dev-8489

- terraform-v2/keycloak-dev/standard-clients/tians-testing-2-27-testing-with-team-member-8491.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-2-27-testing-with-team-member-8491.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-2-27-testing-with-team-member-8491

- terraform-v2/keycloak-dev/standard-clients/email-test-no-team-8515.tf
- terraform-v2/keycloak-prod/standard-clients/email-test-no-team-8515.tf
- terraform-v2/keycloak-test/standard-clients/email-test-no-team-8515.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for email-test-no-team-8515

- terraform-v2/keycloak-dev/standard-clients/test-service-account-8516.tf
- terraform-v2/keycloak-test/standard-clients/test-service-account-8516.tf
> request: add client files for test-service-account-8516

- terraform-v2/keycloak-dev/standard-clients/test-service-account-browser-8517.tf
- terraform-v2/keycloak-prod/standard-clients/test-service-account-browser-8517.tf
- terraform-v2/keycloak-test/standard-clients/test-service-account-browser-8517.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for test-service-account-browser-8517

- terraform-v2/keycloak-dev/standard-clients/march-7-test-loki-dashboard-8519.tf
- terraform-v2/keycloak-prod/standard-clients/march-7-test-loki-dashboard-8519.tf
- terraform-v2/keycloak-test/standard-clients/march-7-test-loki-dashboard-8519.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for march-7-test-loki-dashboard-8519

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-8485.tf
> request: add client files for kuro-testing-8485

- terraform-v2/keycloak-dev/standard-clients/march-14-saml-roles-8548.tf
> request: add client files for march-14-saml-roles-8548

- terraform-v2/keycloak-dev/standard-clients/tians-testing-3-21-azure-idir-only-8554.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-3-21-azure-idir-only-8554.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-3-21-azure-idir-only-8554.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://exampleTest</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://exampleProd</li>
</ul>
</details>
> request: add client files for tians-testing-3-21-azure-idir-only-8554

- terraform-v2/keycloak-dev/standard-clients/test-saml-logout-nk-1-8555.tf
- terraform-v2/keycloak-prod/standard-clients/test-saml-logout-nk-1-8555.tf
- terraform-v2/keycloak-test/standard-clients/test-saml-logout-nk-1-8555.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://example/*</li>
</ul>
</details>
> request: add client files for test-saml-logout-nk-1-8555

- terraform-v2/keycloak-dev/standard-clients/tians-testing-3-23-saml-8556.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-3-23-saml-8556.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-3-23-saml-8556.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-3-23-saml-8556

- terraform-v2/keycloak-dev/standard-clients/test-saml-logout-nk-2-8558.tf
- terraform-v2/keycloak-prod/standard-clients/test-saml-logout-nk-2-8558.tf
- terraform-v2/keycloak-test/standard-clients/test-saml-logout-nk-2-8558.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for test-saml-logout-nk-2-8558

- terraform-v2/keycloak-dev/standard-clients/kuro-testing-8549.tf
> request: add client files for kuro-testing-8549

- terraform-v2/keycloak-dev/standard-clients/test-migration-nk-1-8559.tf
- terraform-v2/keycloak-prod/standard-clients/test-migration-nk-1-8559.tf
- terraform-v2/keycloak-test/standard-clients/test-migration-nk-1-8559.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/*</li>
</ul>
</details>
> request: add client files for test-migration-nk-1-8559

- terraform-v2/keycloak-dev/standard-clients/test-migration-nk-2-8560.tf
- terraform-v2/keycloak-prod/standard-clients/test-migration-nk-2-8560.tf
- terraform-v2/keycloak-test/standard-clients/test-migration-nk-2-8560.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://example/*</li>
</ul>
</details>
> request: add client files for test-migration-nk-2-8560

- terraform-v2/keycloak-dev/standard-clients/march-29-8562.tf
> request: add client files for march-29-8562

- terraform-v2/keycloak-dev/standard-clients/march-30-confidential-idir-8563.tf
> request: add client files for march-30-confidential-idir-8563

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2146-8564.tf
> request: add client files for service-account-team-2146-8564

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2056-8352.tf
> request: delete client files for service-account-team-2056-8352

- terraform-v2/keycloak-dev/standard-clients/test-sandbox-confidential-idir-8566.tf
- terraform-v2/keycloak-test/standard-clients/test-sandbox-confidential-idir-8566.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/master/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.loginproxy.gov.bc.ca/auth/realms/master/*</li>
</ul>
</details>
> request: add client files for test-sandbox-confidential-idir-8566

- terraform-v2/keycloak-dev/standard-clients/create-role-demo-8581.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://github.com/bcgov/sso-keycloak</li>
</ul>
</details>
> request: add client files for create-role-demo-8581

- terraform-v2/keycloak-dev/standard-clients/check-assign-service-account-to-role-8585.tf
- terraform-v2/keycloak-test/standard-clients/check-assign-service-account-to-role-8585.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000/</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000/</li>
</ul>
</details>
> request: add client files for check-assign-service-account-to-role-8585

- terraform-v2/keycloak-dev/standard-clients/test-april-17-2023-8586.tf
> request: add client files for test-april-17-2023-8586

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-18-role-8587.tf
> request: add client files for tians-testing-4-18-role-8587

- terraform-v2/keycloak-dev/standard-clients/test-saml-custm-client-id-1-8590.tf
> request: add client files for test-saml-custm-client-id-1-8590

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-24-table-8591.tf
> request: add client files for tians-testing-4-24-table-8591

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-24-saml-bceid-8593.tf
> request: add client files for tians-testing-4-24-saml-bceid-8593

- terraform-v2/keycloak-dev/standard-clients/test-oidc-int-nk-1-8595.tf
> request: add client files for test-oidc-int-nk-1-8595

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-27-saml-idir-8597.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-4-27-saml-idir-8597.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-4-27-saml-idir-8597.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-4-27-saml-idir-8597

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-27-multiple-id-ps-8598.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-4-27-multiple-id-ps-8598.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-4-27-multiple-id-ps-8598.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-4-27-multiple-id-ps-8598

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-27-saml-b-ce-id-8599.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-4-27-saml-b-ce-id-8599.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-4-27-saml-b-ce-id-8599.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-4-27-saml-b-ce-id-8599

- terraform-v2/keycloak-dev/standard-clients/tians-testing-sso-8600.tf
> request: add client files for tians-testing-sso-8600

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-27-saml-git-hub-8601.tf
> request: add client files for tians-testing-4-27-saml-git-hub-8601

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-27-saml-b-ce-id-update-8599.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-4-27-saml-b-ce-id-update-8599.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-4-27-saml-b-ce-id-update-8599.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-4-27-saml-b-ce-id-update-8599

- terraform-v2/keycloak-dev/standard-clients/tians-testing-4-28-saml-idir-fixed-project-name-8602.tf
> request: add client files for tians-testing-4-28-saml-idir-fixed-project-name-8602

- terraform-v2/keycloak-dev/standard-clients/may-1-saml-test-8604.tf
> request: add client files for may-1-saml-test-8604

- terraform-v2/keycloak-dev/standard-clients/may-1-b-ce-id-8647.tf
> request: add client files for may-1-b-ce-id-8647

- terraform-v2/keycloak-dev/standard-clients/service-account-test-8687.tf
- terraform-v2/keycloak-test/standard-clients/service-account-test-8687.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.com</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.com</li>
</ul>
</details>
> request: add client files for service-account-test-8687

- terraform-v2/keycloak-dev/standard-clients/may-5-test-8688.tf
> request: add client files for may-5-test-8688

- terraform-v2/keycloak-dev/standard-clients/jon-test-of-client-id-8689.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/oauth/cognito</li>
</ul>
</details>
> request: add client files for jon-test-of-client-id-8689

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-3-service-account-8691.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-5-3-service-account-8691.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-5-3-service-account-8691.tf
> request: add client files for tians-testing-5-3-service-account-8691

- terraform-v2/keycloak-dev/standard-clients/jon-test-2-oidc-to-oidc-8692.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/oauth/cognito</li>
</ul>
</details>
> request: add client files for jon-test-2-oidc-to-oidc-8692

- terraform-v2/keycloak-dev/standard-clients/may-4-saml-zorin-c-8690.tf
> request: add client files for may-4-saml-zorin-c-8690

- terraform-v2/keycloak-dev/standard-clients/jon-may-4-saml-8694.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/oauth/cognito</li>
</ul>
</details>
> request: add client files for jon-may-4-saml-8694

- terraform-v2/keycloak-dev/standard-clients/may-1-b-ce-id-update-existing-8647.tf
> request: add client files for may-1-b-ce-id-update-existing-8647

- terraform-v2/keycloak-dev/standard-clients/changed-name-may-4-8647.tf
> request: add client files for changed-name-may-4-8647

- terraform-v2/keycloak-dev/standard-clients/may-4-saml-test-zs-9-pm-8592.tf
> request: add client files for may-4-saml-test-zs-9-pm-8592

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-4-sandbox-test-name-updated-8696.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-5-4-sandbox-test-name-updated-8696.tf
> request: add client files for tians-testing-5-4-sandbox-test-name-updated-8696

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-5-after-name-blocker-8697.tf
> request: add client files for tians-testing-5-5-after-name-blocker-8697

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-5-saml-8698.tf
> request: add client files for tians-testing-5-5-saml-8698

- terraform-v2/keycloak-dev/standard-clients/browser-service-account-8700.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://test.com</li>
</ul>
</details>
> request: add client files for browser-service-account-8700

- terraform-v2/keycloak-dev/standard-clients/march-7-test-loki-dashboard-edited-may-15-8519.tf
- terraform-v2/keycloak-prod/standard-clients/march-7-test-loki-dashboard-edited-may-15-8519.tf
- terraform-v2/keycloak-test/standard-clients/march-7-test-loki-dashboard-edited-may-15-8519.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for march-7-test-loki-dashboard-edited-may-15-8519

- terraform-v2/keycloak-dev/standard-clients/march-29-public-idir-edited-may-15-8562.tf
> request: add client files for march-29-public-idir-edited-may-15-8562

- terraform-v2/keycloak-dev/standard-clients/march-30-confidential-idir-edited-may-15-8563.tf
> request: add client files for march-30-confidential-idir-edited-may-15-8563

- terraform-v2/keycloak-dev/standard-clients/may-15-saml-test-8702.tf
> request: add client files for may-15-saml-test-8702

- terraform-v2/keycloak-dev/standard-clients/test-tf-file-fix-1-nk-8703.tf
> request: add client files for test-tf-file-fix-1-nk-8703

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-16-browser-8704.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-5-16-browser-8704.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-5-16-browser-8704.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-5-16-browser-8704

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-16-saml-8705.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-5-16-saml-8705.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-5-16-saml-8705.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-5-16-saml-8705

- terraform-v2/keycloak-dev/standard-clients/test-proj-name-update-nk-1-8706.tf
> request: add client files for test-proj-name-update-nk-1-8706

- terraform-v2/keycloak-dev/standard-clients/kuro-email-test-integ-8707.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://example.com</li>
</ul>
</details>
> request: add client files for kuro-email-test-integ-8707

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-17-email-update-8708.tf
> request: add client files for tians-testing-5-17-email-update-8708

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1986-8227.tf
> request: delete client files for service-account-for-team-1986-8227

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1986-8709.tf
> request: add client files for service-account-for-team-1986-8709

- terraform-v2/keycloak-dev/standard-clients/may-1-b-ce-id-8647.tf
- terraform-v2/keycloak-prod/standard-clients/may-1-b-ce-id-8647.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for may-23-updated-name-non-p-rod-to-prod-8647

- terraform-v2/keycloak-dev/standard-clients/tians-testing-5-24-leaving-team-8711.tf
> request: add client files for tians-testing-5-24-leaving-team-8711

- terraform-v2/keycloak-dev/standard-clients/test-cache-tf-nk-1-8714.tf
> request: add client files for test-cache-tf-nk-1-8714

- terraform-v2/keycloak-dev/standard-clients/test-cache-tf-nk-2-8715.tf
> request: add client files for test-cache-tf-nk-2-8715

- terraform-v2/keycloak-dev/standard-clients/kuro-test-integ-8717.tf
> request: add client files for kuro-test-integ-8717

- terraform-v2/keycloak-dev/standard-clients/kuro-team-id-uses-team-issue-8719.tf
> request: add client files for kuro-team-id-uses-team-issue-8719

- terraform-v2/keycloak-dev/standard-clients/test-2202-8720.tf
- terraform-v2/keycloak-test/standard-clients/test-2202-8720.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost.com</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost.com</li>
</ul>
</details>
> request: add client files for test-2202-8720

- terraform-v2/keycloak-dev/standard-clients/june-2023-b-ce-id-basic-conf-8721.tf
- terraform-v2/keycloak-prod/standard-clients/june-2023-b-ce-id-basic-conf-8721.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li><li>https://sso-keycloak-e4ca1d-dev.apps.gold.devops.gov.bc.ca/auth/realms/test-realm/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li><li>https://sso-keycloak-e4ca1d-prod.apps.gold.devops.gov.bc.ca/auth/realms/test-realm/*</li>
</ul>
</details>
> request: add client files for june-2023-b-ce-id-basic-conf-8721

- terraform-v2/keycloak-dev/standard-clients/tians-testing-6-23-multiple-idps-8722.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-6-23-multiple-idps-8722.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-6-23-multiple-idps-8722.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-6-23-multiple-idps-8722

- terraform-v2/keycloak-dev/standard-clients/kuro-bceid-idp-removal-test-8723.tf
- terraform-v2/keycloak-prod/standard-clients/kuro-bceid-idp-removal-test-8723.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000</li>
</ul>
</details>
> request: add client files for kuro-bceid-idp-removal-test-8723

- terraform-v2/keycloak-dev/standard-clients/github-bc-gov-june-2023-8726.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li><li>https://localhost:3000/*</li><li>https://localhost:3500/*</li>
</ul>
</details>
> request: add client files for github-bc-gov-june-2023-8726

- terraform-v2/keycloak-dev/standard-clients/git-hub-public-june-2023-8727.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li><li>https://localhost:3000/*</li><li>https://localhost:3500/*</li>
</ul>
</details>
> request: add client files for git-hub-public-june-2023-8727

- terraform-v2/keycloak-dev/standard-clients/azure-idir-june-2023-8728.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/*</li><li>https://localhost:3000/*</li><li>https://localhost:3500/*</li>
</ul>
</details>
> request: add client files for azure-idir-june-2023-8728

- terraform-v2/keycloak-dev/standard-clients/azure-idir-conf-june-2023-8729.tf
- terraform-v2/keycloak-prod/standard-clients/azure-idir-conf-june-2023-8729.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li><li>https://localhost:3000/*</li><li>https://localhost:3500/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li><li>https://localhost:3000/*</li><li>https://localhost:3500/*</li>
</ul>
</details>
> request: add client files for azure-idir-conf-june-2023-8729

- terraform-v2/keycloak-dev/standard-clients/git-hub-bc-gov-conf-juen-2023-8730.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li><li>https://localhost:3000/*</li>
</ul>
</details>
> request: add client files for git-hub-bc-gov-conf-juen-2023-8730

- terraform-v2/keycloak-dev/standard-clients/github-public-conf-8731.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/keycloak-example-apps/</li><li>https://localhost:3000/*</li>
</ul>
</details>
> request: add client files for github-public-conf-8731

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2215-8732.tf
> request: add client files for service-account-for-team-2215-8732

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2215-8732.tf
> request: delete client files for service-account-for-team-2215-8732

- terraform-v2/keycloak-dev/standard-clients/tians-testing-6-27-8734.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-6-27-8734.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-6-27-8734

- terraform-v2/keycloak-dev/standard-clients/tians-testing-6-29-8737.tf
> request: add client files for tians-testing-6-29-8737

- terraform-v2/keycloak-dev/standard-clients/kuro-test-team-issue-8738.tf
- terraform-v2/keycloak-prod/standard-clients/kuro-test-team-issue-8738.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for kuro-test-team-issue-8738

- terraform-v2/keycloak-dev/standard-clients/tians-testing-6-29-b-ce-id-remove-after-prod-approv-8739.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-6-29-b-ce-id-remove-after-prod-approv-8739.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-6-29-b-ce-id-remove-after-prod-approv-8739.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-6-29-b-ce-id-remove-after-prod-approv-8739

- terraform-v2/keycloak-dev/standard-clients/kuro-test-teamid-issue-02-8740.tf
> request: add client files for kuro-test-teamid-issue-02-8740

- terraform-v2/keycloak-dev/standard-clients/kuro-test-team-id-issue-2222-8741.tf
> request: add client files for kuro-test-team-id-issue-2222-8741

- terraform-v2/keycloak-dev/standard-clients/kuro-test-team-id-444-8743.tf
> request: add client files for kuro-test-team-id-444-8743

- terraform-v2/keycloak-dev/standard-clients/kuro-test-integ-8744.tf
> request: add client files for kuro-test-integ-8744

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8745.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8745.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-8745

- terraform-v2/keycloak-dev/standard-clients/kuro-test-integ-8746.tf
> request: add client files for kuro-test-integ-8746

- terraform-v2/keycloak-dev/standard-clients/kuro-test-team-id-issue-33-8742.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000</li>
</ul>
</details>
> request: add client files for kuro-test-team-id-issue-33-8742

- terraform-v2/keycloak-dev/standard-clients/tians-testing-6-30-team-id-8747.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-6-30-team-id-8747.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-6-30-team-id-8747

- terraform-v2/keycloak-dev/standard-clients/tians-testing-7-4-test-client-1-8755.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-7-4-test-client-1-8755.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-7-4-test-client-1-8755

- terraform-v2/keycloak-dev/standard-clients/tians-testing-7-4-test-client-2-8756.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-7-4-test-client-2-8756.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-7-4-test-client-2-8756

- terraform-v2/keycloak-dev/standard-clients/business-public-june-2023-8761.tf
- terraform-v2/keycloak-test/standard-clients/business-public-june-2023-8761.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000/*</li><li>http://localhost:3000/*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:1000/*</li><li>http://localhost:3000/*</li><li>https://bcgov.github.io/keycloak-example-apps/</li>
</ul>
</details>
> request: add client files for business-public-june-2023-8761

- terraform-v2/keycloak-dev/standard-clients/all-idps-public-june-2023-8763.tf
- terraform-v2/keycloak-test/standard-clients/all-idps-public-june-2023-8763.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for all-idps-public-june-2023-8763

- terraform-v2/keycloak-dev/standard-clients/all-bc-id-ps-public-june-2023-8764.tf
- terraform-v2/keycloak-test/standard-clients/all-bc-id-ps-public-june-2023-8764.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for all-bc-id-ps-public-june-2023-8764

- terraform-v2/keycloak-dev/standard-clients/non-siteminder-conf-june-2023-8765.tf
- terraform-v2/keycloak-test/standard-clients/non-siteminder-conf-june-2023-8765.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for non-siteminder-conf-june-2023-8765

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1990-8766.tf
> request: add client files for service-account-for-team-1990-8766

- terraform-v2/keycloak-dev/standard-clients/azure-idir-public-july-2023-8767.tf
- terraform-v2/keycloak-prod/standard-clients/azure-idir-public-july-2023-8767.tf
- terraform-v2/keycloak-test/standard-clients/azure-idir-public-july-2023-8767.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/</li>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/</li>
</ul>
</details>
> request: add client files for azure-idir-public-july-2023-8767

- terraform-v2/keycloak-dev/standard-clients/id-ps-no-idir-public-july-2023-8768.tf
- terraform-v2/keycloak-prod/standard-clients/id-ps-no-idir-public-july-2023-8768.tf
- terraform-v2/keycloak-test/standard-clients/id-ps-no-idir-public-july-2023-8768.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/</li>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li><li>http://localhost:3500/*</li><li>https://bcgov.github.io/keycloak-example-apps/</li>
</ul>
</details>
> request: add client files for id-ps-no-idir-public-july-2023-8768

- terraform-v2/keycloak-dev/standard-clients/kuro-team-id-testing-8769.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000</li>
</ul>
</details>
> request: add client files for kuro-team-id-testing-8769

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1555-8771.tf
> request: add client files for service-account-for-team-1555-8771

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2179-8774.tf
> request: add client files for service-account-for-team-2179-8774

- terraform-v2/keycloak-dev/standard-clients/does-batch-trigger-july-27-8775.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/oauth/cognito</li>
</ul>
</details>
> request: add client files for does-batch-trigger-july-27-8775

- terraform-v2/keycloak-dev/standard-clients/all-siteminder-id-ps-conf-july-2023-8778.tf
- terraform-v2/keycloak-test/standard-clients/all-siteminder-id-ps-conf-july-2023-8778.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-multiple-nonsiteminder-2/*</li><li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-multiple-nonsiteminder/*</li>
</ul>
</details>
> request: add client files for all-siteminder-id-ps-conf-july-2023-8778

- terraform-v2/keycloak-dev/standard-clients/all-idps-conf-july-2023-8777.tf
- terraform-v2/keycloak-test/standard-clients/all-idps-conf-july-2023-8777.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-multiple-nonsiteminder-2/*</li>
</ul>
</details>
> request: add client files for all-idps-conf-july-2023-8777

- terraform-v2/keycloak-dev/standard-clients/all-non-siteminder-id-ps-conf-july-2023-8779.tf
- terraform-v2/keycloak-test/standard-clients/all-non-siteminder-id-ps-conf-july-2023-8779.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-multiple-nonsiteminder-2/*</li><li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-multiple-nonsiteminder/*</li>
</ul>
</details>
> request: add client files for all-non-siteminder-id-ps-conf-july-2023-8779

- terraform-v2/keycloak-dev/standard-clients/azure-idir-conf-july-2023-8776.tf
- terraform-v2/keycloak-test/standard-clients/azure-idir-conf-july-2023-8776.tf
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-single-nonsiteminder-2/*</li><li>https://sso-keycloak-e4ca1d-test.apps.gold.devops.gov.bc.ca/auth/realms/test-realm-single-nonsiteminder/*</li>
</ul>
</details>
> request: add client files for azure-idir-conf-july-2023-8776

- terraform-v2/keycloak-dev/standard-clients/all-non-idir-id-ps-public-aug-2023-8812.tf
- terraform-v2/keycloak-prod/standard-clients/all-non-idir-id-ps-public-aug-2023-8812.tf
- terraform-v2/keycloak-test/standard-clients/all-non-idir-id-ps-public-aug-2023-8812.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for all-non-idir-id-ps-public-aug-2023-8812

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-3-composite-role-behavior-8813.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-8-3-composite-role-behavior-8813.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-3-composite-role-behavior-8813.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-8-3-composite-role-behavior-8813

- terraform-v2/keycloak-dev/standard-clients/test-email-notifs-int-nk-8814.tf
> request: add client files for test-email-notifs-int-nk-8814

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-02-8815.tf
> request: add client files for test-int-nk-02-8815

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-03-8816.tf
- terraform-v2/keycloak-prod/standard-clients/test-int-nk-03-8816.tf
- terraform-v2/keycloak-test/standard-clients/test-int-nk-03-8816.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://example.com/*</li>
</ul>
</details>
> request: add client files for test-int-nk-03-8816

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-10-email-notification-8817.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-8-10-email-notification-8817.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-10-email-notification-8817.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-8-10-email-notification-8817

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-14-add-remove-team-8847.tf
> request: add client files for tians-testing-8-14-add-remove-team-8847

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-04-8848.tf
> request: add client files for test-int-nk-04-8848

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-05-8849.tf
> request: add client files for test-int-nk-05-8849

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-06-8850.tf
> request: add client files for test-int-nk-06-8850

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-08-8852.tf
> request: add client files for test-int-nk-08-8852

- terraform-v2/keycloak-dev/standard-clients/test-int-nk-07-8851.tf
> request: add client files for test-int-nk-07-8851

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-16-add-remove-team-8853.tf
> request: add client files for tians-testing-8-16-add-remove-team-8853

- terraform-v2/keycloak-dev/standard-clients/test-kc-upg-nk-01-8855.tf
- terraform-v2/keycloak-prod/standard-clients/test-kc-upg-nk-01-8855.tf
- terraform-v2/keycloak-test/standard-clients/test-kc-upg-nk-01-8855.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://example.com/*</li>
</ul>
</details>
> request: add client files for test-kc-upg-nk-01-8855

- terraform-v2/keycloak-dev/standard-clients/created-by-training-account-aug-21-8760.tf
> request: add client files for created-by-training-account-aug-21-8760

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-28-keycloak-upgrade-multiple-idp-8856.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-28-keycloak-upgrade-multiple-idp-8856.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-8-28-keycloak-upgrade-multiple-idp-8856

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-28-keycloak-upgrade-single-idp-8857.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8-28-keycloak-upgrade-single-idp-8857.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-8-28-keycloak-upgrade-single-idp-8857

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8-28-saml-8858.tf
> request: add client files for tians-testing-8-28-saml-8858

- terraform-v2/keycloak-dev/standard-clients/test-1-8859.tf
> request: add client files for test-1-8859

- terraform-v2/keycloak-dev/standard-clients/test-project-8860.tf
> request: add client files for test-project-8860

- terraform-v2/keycloak-dev/standard-clients/test-2-8861.tf
> request: add client files for test-2-8861

- terraform-v2/keycloak-dev/standard-clients/j-lkj-lkj-l-8863.tf
> request: add client files for j-lkj-lkj-l-8863

- terraform-v2/keycloak-dev/standard-clients/balanced-national-flexibility-engineer-collaborati-8866.tf
> request: add client files for balanced-national-flexibility-engineer-collaborati-8866

- terraform-v2/keycloak-dev/standard-clients/cross-platform-static-open-architecture-incubate-f-8867.tf
> request: add client files for cross-platform-static-open-architecture-incubate-f-8867

- terraform-v2/keycloak-dev/standard-clients/digitized-24-7-solution-deliver-back-end-e-busines-8869.tf
> request: add client files for digitized-24-7-solution-deliver-back-end-e-busines-8869

- terraform-v2/keycloak-dev/standard-clients/quality-focused-scalable-matrix-8870.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://circular-recognition.biz</li>
</ul>
</details>
> request: add client files for quality-focused-scalable-matrix-8870

- terraform-v2/keycloak-dev/standard-clients/pre-emptive-bandwidth-monitored-function-iterate-s-8865.tf
> request: add client files for pre-emptive-bandwidth-monitored-function-iterate-s-8865

- terraform-v2/keycloak-dev/standard-clients/extended-full-range-throughput-8871.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://abandoned-reality.name</li>
</ul>
</details>
> request: add client files for extended-full-range-throughput-8871

- terraform-v2/keycloak-dev/standard-clients/organic-needs-based-protocol-8872.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://elated-origin.com</li>
</ul>
</details>
> request: add client files for organic-needs-based-protocol-8872

- terraform-v2/keycloak-dev/standard-clients/enterprise-wide-bifurcated-archive-8873.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://flawed-creature.com</li>
</ul>
</details>
> request: add client files for enterprise-wide-bifurcated-archive-8873

- terraform-v2/keycloak-dev/standard-clients/up-sized-static-structure-8874.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://sociable-refreshments.name</li>
</ul>
</details>
> request: add client files for up-sized-static-structure-8874

- terraform-v2/keycloak-dev/standard-clients/upgradable-client-server-attitude-8875.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://true-lad.name</li>
</ul>
</details>
> request: add client files for upgradable-client-server-attitude-8875

- terraform-v2/keycloak-dev/standard-clients/customer-focused-client-server-moderator-8877.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://growing-spirituality.com</li>
</ul>
</details>
> request: add client files for customer-focused-client-server-moderator-8877

- terraform-v2/keycloak-dev/standard-clients/devolved-leading-edge-function-8878.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://minty-terminal.info</li>
</ul>
</details>
> request: add client files for devolved-leading-edge-function-8878

- terraform-v2/keycloak-dev/standard-clients/automated-bi-directional-process-improvement-8882.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://bulky-compost.biz</li>
</ul>
</details>
> request: add client files for automated-bi-directional-process-improvement-8882

- terraform-v2/keycloak-dev/standard-clients/persevering-clear-thinking-moderator-8883.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://satisfied-proprietor.name</li>
</ul>
</details>
> request: add client files for persevering-clear-thinking-moderator-8883

- terraform-v2/keycloak-dev/standard-clients/multi-tiered-responsive-moderator-8884.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://webbed-proposition.com</li>
</ul>
</details>
> request: add client files for multi-tiered-responsive-moderator-8884

- terraform-v2/keycloak-dev/standard-clients/re-engineered-mission-critical-conglomeration-8885.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://subdued-piano.biz</li>
</ul>
</details>
> request: add client files for re-engineered-mission-critical-conglomeration-8885

- terraform-v2/keycloak-dev/standard-clients/optional-even-keeled-system-engine-8886.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://wan-online.info</li>
</ul>
</details>
> request: add client files for optional-even-keeled-system-engine-8886

- terraform-v2/keycloak-dev/standard-clients/realigned-holistic-contingency-8887.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://altruistic-bowler.name</li>
</ul>
</details>
> request: add client files for realigned-holistic-contingency-8887

- terraform-v2/keycloak-dev/standard-clients/right-sized-homogeneous-time-frame-8888.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://frightened-mother.info</li>
</ul>
</details>
> request: add client files for right-sized-homogeneous-time-frame-8888

- terraform-v2/keycloak-dev/standard-clients/multi-layered-radical-encoding-8889.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://ornate-calculus.com</li>
</ul>
</details>
> request: add client files for multi-layered-radical-encoding-8889

- terraform-v2/keycloak-dev/standard-clients/enterprise-wide-dedicated-throughput-8890.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://juicy-expertise.com</li>
</ul>
</details>
> request: add client files for enterprise-wide-dedicated-throughput-8890

- terraform-v2/keycloak-dev/standard-clients/configurable-bandwidth-monitored-encryption-8891.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://worldly-cyst.net</li>
</ul>
</details>
> request: add client files for configurable-bandwidth-monitored-encryption-8891

- terraform-v2/keycloak-dev/standard-clients/test-1-8892.tf
> request: add client files for test-1-8892

- terraform-v2/keycloak-dev/standard-clients/tians-testing-8893.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-8893.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-8893

- terraform-v2/keycloak-dev/standard-clients/fundamental-local-projection-8898.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://humming-background.info</li>
</ul>
</details>
> request: add client files for fundamental-local-projection-8898

- terraform-v2/keycloak-dev/standard-clients/nextjs-service-account-demo-8900.tf
> request: add client files for nextjs-service-account-demo-8900

- terraform-v2/keycloak-dev/standard-clients/test-8901.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://experienced-matter.net</li>
</ul>
</details>
> request: add client files for test-8901

- terraform-v2/keycloak-dev/standard-clients/focused-3-rd-generation-throughput-8902.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://kind-leather.com</li>
</ul>
</details>
> request: add client files for focused-3rd-generation-throughput-8902

- terraform-v2/keycloak-dev/standard-clients/synergized-methodical-methodology-8903.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://torn-lover.biz</li>
</ul>
</details>
> request: add client files for synergized-methodical-methodology-8903

- terraform-v2/keycloak-dev/standard-clients/adaptive-zero-tolerance-benchmark-8904.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://spotted-meteor.org</li>
</ul>
</details>
> request: add client files for adaptive-zero-tolerance-benchmark-8904

- terraform-v2/keycloak-dev/standard-clients/quality-focused-system-worthy-installation-8906.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://damp-permit.name</li>
</ul>
</details>
> request: add client files for quality-focused-system-worthy-installation-8906

- terraform-v2/keycloak-dev/standard-clients/fully-configurable-interactive-budgetary-managemen-8907.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://honest-innovation.org</li>
</ul>
</details>
> request: add client files for fully-configurable-interactive-budgetary-managemen-8907

- terraform-v2/keycloak-dev/standard-clients/inverse-systemic-collaboration-8908.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://murky-stem.com</li>
</ul>
</details>
> request: add client files for inverse-systemic-collaboration-8908

- terraform-v2/keycloak-dev/standard-clients/innovative-holistic-task-force-8909.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://sympathetic-dock.com</li>
</ul>
</details>
> request: add client files for innovative-holistic-task-force-8909

- terraform-v2/keycloak-dev/standard-clients/de-engineered-national-open-architecture-8910.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://familiar-wharf.net</li>
</ul>
</details>
> request: add client files for de-engineered-national-open-architecture-8910

- terraform-v2/keycloak-dev/standard-clients/optimized-stable-extranet-8911.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://keen-cloud.com</li>
</ul>
</details>
> request: add client files for optimized-stable-extranet-8911

- terraform-v2/keycloak-dev/standard-clients/realigned-optimal-help-desk-8913.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://nimble-reporting.com</li>
</ul>
</details>
> request: add client files for realigned-optimal-help-desk-8913

- terraform-v2/keycloak-dev/standard-clients/balanced-discrete-internet-solution-8914.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://dizzy-anybody.net</li>
</ul>
</details>
> request: add client files for balanced-discrete-internet-solution-8914

- terraform-v2/keycloak-dev/standard-clients/universal-fault-tolerant-knowledge-user-8915.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://well-groomed-revitalisation.biz</li>
</ul>
</details>
> request: add client files for universal-fault-tolerant-knowledge-user-8915

- terraform-v2/keycloak-dev/standard-clients/profound-high-level-matrices-8916.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://gregarious-accelerator.net</li>
</ul>
</details>
> request: add client files for profound-high-level-matrices-8916

- terraform-v2/keycloak-dev/standard-clients/face-to-face-optimal-functionalities-8917.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://handsome-wharf.org</li>
</ul>
</details>
> request: add client files for face-to-face-optimal-functionalities-8917

- terraform-v2/keycloak-dev/standard-clients/enhanced-bifurcated-initiative-8918.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://deficient-age.com</li>
</ul>
</details>
> request: add client files for enhanced-bifurcated-initiative-8918

- terraform-v2/keycloak-dev/standard-clients/fundamental-human-resource-forecast-8919.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://tired-triumph.net</li>
</ul>
</details>
> request: add client files for fundamental-human-resource-forecast-8919

- terraform-v2/keycloak-dev/standard-clients/pre-emptive-24-hour-framework-8920.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://massive-quality.com</li>
</ul>
</details>
> request: add client files for pre-emptive-24-hour-framework-8920

- terraform-v2/keycloak-dev/standard-clients/multi-layered-radical-data-warehouse-8921.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://pastel-steak.net</li>
</ul>
</details>
> request: add client files for multi-layered-radical-data-warehouse-8921

- terraform-v2/keycloak-dev/standard-clients/visionary-even-keeled-focus-group-8922.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://regal-room.com</li>
</ul>
</details>
> request: add client files for visionary-even-keeled-focus-group-8922

- terraform-v2/keycloak-dev/standard-clients/cloned-heuristic-array-8923.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://little-zither.info</li>
</ul>
</details>
> request: add client files for cloned-heuristic-array-8923

- terraform-v2/keycloak-dev/standard-clients/ergonomic-upward-trending-model-8924.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://elated-spatula.info</li>
</ul>
</details>
> request: add client files for ergonomic-upward-trending-model-8924

- terraform-v2/keycloak-dev/standard-clients/operative-methodical-framework-8925.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://animated-snowboarding.org</li>
</ul>
</details>
> request: add client files for operative-methodical-framework-8925

- terraform-v2/keycloak-dev/standard-clients/managed-context-sensitive-frame-8926.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://giving-shipper.com</li>
</ul>
</details>
> request: add client files for managed-context-sensitive-frame-8926

- terraform-v2/keycloak-dev/standard-clients/horizontal-asynchronous-emulation-8927.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://sarcastic-dart.org</li>
</ul>
</details>
> request: add client files for horizontal-asynchronous-emulation-8927

- terraform-v2/keycloak-dev/standard-clients/face-to-face-6-th-generation-customer-loyalty-8928.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://lonely-pocket.org</li>
</ul>
</details>
> request: add client files for face-to-face-6th-generation-customer-loyalty-8928

- terraform-v2/keycloak-dev/standard-clients/face-to-face-non-volatile-policy-8929.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://luminous-domination.info</li>
</ul>
</details>
> request: add client files for face-to-face-non-volatile-policy-8929

- terraform-v2/keycloak-dev/standard-clients/organic-client-server-methodology-8931.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://coarse-negligee.name</li>
</ul>
</details>
> request: add client files for organic-client-server-methodology-8931

- terraform-v2/keycloak-dev/standard-clients/up-sized-intermediate-implementation-8932.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://tattered-bureau.biz</li>
</ul>
</details>
> request: add client files for up-sized-intermediate-implementation-8932

- terraform-v2/keycloak-dev/standard-clients/up-sized-foreground-core-8933.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://instructive-ecclesia.com</li>
</ul>
</details>
> request: add client files for up-sized-foreground-core-8933

- terraform-v2/keycloak-dev/standard-clients/ergonomic-directional-concept-8934.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://quirky-bell.net</li>
</ul>
</details>
> request: add client files for ergonomic-directional-concept-8934

- terraform-v2/keycloak-dev/standard-clients/upgradable-tangible-graphical-user-interface-8935.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://utter-bathhouse.org</li>
</ul>
</details>
> request: add client files for upgradable-tangible-graphical-user-interface-8935

- terraform-v2/keycloak-dev/standard-clients/advanced-hybrid-conglomeration-8936.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://impure-whisker.com</li>
</ul>
</details>
> request: add client files for advanced-hybrid-conglomeration-8936

- terraform-v2/keycloak-dev/standard-clients/assimilated-coherent-algorithm-8937.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://guilty-dignity.name</li>
</ul>
</details>
> request: add client files for assimilated-coherent-algorithm-8937

- terraform-v2/keycloak-dev/standard-clients/visionary-attitude-oriented-model-8938.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://jaded-leopard.biz</li>
</ul>
</details>
> request: add client files for visionary-attitude-oriented-model-8938

- terraform-v2/keycloak-dev/standard-clients/inverse-heuristic-database-8939.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://mean-cross.name</li>
</ul>
</details>
> request: add client files for inverse-heuristic-database-8939

- terraform-v2/keycloak-dev/standard-clients/persistent-homogeneous-frame-8940.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://vicious-gavel.biz</li>
</ul>
</details>
> request: add client files for persistent-homogeneous-frame-8940

- terraform-v2/keycloak-dev/standard-clients/reactive-regional-superstructure-8941.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://sandy-need.net</li>
</ul>
</details>
> request: add client files for reactive-regional-superstructure-8941

- terraform-v2/keycloak-dev/standard-clients/function-based-coherent-matrix-8942.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://breakable-segment.biz</li>
</ul>
</details>
> request: add client files for function-based-coherent-matrix-8942

- terraform-v2/keycloak-dev/standard-clients/re-contextualized-composite-conglomeration-8943.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://second-hand-socks.net</li>
</ul>
</details>
> request: add client files for re-contextualized-composite-conglomeration-8943

- terraform-v2/keycloak-dev/standard-clients/up-sized-actuating-synergy-8944.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://extroverted-spike.biz</li>
</ul>
</details>
> request: add client files for up-sized-actuating-synergy-8944

- terraform-v2/keycloak-dev/standard-clients/re-contextualized-upward-trending-intranet-8945.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://wild-umbrella.org</li>
</ul>
</details>
> request: add client files for re-contextualized-upward-trending-intranet-8945

- terraform-v2/keycloak-dev/standard-clients/total-maximized-open-system-8946.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://mean-dimple.com</li>
</ul>
</details>
> request: add client files for total-maximized-open-system-8946

- terraform-v2/keycloak-dev/standard-clients/re-contextualized-maximized-encryption-8948.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://haunting-volleyball.org</li>
</ul>
</details>
> request: add client files for re-contextualized-maximized-encryption-8948

- terraform-v2/keycloak-dev/standard-clients/css-api-test-8949.tf
- terraform-v2/keycloak-prod/standard-clients/css-api-test-8949.tf
- terraform-v2/keycloak-test/standard-clients/css-api-test-8949.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://localhost:3000</li>
</ul>
</details>
> request: add client files for css-api-test-8949

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2279-8950.tf
> request: add client files for service-account-for-team-2279-8950

- terraform-v2/keycloak-dev/standard-clients/tians-testing-9-22-example-app-8951.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-9-22-example-app-8951.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-9-22-example-app-8951.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-9-22-example-app-8951

- terraform-v2/keycloak-dev/standard-clients/css-api-test-no-prod-8952.tf
> request: add client files for css-api-test-no-prod-8952

- terraform-v2/keycloak-dev/standard-clients/monitored-attitude-oriented-budgetary-management-8953.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://light-moron.net</li>
</ul>
</details>
> request: add client files for monitored-attitude-oriented-budgetary-management-8953

- terraform-v2/keycloak-dev/standard-clients/ameliorated-bandwidth-monitored-support-8954.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://frivolous-recession.net</li>
</ul>
</details>
> request: add client files for ameliorated-bandwidth-monitored-support-8954

- terraform-v2/keycloak-dev/standard-clients/streamlined-bifurcated-toolset-8956.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://super-starboard.net</li>
</ul>
</details>
> request: add client files for streamlined-bifurcated-toolset-8956

- terraform-v2/keycloak-dev/standard-clients/cross-platform-heuristic-knowledge-base-8957.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://delayed-criminal.info</li>
</ul>
</details>
> request: add client files for cross-platform-heuristic-knowledge-base-8957

- terraform-v2/keycloak-dev/standard-clients/switchable-maximized-orchestration-8958.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://fine-swallow.biz</li>
</ul>
</details>
> request: add client files for switchable-maximized-orchestration-8958

- terraform-v2/keycloak-dev/standard-clients/multi-layered-bi-directional-groupware-8959.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://buzzing-turn.biz</li>
</ul>
</details>
> request: add client files for multi-layered-bi-directional-groupware-8959

- terraform-v2/keycloak-dev/standard-clients/organized-background-graphic-interface-8960.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://amusing-dud.org</li>
</ul>
</details>
> request: add client files for organized-background-graphic-interface-8960

- terraform-v2/keycloak-dev/standard-clients/automated-impactful-database-8961.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://dim-eurocentrism.net</li>
</ul>
</details>
> request: add client files for automated-impactful-database-8961

- terraform-v2/keycloak-dev/standard-clients/inverse-foreground-leverage-8962.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://thoughtful-cereal.com</li>
</ul>
</details>
> request: add client files for inverse-foreground-leverage-8962

- terraform-v2/keycloak-dev/standard-clients/cross-group-client-driven-framework-8963.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://troubled-cauliflower.com</li>
</ul>
</details>
> request: add client files for cross-group-client-driven-framework-8963

- terraform-v2/keycloak-dev/standard-clients/streamlined-logistical-architecture-8964.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://outlandish-latex.biz</li>
</ul>
</details>
> request: add client files for streamlined-logistical-architecture-8964

- terraform-v2/keycloak-dev/standard-clients/horizontal-mobile-algorithm-8965.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://glass-pet.name</li>
</ul>
</details>
> request: add client files for horizontal-mobile-algorithm-8965

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2279-8950.tf
> request: delete client files for service-account-for-team-2279-8950

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2279-8966.tf
> request: add client files for service-account-for-team-2279-8966

- terraform-v2/keycloak-dev/standard-clients/reactive-global-utilisation-8967.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://infantile-nose.com</li>
</ul>
</details>
> request: add client files for reactive-global-utilisation-8967

- terraform-v2/keycloak-dev/standard-clients/multi-layered-real-time-alliance-8968.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://exciting-masterpiece.org</li>
</ul>
</details>
> request: add client files for multi-layered-real-time-alliance-8968

- terraform-v2/keycloak-dev/standard-clients/balanced-context-sensitive-definition-8969.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://unwritten-entrepreneur.name</li>
</ul>
</details>
> request: add client files for balanced-context-sensitive-definition-8969

- terraform-v2/keycloak-dev/standard-clients/proactive-asynchronous-interface-8970.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://oddball-vaulting.biz</li>
</ul>
</details>
> request: add client files for proactive-asynchronous-interface-8970

- terraform-v2/keycloak-dev/standard-clients/diverse-4-th-generation-success-8971.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://sweltering-hoe.org</li>
</ul>
</details>
> request: add client files for diverse-4th-generation-success-8971

- terraform-v2/keycloak-dev/standard-clients/versatile-intangible-model-8972.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://all-smelting.org</li>
</ul>
</details>
> request: add client files for versatile-intangible-model-8972

- terraform-v2/keycloak-dev/standard-clients/ergonomic-methodical-intranet-8974.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://handy-simplification.name</li>
</ul>
</details>
> request: add client files for ergonomic-methodical-intranet-8974

- terraform-v2/keycloak-dev/standard-clients/face-to-face-value-added-concept-8975.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://entire-drinking.org</li>
</ul>
</details>
> request: add client files for face-to-face-value-added-concept-8975

- terraform-v2/keycloak-dev/standard-clients/public-key-24-hour-system-engine-8976.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://calm-carpet.name</li>
</ul>
</details>
> request: add client files for public-key-24-hour-system-engine-8976

- terraform-v2/keycloak-dev/standard-clients/persistent-responsive-secured-line-8977.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://forsaken-validate.biz</li>
</ul>
</details>
> request: add client files for persistent-responsive-secured-line-8977

- terraform-v2/keycloak-dev/standard-clients/face-to-face-tangible-workforce-8978.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://spry-left.com</li>
</ul>
</details>
> request: add client files for face-to-face-tangible-workforce-8978

- terraform-v2/keycloak-dev/standard-clients/multi-channelled-fault-tolerant-artificial-intelli-8979.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://anguished-plantation.net</li>
</ul>
</details>
> request: add client files for multi-channelled-fault-tolerant-artificial-intelli-8979

- terraform-v2/keycloak-dev/standard-clients/synergized-full-range-focus-group-8980.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://each-peasant.org</li>
</ul>
</details>
> request: add client files for synergized-full-range-focus-group-8980

- terraform-v2/keycloak-dev/standard-clients/digitized-systematic-task-force-8981.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://capital-daddy.name</li>
</ul>
</details>
> request: add client files for digitized-systematic-task-force-8981

- terraform-v2/keycloak-dev/standard-clients/cross-platform-mission-critical-data-warehouse-8982.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://quarrelsome-product.info</li>
</ul>
</details>
> request: add client files for cross-platform-mission-critical-data-warehouse-8982

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2280-8983.tf
> request: add client files for service-account-for-team-2280-8983

- terraform-v2/keycloak-dev/standard-clients/down-sized-background-initiative-8984.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://crooked-gong.info</li>
</ul>
</details>
> request: add client files for down-sized-background-initiative-8984

- terraform-v2/keycloak-dev/standard-clients/seamless-encompassing-forecast-8985.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://likable-wilderness.info</li>
</ul>
</details>
> request: add client files for seamless-encompassing-forecast-8985

- terraform-v2/keycloak-dev/standard-clients/fully-configurable-demand-driven-system-engine-8986.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://gullible-sister.info</li>
</ul>
</details>
> request: add client files for fully-configurable-demand-driven-system-engine-8986

- terraform-v2/keycloak-dev/standard-clients/cross-platform-zero-administration-challenge-8987.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://nice-brewer.biz</li>
</ul>
</details>
> request: add client files for cross-platform-zero-administration-challenge-8987

- terraform-v2/keycloak-dev/standard-clients/down-sized-content-based-process-improvement-8988.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://incomplete-broiler.net</li>
</ul>
</details>
> request: add client files for down-sized-content-based-process-improvement-8988

- terraform-v2/keycloak-dev/standard-clients/face-to-face-leading-edge-adapter-8990.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://wise-surroundings.name</li>
</ul>
</details>
> request: add client files for face-to-face-leading-edge-adapter-8990

- terraform-v2/keycloak-dev/standard-clients/test-saml-custm-clntdid-nk-8991.tf
> request: add client files for test-saml-custm-clntdid-nk-8991

- terraform-v2/keycloak-dev/standard-clients/organic-optimizing-structure-8992.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://improbable-score.com</li>
</ul>
</details>
> request: add client files for organic-optimizing-structure-8992

- terraform-v2/keycloak-dev/standard-clients/sharable-foreground-firmware-8993.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://forceful-underwriting.name</li>
</ul>
</details>
> request: add client files for sharable-foreground-firmware-8993

- terraform-v2/keycloak-dev/standard-clients/realigned-attitude-oriented-workforce-9010.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://chief-crude.info</li>
</ul>
</details>
> request: add client files for realigned-attitude-oriented-workforce-9010

- terraform-v2/keycloak-dev/standard-clients/cross-group-web-enabled-initiative-9012.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://glamorous-setting.org</li>
</ul>
</details>
> request: add client files for cross-group-web-enabled-initiative-9012

- terraform-v2/keycloak-dev/standard-clients/organic-neutral-website-9013.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://meaty-stove.net</li>
</ul>
</details>
> request: add client files for organic-neutral-website-9013

- terraform-v2/keycloak-dev/standard-clients/ergonomic-didactic-archive-9014.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://hungry-misfit.net</li>
</ul>
</details>
> request: add client files for ergonomic-didactic-archive-9014

- terraform-v2/keycloak-dev/standard-clients/operative-6-th-generation-data-warehouse-9015.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://criminal-cough.org</li>
</ul>
</details>
> request: add client files for operative-6th-generation-data-warehouse-9015

- terraform-v2/keycloak-dev/standard-clients/synchronised-clear-thinking-budgetary-management-9016.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://well-to-do-loft.info</li>
</ul>
</details>
> request: add client files for synchronised-clear-thinking-budgetary-management-9016

- terraform-v2/keycloak-dev/standard-clients/versatile-coherent-firmware-9017.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://kindly-bulb.com</li>
</ul>
</details>
> request: add client files for versatile-coherent-firmware-9017

- terraform-v2/keycloak-dev/standard-clients/re-contextualized-mission-critical-service-desk-9018.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://worried-peen.net</li>
</ul>
</details>
> request: add client files for re-contextualized-mission-critical-service-desk-9018

- terraform-v2/keycloak-dev/standard-clients/down-sized-background-alliance-9019.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://grateful-tornado.com</li>
</ul>
</details>
> request: add client files for down-sized-background-alliance-9019

- terraform-v2/keycloak-dev/standard-clients/seamless-hybrid-budgetary-management-9020.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://loyal-nephew.biz</li>
</ul>
</details>
> request: add client files for seamless-hybrid-budgetary-management-9020

- terraform-v2/keycloak-dev/standard-clients/customizable-didactic-toolset-9021.tf
> request: add client files for customizable-didactic-toolset-9021

- terraform-v2/keycloak-dev/standard-clients/centralized-full-range-ability-9022.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://delirious-clove.net</li>
</ul>
</details>
> request: add client files for centralized-full-range-ability-9022

- terraform-v2/keycloak-dev/standard-clients/total-directional-approach-9023.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://rotten-limestone.org</li>
</ul>
</details>
> request: add client files for total-directional-approach-9023

- terraform-v2/keycloak-dev/standard-clients/proactive-demand-driven-contingency-9024.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://unaware-mayonnaise.name</li>
</ul>
</details>
> request: add client files for proactive-demand-driven-contingency-9024

- terraform-v2/keycloak-dev/standard-clients/versatile-fresh-thinking-knowledge-base-9025.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://fussy-foray.biz</li>
</ul>
</details>
> request: add client files for versatile-fresh-thinking-knowledge-base-9025

- terraform-v2/keycloak-dev/standard-clients/streamlined-systematic-database-9026.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://chief-pledge.org</li>
</ul>
</details>
> request: add client files for streamlined-systematic-database-9026

- terraform-v2/keycloak-dev/standard-clients/stand-alone-system-worthy-focus-group-9027.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://fatherly-icebreaker.info</li>
</ul>
</details>
> request: add client files for stand-alone-system-worthy-focus-group-9027

- terraform-v2/keycloak-dev/standard-clients/open-architected-well-modulated-solution-9028.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://whimsical-bias.info</li>
</ul>
</details>
> request: add client files for open-architected-well-modulated-solution-9028

- terraform-v2/keycloak-dev/standard-clients/triple-buffered-optimal-support-9029.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://probable-wreck.biz</li>
</ul>
</details>
> request: add client files for triple-buffered-optimal-support-9029

- terraform-v2/keycloak-dev/standard-clients/synergized-transitional-process-improvement-9030.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://glistening-slave.name</li>
</ul>
</details>
> request: add client files for synergized-transitional-process-improvement-9030

- terraform-v2/keycloak-dev/standard-clients/face-to-face-heuristic-array-9031.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://concerned-bike.org</li>
</ul>
</details>
> request: add client files for face-to-face-heuristic-array-9031

- terraform-v2/keycloak-dev/standard-clients/networked-client-driven-portal-9032.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://untidy-biscuit.com</li>
</ul>
</details>
> request: add client files for networked-client-driven-portal-9032

- terraform-v2/keycloak-dev/standard-clients/persevering-next-generation-interface-9033.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://baggy-submarine.net</li>
</ul>
</details>
> request: add client files for persevering-next-generation-interface-9033

- terraform-v2/keycloak-dev/standard-clients/extended-stable-graphical-user-interface-9034.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://submissive-millstone.info</li>
</ul>
</details>
> request: add client files for extended-stable-graphical-user-interface-9034

- terraform-v2/keycloak-dev/standard-clients/decentralized-radical-matrices-9035.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://rowdy-farmland.info</li>
</ul>
</details>
> request: add client files for decentralized-radical-matrices-9035

- terraform-v2/keycloak-dev/standard-clients/vision-oriented-local-graphical-user-interface-9037.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://loose-nationality.name</li>
</ul>
</details>
> request: add client files for vision-oriented-local-graphical-user-interface-9037

- terraform-v2/keycloak-dev/standard-clients/mandatory-optimizing-initiative-9038.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://celebrated-know-how.com</li>
</ul>
</details>
> request: add client files for mandatory-optimizing-initiative-9038

- terraform-v2/keycloak-dev/standard-clients/persistent-bi-directional-alliance-9039.tf
<details>
<ul>✔️ Valid Redirect Urls<li>https://aged-satisfaction.com</li>
</ul>
</details>
> request: add client files for persistent-bi-directional-alliance-9039
