terraform-v2/keycloak-dev/standard-clients/persevering-client-server-open-architecture-9040.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://jovial-octavo.info</li>
</ul>
</details>

request: add client files for persevering-client-server-open-architecture-9040

---

terraform-v2/keycloak-dev/standard-clients/optimized-fresh-thinking-pricing-structure-9041.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://second-hand-tribe.name</li>
</ul>
</details>

request: add client files for optimized-fresh-thinking-pricing-structure-9041

---

terraform-v2/keycloak-dev/standard-clients/monitored-tangible-archive-9042.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://plush-limestone.name</li>
</ul>
</details>

request: add client files for monitored-tangible-archive-9042

---

terraform-v2/keycloak-dev/standard-clients/stand-alone-client-server-support-9043.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://remote-bunghole.info</li>
</ul>
</details>

request: add client files for stand-alone-client-server-support-9043

---

terraform-v2/keycloak-dev/standard-clients/project-1-9044.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://prudent-gosling.org</li>
</ul>
</details>

request: add client files for project-1-9044

---

terraform-v2/keycloak-dev/standard-clients/project-2-9045.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://vain-volunteer.com</li>
</ul>
</details>

request: add client files for project-2-9045

---

terraform-v2/keycloak-dev/standard-clients/project-3-9046.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://subdued-abolishment.net</li>
</ul>
</details>

request: add client files for project-3-9046

---

terraform-v2/keycloak-dev/standard-clients/project-4-9047.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://aggravating-waist.com</li>
</ul>
</details>

request: add client files for project-4-9047

---

terraform-v2/keycloak-dev/standard-clients/project-3-9050.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://magnificent-hybridization.org</li>
</ul>
</details>

request: add client files for project-3-9050

---

terraform-v2/keycloak-dev/standard-clients/project-1-9048.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://immediate-min.name</li>
</ul>
</details>

request: add client files for project-1-9048

---

terraform-v2/keycloak-dev/standard-clients/project-2-9049.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://exhausted-morning.biz</li>
</ul>
</details>

request: add client files for project-2-9049

---

terraform-v2/keycloak-dev/standard-clients/project-4-9051.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://murky-cough.info</li>
</ul>
</details>

request: add client files for project-4-9051

---

terraform-v2/keycloak-dev/standard-clients/project-2-9053.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://slim-tank.com</li>
</ul>
</details>

request: add client files for project-2-9053

---

terraform-v2/keycloak-dev/standard-clients/project-3-9054.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://slushy-possibility.info</li>
</ul>
</details>

request: add client files for project-3-9054

---

terraform-v2/keycloak-dev/standard-clients/project-4-9055.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://second-decongestant.net</li>
</ul>
</details>

request: add client files for project-4-9055

---

terraform-v2/keycloak-dev/standard-clients/project-1-9052.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://tempting-catsup.info</li>
</ul>
</details>

request: add client files for project-1-9052

---

terraform-v2/keycloak-dev/standard-clients/project-2-9057.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://meager-bag.net</li>
</ul>
</details>

request: add client files for project-2-9057

---

terraform-v2/keycloak-dev/standard-clients/project-3-9058.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://rough-coalition.org</li>
</ul>
</details>

request: add client files for project-3-9058

---

terraform-v2/keycloak-dev/standard-clients/project-1-9056.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://reasonable-vernacular.info</li>
</ul>
</details>

request: add client files for project-1-9056

---

terraform-v2/keycloak-dev/standard-clients/project-4-9059.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://rosy-retirement.net</li>
</ul>
</details>

request: add client files for project-4-9059

---

terraform-v2/keycloak-dev/standard-clients/test-1-9060.tf

request: add client files for test-1-9060

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2311-9061.tf

request: add client files for service-account-for-team-2311-9061

---

terraform-v2/keycloak-dev/standard-clients/project-1-9062.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://lustrous-necessity.name</li>
</ul>
</details>

request: add client files for project-1-9062

---

terraform-v2/keycloak-dev/standard-clients/project-3-9064.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://jagged-bandana.name</li>
</ul>
</details>

request: add client files for project-3-9064

---

terraform-v2/keycloak-dev/standard-clients/project-2-9063.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://terrific-tool.net</li>
</ul>
</details>

request: add client files for project-2-9063

---

terraform-v2/keycloak-dev/standard-clients/project-4-9065.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://shocked-reef.biz</li>
</ul>
</details>

request: add client files for project-4-9065

---

terraform-v2/keycloak-dev/standard-clients/project-1-9066.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://useless-cupola.biz</li>
</ul>
</details>

request: add client files for project-1-9066

---

terraform-v2/keycloak-dev/standard-clients/project-2-9067.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://mean-means.info</li>
</ul>
</details>

request: add client files for project-2-9067

---

terraform-v2/keycloak-dev/standard-clients/project-3-9068.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://black-and-white-giant.com</li>
</ul>
</details>

request: add client files for project-3-9068

---

terraform-v2/keycloak-dev/standard-clients/project-4-9069.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://descriptive-improvement.net</li>
</ul>
</details>

request: add client files for project-4-9069

---

terraform-v2/keycloak-dev/standard-clients/project-5-9070.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://profitable-wool.name</li>
</ul>
</details>

request: add client files for project-5-9070

---

terraform-v2/keycloak-dev/standard-clients/project-6-9071.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://actual-shoes.org</li>
</ul>
</details>

request: add client files for project-6-9071

---

terraform-v2/keycloak-dev/standard-clients/project-7-9072.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://impressive-tech.org</li>
</ul>
</details>

request: add client files for project-7-9072

---

terraform-v2/keycloak-dev/standard-clients/project-8-9073.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://icky-arrival.biz</li>
</ul>
</details>

request: add client files for project-8-9073

---

terraform-v2/keycloak-dev/standard-clients/project-9-9074.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://sentimental-scraper.org</li>
</ul>
</details>

request: add client files for project-9-9074

---

terraform-v2/keycloak-dev/standard-clients/project-10-9075.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://academic-divide.name</li>
</ul>
</details>

request: add client files for project-10-9075

---

terraform-v2/keycloak-dev/standard-clients/project-11-9076.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://dizzy-business.com</li>
</ul>
</details>

request: add client files for project-11-9076

---

terraform-v2/keycloak-dev/standard-clients/project-12-9077.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://sticky-gym.net</li>
</ul>
</details>

request: add client files for project-12-9077

---

terraform-v2/keycloak-dev/standard-clients/project-13-9078.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://burdensome-socks.info</li>
</ul>
</details>

request: add client files for project-13-9078

---

terraform-v2/keycloak-dev/standard-clients/project-14-9079.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://unlined-taxi.biz</li>
</ul>
</details>

request: add client files for project-14-9079

---

terraform-v2/keycloak-dev/standard-clients/project-15-9080.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://melodic-azimuth.biz</li>
</ul>
</details>

request: add client files for project-15-9080

---

terraform-v2/keycloak-dev/standard-clients/project-16-9081.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://bowed-label.info</li>
</ul>
</details>

request: add client files for project-16-9081

---

terraform-v2/keycloak-dev/standard-clients/project-17-9082.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://bewitched-bus.name</li>
</ul>
</details>

request: add client files for project-17-9082

---

terraform-v2/keycloak-dev/standard-clients/project-18-9083.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://infatuated-duckling.com</li>
</ul>
</details>

request: add client files for project-18-9083

---

terraform-v2/keycloak-dev/standard-clients/project-19-9084.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://potable-end.net</li>
</ul>
</details>

request: add client files for project-19-9084

---

terraform-v2/keycloak-dev/standard-clients/project-20-9085.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://unruly-judge.net</li>
</ul>
</details>

request: add client files for project-20-9085

---

terraform-v2/keycloak-dev/standard-clients/project-21-9086.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://left-pigeon.biz</li>
</ul>
</details>

request: add client files for project-21-9086

---

terraform-v2/keycloak-dev/standard-clients/project-22-9087.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://neat-barrier.net</li>
</ul>
</details>

request: add client files for project-22-9087

---

terraform-v2/keycloak-dev/standard-clients/project-23-9088.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://clear-encouragement.biz</li>
</ul>
</details>

request: add client files for project-23-9088

---

terraform-v2/keycloak-dev/standard-clients/project-25-9090.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://weak-lathe.org</li>
</ul>
</details>

request: add client files for project-25-9090

---

terraform-v2/keycloak-dev/standard-clients/project-24-9089.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://runny-chuck.org</li>
</ul>
</details>

request: add client files for project-24-9089

---

terraform-v2/keycloak-dev/standard-clients/project-26-9091.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://phony-brochure.info</li>
</ul>
</details>

request: add client files for project-26-9091

---

terraform-v2/keycloak-dev/standard-clients/project-27-9092.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://recent-maternity.com</li>
</ul>
</details>

request: add client files for project-27-9092

---

terraform-v2/keycloak-dev/standard-clients/project-28-9093.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://clear-cut-screen.biz</li>
</ul>
</details>

request: add client files for project-28-9093

---

terraform-v2/keycloak-dev/standard-clients/project-29-9094.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://joyful-storey.com</li>
</ul>
</details>

request: add client files for project-29-9094

---

terraform-v2/keycloak-dev/standard-clients/project-30-9095.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://real-load.net</li>
</ul>
</details>

request: add client files for project-30-9095

---

terraform-v2/keycloak-dev/standard-clients/project-31-9096.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://first-aluminum.biz</li>
</ul>
</details>

request: add client files for project-31-9096

---

terraform-v2/keycloak-dev/standard-clients/project-32-9097.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://marvelous-emitter.info</li>
</ul>
</details>

request: add client files for project-32-9097

---

terraform-v2/keycloak-dev/standard-clients/project-33-9098.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://bright-noun.net</li>
</ul>
</details>

request: add client files for project-33-9098

---

terraform-v2/keycloak-dev/standard-clients/project-35-9100.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://scrawny-rugby.biz</li>
</ul>
</details>

request: add client files for project-35-9100

---

terraform-v2/keycloak-dev/standard-clients/project-36-9101.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://complete-index.org</li>
</ul>
</details>

request: add client files for project-36-9101

---

terraform-v2/keycloak-dev/standard-clients/gkhgkjhgkjhg-9102.tf

request: add client files for gkhgkjhgkjhg-9102

---

terraform-v2/keycloak-dev/standard-clients/project-2-9104.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://standard-reindeer.net</li>
</ul>
</details>

request: add client files for project-2-9104

---

terraform-v2/keycloak-dev/standard-clients/project-1-9103.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://frayed-goodnight.org</li>
</ul>
</details>

request: add client files for project-1-9103

---

terraform-v2/keycloak-dev/standard-clients/project-3-9105.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://offensive-fencing.org</li>
</ul>
</details>

request: add client files for project-3-9105

---

terraform-v2/keycloak-dev/standard-clients/project-4-9106.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://unwelcome-expression.info</li>
</ul>
</details>

request: add client files for project-4-9106

---

terraform-v2/keycloak-dev/standard-clients/project-6-9108.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://corny-fat.name</li>
</ul>
</details>

request: add client files for project-6-9108

---

terraform-v2/keycloak-dev/standard-clients/project-5-9107.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://distorted-meantime.info</li>
</ul>
</details>

request: add client files for project-5-9107

---

terraform-v2/keycloak-dev/standard-clients/project-7-9109.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://earnest-gerbil.com</li>
</ul>
</details>

request: add client files for project-7-9109

---

terraform-v2/keycloak-dev/standard-clients/project-3-9112.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://proper-proposal.org</li>
</ul>
</details>

request: add client files for project-3-9112

---

terraform-v2/keycloak-dev/standard-clients/project-1-9110.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://punctual-blow.biz</li>
</ul>
</details>

request: add client files for project-1-9110

---

terraform-v2/keycloak-dev/standard-clients/project-4-9113.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://spirited-mail.info</li>
</ul>
</details>

request: add client files for project-4-9113

---

terraform-v2/keycloak-dev/standard-clients/project-6-9115.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://athletic-velodrome.name</li>
</ul>
</details>

request: add client files for project-6-9115

---

terraform-v2/keycloak-dev/standard-clients/project-5-9114.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://key-macro.biz</li>
</ul>
</details>

request: add client files for project-5-9114

---

terraform-v2/keycloak-dev/standard-clients/project-7-9116.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://filthy-load.org</li>
</ul>
</details>

request: add client files for project-7-9116

---

terraform-v2/keycloak-dev/standard-clients/project-8-9117.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://dopey-puritan.net</li>
</ul>
</details>

request: add client files for project-8-9117

---

terraform-v2/keycloak-dev/standard-clients/project-1-9118.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://concerned-max.org</li>
</ul>
</details>

request: add client files for project-1-9118

---

terraform-v2/keycloak-dev/standard-clients/project-2-9119.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://infantile-steamroller.net</li>
</ul>
</details>

request: add client files for project-2-9119

---

terraform-v2/keycloak-dev/standard-clients/project-3-9120.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://demanding-peak.name</li>
</ul>
</details>

request: add client files for project-3-9120

---

terraform-v2/keycloak-dev/standard-clients/project-5-9122.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://whole-pipe.biz</li>
</ul>
</details>

request: add client files for project-5-9122

---

terraform-v2/keycloak-dev/standard-clients/project-4-9121.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://buzzing-burro.name</li>
</ul>
</details>

request: add client files for project-4-9121

---

terraform-v2/keycloak-dev/standard-clients/project-7-9124.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://wasteful-quiver.biz</li>
</ul>
</details>

request: add client files for project-7-9124

---

terraform-v2/keycloak-dev/standard-clients/project-6-9123.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://quiet-dictaphone.net</li>
</ul>
</details>

request: add client files for project-6-9123

---

terraform-v2/keycloak-dev/standard-clients/project-2-9126.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://acclaimed-mezzanine.org</li>
</ul>
</details>

request: add client files for project-2-9126

---

terraform-v2/keycloak-dev/standard-clients/project-1-9125.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://silly-zephyr.info</li>
</ul>
</details>

request: add client files for project-1-9125

---

terraform-v2/keycloak-dev/standard-clients/project-3-9127.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://mushy-circulation.info</li>
</ul>
</details>

request: add client files for project-3-9127

---

terraform-v2/keycloak-dev/standard-clients/project-4-9128.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://envious-preface.name</li>
</ul>
</details>

request: add client files for project-4-9128

---

terraform-v2/keycloak-dev/standard-clients/project-1-9130.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://suspicious-vault.org</li>
</ul>
</details>

request: add client files for project-1-9130

---

terraform-v2/keycloak-dev/standard-clients/project-2-9131.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://skeletal-kindness.com</li>
</ul>
</details>

request: add client files for project-2-9131

---

terraform-v2/keycloak-dev/standard-clients/project-3-9132.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://dear-standard.org</li>
</ul>
</details>

request: add client files for project-3-9132

---

terraform-v2/keycloak-dev/standard-clients/project-5-9134.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://valid-surge.biz</li>
</ul>
</details>

request: add client files for project-5-9134

---

terraform-v2/keycloak-dev/standard-clients/project-4-9133.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://sophisticated-botany.name</li>
</ul>
</details>

request: add client files for project-4-9133

---

terraform-v2/keycloak-dev/standard-clients/project-7-9136.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://dense-man.org</li>
</ul>
</details>

request: add client files for project-7-9136

---

terraform-v2/keycloak-dev/standard-clients/project-6-9135.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://torn-detour.name</li>
</ul>
</details>

request: add client files for project-6-9135

---

terraform-v2/keycloak-dev/standard-clients/project-1-9138.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://entire-midnight.biz</li>
</ul>
</details>

request: add client files for project-1-9138

---

terraform-v2/keycloak-dev/standard-clients/project-3-9140.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://dry-balalaika.info</li>
</ul>
</details>

request: add client files for project-3-9140

---

terraform-v2/keycloak-dev/standard-clients/project-2-9139.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://adored-dearest.com</li>
</ul>
</details>

request: add client files for project-2-9139

---

terraform-v2/keycloak-dev/standard-clients/project-4-9141.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://dizzy-separation.com</li>
</ul>
</details>

request: add client files for project-4-9141

---

terraform-v2/keycloak-dev/standard-clients/project-5-9142.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://forthright-inevitable.org</li>
</ul>
</details>

request: add client files for project-5-9142

---

terraform-v2/keycloak-dev/standard-clients/project-6-9143.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://winding-carload.org</li>
</ul>
</details>

request: add client files for project-6-9143

---

terraform-v2/keycloak-dev/standard-clients/project-7-9144.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://bold-explosion.net</li>
</ul>
</details>

request: add client files for project-7-9144

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-13-sandbox-url-9145.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-13-sandbox-url-9145.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-13-sandbox-url-9145.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-13-sandbox-url-9145

---

terraform-v2/keycloak-dev/standard-clients/saml-test-sept-2023-8989.tf

request: add client files for saml-test-sept-2023-8989

---

terraform-v2/keycloak-dev/standard-clients/test-saml-sign-asr-nk-01-9147.tf
terraform-v2/keycloak-prod/standard-clients/test-saml-sign-asr-nk-01-9147.tf
terraform-v2/keycloak-test/standard-clients/test-saml-sign-asr-nk-01-9147.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://example.com</li>
</ul>
</details>

request: add client files for test-saml-sign-asr-nk-01-9147

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2212-9149.tf

request: add client files for service-account-for-team-2212-9149

---

terraform-v2/keycloak-dev/standard-clients/test-saml-sign-asr-nk-02-9150.tf
terraform-v2/keycloak-prod/standard-clients/test-saml-sign-asr-nk-02-9150.tf
terraform-v2/keycloak-test/standard-clients/test-saml-sign-asr-nk-02-9150.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://example.com</li>
</ul>
</details>

request: add client files for test-saml-sign-asr-nk-02-9150

---

terraform-v2/keycloak-dev/standard-clients/project-1-9152.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://glamorous-gold.org</li>
</ul>
</details>

request: add client files for project-1-9152

---

terraform-v2/keycloak-dev/standard-clients/project-2-9153.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://nautical-film.info</li>
</ul>
</details>

request: add client files for project-2-9153

---

terraform-v2/keycloak-dev/standard-clients/project-3-9154.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://flat-league.com</li>
</ul>
</details>

request: add client files for project-3-9154

---

terraform-v2/keycloak-dev/standard-clients/project-4-9155.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://rundown-hit.biz</li>
</ul>
</details>

request: add client files for project-4-9155

---

terraform-v2/keycloak-dev/standard-clients/project-5-9156.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://straight-cushion.com</li>
</ul>
</details>

request: add client files for project-5-9156

---

terraform-v2/keycloak-dev/standard-clients/project-1-9157.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://arid-harpooner.com</li>
</ul>
</details>

request: add client files for project-1-9157

---

terraform-v2/keycloak-dev/standard-clients/project-2-9158.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://defensive-stalk.info</li>
</ul>
</details>

request: add client files for project-2-9158

---

terraform-v2/keycloak-dev/standard-clients/project-3-9159.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://disfigured-nourishment.com</li>
</ul>
</details>

request: add client files for project-3-9159

---

terraform-v2/keycloak-dev/standard-clients/project-4-9160.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://wary-pail.biz</li>
</ul>
</details>

request: add client files for project-4-9160

---

terraform-v2/keycloak-dev/standard-clients/project-5-9161.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://difficult-tomorrow.biz</li>
</ul>
</details>

request: add client files for project-5-9161

---

terraform-v2/keycloak-dev/standard-clients/project-6-9162.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://scornful-printing.biz</li>
</ul>
</details>

request: add client files for project-6-9162

---

terraform-v2/keycloak-dev/standard-clients/oct-13-zorin-test-2-9163.tf

request: add client files for oct-13-zorin-test-2-9163

---

terraform-v2/keycloak-dev/standard-clients/training-2-test-9164.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/sso-requests-sandbox/reque</li>
</ul>
</details>

request: add client files for training-2-test-9164

---

terraform-v2/keycloak-dev/standard-clients/project-1-9165.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://frilly-oats.org</li>
</ul>
</details>

request: add client files for project-1-9165

---

terraform-v2/keycloak-dev/standard-clients/project-2-9166.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://possible-sinuosity.biz</li>
</ul>
</details>

request: add client files for project-2-9166

---

terraform-v2/keycloak-dev/standard-clients/project-3-9167.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://wealthy-dirndl.biz</li>
</ul>
</details>

request: add client files for project-3-9167

---

terraform-v2/keycloak-dev/standard-clients/project-4-9169.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://indelible-termite.biz</li>
</ul>
</details>

request: add client files for project-4-9169

---

terraform-v2/keycloak-dev/standard-clients/project-5-9170.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://scarce-warrior.info</li>
</ul>
</details>

request: add client files for project-5-9170

---

terraform-v2/keycloak-dev/standard-clients/ssotraining-test-2-oct-13-9168.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/sso-requests-sandbox/request/9*</li>
</ul>
</details>

request: add client files for ssotraining-test-2-oct-13-9168

---

terraform-v2/keycloak-dev/standard-clients/project-6-9171.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://agreeable-thug.org</li>
</ul>
</details>

request: add client files for project-6-9171

---

terraform-v2/keycloak-dev/standard-clients/project-7-9172.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://watchful-vanilla.name</li>
</ul>
</details>

request: add client files for project-7-9172

---

terraform-v2/keycloak-dev/standard-clients/project-8-9173.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://haunting-guarantee.com</li>
</ul>
</details>

request: add client files for project-8-9173

---

terraform-v2/keycloak-dev/standard-clients/project-9-9174.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://trim-handsaw.info</li>
</ul>
</details>

request: add client files for project-9-9174

---

terraform-v2/keycloak-dev/standard-clients/project-10-9175.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://muffled-researcher.org</li>
</ul>
</details>

request: add client files for project-10-9175

---

terraform-v2/keycloak-dev/standard-clients/project-11-9176.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://hidden-crane.info</li>
</ul>
</details>

request: add client files for project-11-9176

---

terraform-v2/keycloak-dev/standard-clients/ssoteam-test-1-9177.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://bcgov.github.io/sso-requests-sandbox/*</li>
</ul>
</details>

request: add client files for ssoteam-test-1-9177

---

terraform-v2/keycloak-dev/standard-clients/project-12-9178.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://worn-hip.org</li>
</ul>
</details>

request: add client files for project-12-9178

---

terraform-v2/keycloak-dev/standard-clients/project-13-9179.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://downright-pinkie.info</li>
</ul>
</details>

request: add client files for project-13-9179

---

terraform-v2/keycloak-dev/standard-clients/project-14-9180.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://acceptable-stay.org</li>
</ul>
</details>

request: add client files for project-14-9180

---

terraform-v2/keycloak-dev/standard-clients/project-15-9181.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://primary-stir-fry.com</li>
</ul>
</details>

request: add client files for project-15-9181

---

terraform-v2/keycloak-dev/standard-clients/project-16-9182.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://dazzling-tapioca.name</li>
</ul>
</details>

request: add client files for project-16-9182

---

terraform-v2/keycloak-dev/standard-clients/project-17-9183.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://damaged-asparagus.name</li>
</ul>
</details>

request: add client files for project-17-9183

---

terraform-v2/keycloak-dev/standard-clients/project-18-9184.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://knotty-purchase.info</li>
</ul>
</details>

request: add client files for project-18-9184

---

terraform-v2/keycloak-dev/standard-clients/project-19-9185.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://shameless-hearing.biz</li>
</ul>
</details>

request: add client files for project-19-9185

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2280-8983.tf

request: delete client files for service-account-for-team-2280-8983

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2280-9187.tf

request: add client files for service-account-for-team-2280-9187

---

terraform-v2/keycloak-dev/standard-clients/project-20-9186.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://worse-console.net</li>
</ul>
</details>

request: add client files for project-20-9186

---

terraform-v2/keycloak-dev/standard-clients/training-2-oct-13-test-2-9189.tf

request: add client files for training-2-oct-13-test-2-9189

---

terraform-v2/keycloak-dev/standard-clients/trainingto-create-surveysubmit-9190.tf

request: add client files for trainingto-create-surveysubmit-9190

---

terraform-v2/keycloak-dev/standard-clients/test-create-survey-oct-13-9191.tf

request: add client files for test-create-survey-oct-13-9191

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2316-9192.tf

request: add client files for service-account-for-team-2316-9192

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2313-9193.tf

request: add client files for service-account-for-team-2313-9193

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2313-9193.tf

request: delete client files for service-account-for-team-2313-9193

---

terraform-v2/keycloak-dev/standard-clients/open-architected-systematic-productivity-9194.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://wavy-brunch.org</li>
</ul>
</details>

request: add client files for open-architected-systematic-productivity-9194

---

terraform-v2/keycloak-dev/standard-clients/vision-oriented-discrete-flexibility-9195.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://immediate-lunchmeat.name</li>
</ul>
</details>

request: add client files for vision-oriented-discrete-flexibility-9195

---

terraform-v2/keycloak-dev/standard-clients/fundamental-non-volatile-moderator-9196.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://scratchy-boycott.name</li>
</ul>
</details>

request: add client files for fundamental-non-volatile-moderator-9196

---

terraform-v2/keycloak-dev/standard-clients/integrated-national-encoding-9197.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://functional-eviction.org</li>
</ul>
</details>

request: add client files for integrated-national-encoding-9197

---

terraform-v2/keycloak-dev/standard-clients/business-focused-motivating-process-improvement-9198.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://deserted-crazy.net</li>
</ul>
</details>

request: add client files for business-focused-motivating-process-improvement-9198

---

terraform-v2/keycloak-dev/standard-clients/customizable-methodical-internet-solution-9199.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://careful-chaos.name</li>
</ul>
</details>

request: add client files for customizable-methodical-internet-solution-9199

---

terraform-v2/keycloak-dev/standard-clients/re-contextualized-grid-enabled-function-9200.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://finished-decryption.biz</li>
</ul>
</details>

request: add client files for re-contextualized-grid-enabled-function-9200

---

terraform-v2/keycloak-dev/standard-clients/robust-high-level-pricing-structure-9201.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://intrepid-functionality.biz</li>
</ul>
</details>

request: add client files for robust-high-level-pricing-structure-9201

---

terraform-v2/keycloak-dev/standard-clients/team-oriented-hybrid-middleware-9202.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://ample-sand.org</li>
</ul>
</details>

request: add client files for team-oriented-hybrid-middleware-9202

---

terraform-v2/keycloak-dev/standard-clients/ergonomic-tangible-algorithm-9206.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://shiny-brewer.biz</li>
</ul>
</details>

request: add client files for ergonomic-tangible-algorithm-9206

---

terraform-v2/keycloak-dev/standard-clients/business-focused-explicit-product-9208.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://pointed-bran.com</li>
</ul>
</details>

request: add client files for business-focused-explicit-product-9208

---

terraform-v2/keycloak-dev/standard-clients/project-1-9209.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://serpentine-holiday.com</li>
</ul>
</details>

request: add client files for project-1-9209

---

terraform-v2/keycloak-dev/standard-clients/project-2-9210.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://terrible-vixen.info</li>
</ul>
</details>

request: add client files for project-2-9210

---

terraform-v2/keycloak-dev/standard-clients/project-3-9211.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://jumpy-alpenglow.net</li>
</ul>
</details>

request: add client files for project-3-9211

---

terraform-v2/keycloak-dev/standard-clients/project-4-9212.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://infatuated-printer.name</li>
</ul>
</details>

request: add client files for project-4-9212

---

terraform-v2/keycloak-dev/standard-clients/project-5-9213.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://empty-psychologist.name</li>
</ul>
</details>

request: add client files for project-5-9213

---

terraform-v2/keycloak-dev/standard-clients/project-6-9214.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://itchy-detective.info</li>
</ul>
</details>

request: add client files for project-6-9214

---

terraform-v2/keycloak-dev/standard-clients/project-7-9215.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://wide-dungarees.info</li>
</ul>
</details>

request: add client files for project-7-9215

---

terraform-v2/keycloak-dev/standard-clients/project-8-9216.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://internal-beach.org</li>
</ul>
</details>

request: add client files for project-8-9216

---

terraform-v2/keycloak-dev/standard-clients/project-9-9217.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://bronze-exception.org</li>
</ul>
</details>

request: add client files for project-9-9217

---

terraform-v2/keycloak-dev/standard-clients/project-10-9218.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://masculine-couch.net</li>
</ul>
</details>

request: add client files for project-10-9218

---

terraform-v2/keycloak-dev/standard-clients/project-11-9219.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://sweltering-jaw.biz</li>
</ul>
</details>

request: add client files for project-11-9219

---

terraform-v2/keycloak-dev/standard-clients/project-12-9220.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://bruised-neonate.com</li>
</ul>
</details>

request: add client files for project-12-9220

---

terraform-v2/keycloak-dev/standard-clients/project-13-9221.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://edible-extension.biz</li>
</ul>
</details>

request: add client files for project-13-9221

---

terraform-v2/keycloak-dev/standard-clients/project-14-9222.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://amused-feng.net</li>
</ul>
</details>

request: add client files for project-14-9222

---

terraform-v2/keycloak-dev/standard-clients/project-15-9223.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://oblong-beaver.com</li>
</ul>
</details>

request: add client files for project-15-9223

---

terraform-v2/keycloak-dev/standard-clients/project-16-9224.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://late-eyebrows.com</li>
</ul>
</details>

request: add client files for project-16-9224

---

terraform-v2/keycloak-dev/standard-clients/project-17-9225.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://faraway-eggplant.info</li>
</ul>
</details>

request: add client files for project-17-9225

---

terraform-v2/keycloak-dev/standard-clients/project-18-9226.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://messy-suffocation.info</li>
</ul>
</details>

request: add client files for project-18-9226

---

terraform-v2/keycloak-dev/standard-clients/project-19-9227.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://overdue-sentence.org</li>
</ul>
</details>

request: add client files for project-19-9227

---

terraform-v2/keycloak-dev/standard-clients/project-1-9228.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://absolute-entree.info</li>
</ul>
</details>

request: add client files for project-1-9228

---

terraform-v2/keycloak-dev/standard-clients/project-2-9229.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://novel-info.info</li>
</ul>
</details>

request: add client files for project-2-9229

---

terraform-v2/keycloak-dev/standard-clients/project-3-9230.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://yummy-mainland.net</li>
</ul>
</details>

request: add client files for project-3-9230

---

terraform-v2/keycloak-dev/standard-clients/project-4-9231.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://torn-mineshaft.biz</li>
</ul>
</details>

request: add client files for project-4-9231

---

terraform-v2/keycloak-dev/standard-clients/project-5-9232.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://dismal-revenue.name</li>
</ul>
</details>

request: add client files for project-5-9232

---

terraform-v2/keycloak-dev/standard-clients/project-6-9233.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://comfortable-volunteering.name</li>
</ul>
</details>

request: add client files for project-6-9233

---

terraform-v2/keycloak-dev/standard-clients/project-7-9234.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://major-fowl.biz</li>
</ul>
</details>

request: add client files for project-7-9234

---

terraform-v2/keycloak-dev/standard-clients/project-8-9235.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://adolescent-house.info</li>
</ul>
</details>

request: add client files for project-8-9235

---

terraform-v2/keycloak-dev/standard-clients/project-9-9236.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://annual-sledge.org</li>
</ul>
</details>

request: add client files for project-9-9236

---

terraform-v2/keycloak-dev/standard-clients/project-10-9237.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://thorough-yang.biz</li>
</ul>
</details>

request: add client files for project-10-9237

---

terraform-v2/keycloak-dev/standard-clients/project-11-9238.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://honored-conductor.biz</li>
</ul>
</details>

request: add client files for project-11-9238

---

terraform-v2/keycloak-dev/standard-clients/project-12-9239.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://remorseful-apology.org</li>
</ul>
</details>

request: add client files for project-12-9239

---

terraform-v2/keycloak-dev/standard-clients/project-13-9240.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://nonstop-chem.org</li>
</ul>
</details>

request: add client files for project-13-9240

---

terraform-v2/keycloak-dev/standard-clients/project-14-9241.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://worn-sneaker.com</li>
</ul>
</details>

request: add client files for project-14-9241

---

terraform-v2/keycloak-dev/standard-clients/project-15-9242.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://wide-joy.biz</li>
</ul>
</details>

request: add client files for project-15-9242

---

terraform-v2/keycloak-dev/standard-clients/project-16-9243.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://weird-illusion.com</li>
</ul>
</details>

request: add client files for project-16-9243

---

terraform-v2/keycloak-dev/standard-clients/project-17-9244.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://gaseous-dame.info</li>
</ul>
</details>

request: add client files for project-17-9244

---

terraform-v2/keycloak-dev/standard-clients/project-18-9245.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://arid-team.org</li>
</ul>
</details>

request: add client files for project-18-9245

---

terraform-v2/keycloak-dev/standard-clients/project-19-9246.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://woozy-antelope.biz</li>
</ul>
</details>

request: add client files for project-19-9246

---

terraform-v2/keycloak-dev/standard-clients/project-20-9247.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://winged-committee.org</li>
</ul>
</details>

request: add client files for project-20-9247

---

terraform-v2/keycloak-dev/standard-clients/test-saml-sign-asr-nk-03-9248.tf
terraform-v2/keycloak-prod/standard-clients/test-saml-sign-asr-nk-03-9248.tf
terraform-v2/keycloak-test/standard-clients/test-saml-sign-asr-nk-03-9248.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://example.com</li>
</ul>
</details>

request: add client files for test-saml-sign-asr-nk-03-9248

---

terraform-v2/keycloak-dev/standard-clients/new-int-9249.tf

request: add client files for new-int-9249

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-17-saml-9253.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-17-saml-9253.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-17-saml-9253

---

terraform-v2/keycloak-dev/standard-clients/future-proofed-mission-critical-leverage-9255.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://awesome-indication.biz</li>
</ul>
</details>

request: add client files for future-proofed-mission-critical-leverage-9255

---

terraform-v2/keycloak-dev/standard-clients/secured-dedicated-instruction-set-9256.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://spiteful-pillar.biz</li>
</ul>
</details>

request: add client files for secured-dedicated-instruction-set-9256

---

terraform-v2/keycloak-dev/standard-clients/project-1-9257.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://loyal-anarchist.biz</li>
</ul>
</details>

request: add client files for project-1-9257

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-9259.tf

request: add client files for tians-testing-9259

---

terraform-v2/keycloak-dev/standard-clients/project-1-9260.tf

<details>
<ul>✔️ Valid Redirect Urls<li>https://masculine-knife.name</li>
</ul>
</details>

request: add client files for project-1-9260

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2212-9262.tf

request: add client files for service-account-for-team-2212-9262

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2212-9149.tf

request: delete client files for service-account-for-team-2212-9149

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2316-9192.tf

request: delete client files for service-account-for-team-2316-9192

---

terraform-v2/keycloak-dev/standard-clients/training-2-create-request-oct-18-9263.tf

request: add client files for training-2-create-request-oct-18-9263

---

terraform-v2/keycloak-dev/standard-clients/tian-tesing-9265.tf

request: add client files for tian-tesing-9265

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-18-b-ce-id-prod-9266.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-18-b-ce-id-prod-9266.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-18-b-ce-id-prod-9266.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-18-b-ce-id-prod-9266

---

terraform-v2/keycloak-dev/standard-clients/sso-dashboard-9267.tf
terraform-v2/keycloak-prod/standard-clients/sso-dashboard-9267.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca/*</li><li>https://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca/*</li><li>https://sso-grafana-sandbox.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>

request: add client files for sso-dashboard-9267

---

terraform-v2/keycloak-dev/standard-clients/project-1-9269.tf

<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>http://well-made-ambience.name</li>
</ul>
</details>

request: add client files for project-1-9269

---

terraform-v2/keycloak-dev/standard-clients/project-1-9284.tf
terraform-v2/keycloak-prod/standard-clients/project-1-9284.tf
terraform-v2/keycloak-test/standard-clients/project-1-9284.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://measly-jellybeans.net</li>
</ul>
</details>

request: add client files for project-1-9284

---

terraform-v2/keycloak-dev/standard-clients/project-1-9285.tf
terraform-v2/keycloak-prod/standard-clients/project-1-9285.tf
terraform-v2/keycloak-test/standard-clients/project-1-9285.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>https://optimal-overload.org</li>
</ul>
</details>

request: add client files for project-1-9285

---

terraform-v2/keycloak-dev/standard-clients/project-1-9286.tf
terraform-v2/keycloak-prod/standard-clients/project-1-9286.tf
terraform-v2/keycloak-test/standard-clients/project-1-9286.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://long-dromedary.net</li>
</ul>
</details>

request: add client files for project-1-9286

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9288.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9288.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9288

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9290.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9290.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9290

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9291.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9291.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9291

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9292.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9292.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9292

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9293.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9293.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9293

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9294.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9294.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9294

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9297.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9297.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9297

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9299.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9299.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9299

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9301.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9301.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9301

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9302.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9302.tf

request: add client files for create-oidc-2-team-9302

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9304.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9304.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9304

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9305.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9305.tf

request: add client files for create-oidc-2-team-9305

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9306.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9306.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9306

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9309.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9309.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9309

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9310.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9310.tf

request: add client files for create-oidc-2-team-9310

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9311.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9311.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9311

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9312.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9312.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9312

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9313.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9313.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9313

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9314.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9314.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9314

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9315.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9315.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9315

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9316.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9316.tf

request: add client files for create-oidc-2-team-9316

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9317.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9317.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9317

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9318.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9318.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9318

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9319.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9319.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9319

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9320.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9320.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9320

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9321.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9321.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9321

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9322.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9322.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9322

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9323.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9323.tf

request: add client files for create-oidc-2-team-9323

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9324.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9324.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9324

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9325.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9325.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9325

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9326.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9326.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9326

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9327.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9327.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9327

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9328.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9328.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9328

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9329.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9329.tf

request: add client files for create-oidc-2-team-9329

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9330.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9330.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9330

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9331.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9331.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9331

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9332.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9332.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9332

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9333.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9333.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9333

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9335.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9335.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9335

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9336.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9336.tf

request: add client files for create-oidc-2-team-9336

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9338.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9338.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9338

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9339.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9339.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9339

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9340.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9340.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9340

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9341.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9341.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9341

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9342.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9342.tf

request: add client files for create-oidc-2-team-9342

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9343.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9343.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9343

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9344.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9344.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9344

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9345.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9345.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9345

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9346.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9346.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9346

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9347.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9347.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9347

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9348.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9348.tf

request: add client files for create-oidc-2-team-9348

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9349.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9349.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9349

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9350.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9350.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9350

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9351.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9351.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9351

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9352.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9352.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9352

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9354.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9354.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9354

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9356.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9356.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9356

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9358.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9358.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9358

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9359.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9359.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9359

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9360.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9360.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9360

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9361.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9361.tf

request: add client files for create-oidc-2-team-9361

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9362.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9362.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9362

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9363.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9363.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9363

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9364.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9364.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9364

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9365.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9365.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9365

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9366.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9366.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9366

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9367.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9367.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9367

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9368.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9368.tf

request: add client files for create-oidc-2-team-9368

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9369.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9369.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9369

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9370.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9370.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9370

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9371.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9371.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9371

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9372.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9372.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9372

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9373.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9373.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9373

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9374.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9374.tf

request: add client files for create-oidc-2-team-9374

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9375.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9375.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9375

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9376.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9376.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9376

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9377.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9377.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9377

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9378.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9378.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9378

---

terraform-v2/keycloak-dev/standard-clients/jon-s-intfor-jira-1069-9379.tf
terraform-v2/keycloak-prod/standard-clients/jon-s-intfor-jira-1069-9379.tf
terraform-v2/keycloak-test/standard-clients/jon-s-intfor-jira-1069-9379.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for jon-s-intfor-jira-1069-9379

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-23-multiple-id-ps-9381.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-23-multiple-id-ps-9381.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-23-multiple-id-ps-9381

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9406.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9406.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9406

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9407.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9407.tf

request: add client files for create-oidc-2-team-9407

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9408.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9408.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9408

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9409.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9409.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9409

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9410.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9410.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9410

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9411.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9411.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9411

---

terraform-v2/keycloak-dev/standard-clients/zorin-integration-oct-24-1-9412.tf

request: add client files for zorin-integration-oct-24-1-9412

---

terraform-v2/keycloak-dev/standard-clients/zorin-integration-oct-24-3-9414.tf

request: add client files for zorin-integration-oct-24-3-9414

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9416.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9416.tf

request: add client files for create-oidc-2-team-9416

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9417.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9417.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9417

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9418.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9418.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9418

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9419.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9419.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9419

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9420.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9420.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9420

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9421.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9421.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9421

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9422.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9422.tf

request: add client files for create-oidc-2-team-9422

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9423.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9423.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9423

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9424.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9424.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9424

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9425.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9425.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9425

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9426.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9426.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9426

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2278-9430.tf

request: add client files for service-account-for-team-2278-9430

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9431.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9431.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9431

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9432.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9432.tf

request: add client files for create-oidc-2-team-9432

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9433.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9433.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9433

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9434.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9434.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9434

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9435.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9435.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9435

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9436.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9436.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9436

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9438.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9438.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9438

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9439.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9439.tf

request: add client files for create-oidc-2-team-9439

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9440.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9440.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9440

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9441.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9441.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9441

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9442.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9442.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9442

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9443.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9443.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9443

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9444.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9444.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9444

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9446.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9446.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9446

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9447.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9447.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9447

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9448.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9448.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9448

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9449.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9449.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9449

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9450.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9450.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9450

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9451.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9451.tf

request: add client files for create-oidc-2-team-9451

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9452.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9452.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9452

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9453.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9453.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9453

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9454.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9454.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9454

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9455.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9455.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9455

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9456.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9456.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9456

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9457.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9457.tf

request: add client files for create-oidc-2-team-9457

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9458.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9458.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9458

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9459.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9459.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9459

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9461.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9461.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9461

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9462.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9462.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9462

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9463.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9463.tf

request: add client files for create-oidc-2-team-9463

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9464.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9464.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9464

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9465.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9465.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9465

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9467.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9467.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9467

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9469.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9469.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9469

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9470.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9470.tf

request: add client files for create-oidc-2-team-9470

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9471.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9471.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9471

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9472.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9472.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9472

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9473.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9473.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9473

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9474.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9474.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9474

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-27-vc-9475.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-27-vc-9475.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-27-vc-9475.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-27-vc-9475

---

terraform-v2/keycloak-dev/standard-clients/vc-test-9476.tf

request: add client files for vc-test-9476

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-27-no-vc-9477.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-27-no-vc-9477.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-27-no-vc-9477.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-27-no-vc-9477

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-27-vc-only-9478.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-27-vc-only-9478.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-27-vc-only-9478.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-27-vc-only-9478

---

terraform-v2/keycloak-dev/standard-clients/zorin-test-vc-oct-30-1-9479.tf

request: add client files for zorin-test-vc-oct-30-1-9479

---

terraform-v2/keycloak-dev/standard-clients/zorin-test-vc-oct-30-2-9480.tf
terraform-v2/keycloak-prod/standard-clients/zorin-test-vc-oct-30-2-9480.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for zorin-test-vc-oct-30-2-9480

---

terraform-v2/keycloak-dev/standard-clients/jon-example-app-vc-9481.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li>
</ul>
</details>

request: add client files for jon-example-app-vc-9481

---

terraform-v2/keycloak-dev/standard-clients/zorin-test-vc-oct-30-3-9482.tf
terraform-v2/keycloak-prod/standard-clients/zorin-test-vc-oct-30-3-9482.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for zorin-test-vc-oct-30-3-9482

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9483.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9483.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9483

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9485.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9485.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9485

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9486.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9486.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9486

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9487.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9487.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9487

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9488.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9488.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9488

---

terraform-v2/keycloak-dev/standard-clients/sso-min-io-9506.tf
terraform-v2/keycloak-prod/standard-clients/sso-min-io-9506.tf

<details>
<ul>✔️ Valid Redirect Urls<li>http://sso-minio-sandbox.apps.gold.devops.gov.bc.ca/*</li><li>https://sso-minio-sandbox.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://sso-minio-sandbox.apps.gold.devops.gov.bc.ca/*</li><li>https://sso-minio-sandbox.apps.gold.devops.gov.bc.ca/*</li>
</ul>
</details>

request: add client files for sso-min-io-9506

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-31-vc-only-9507.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-31-vc-only-9507.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-31-vc-only-9507.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-31-vc-only-9507

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-31-b-ce-id-only-9508.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-31-b-ce-id-only-9508.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-31-b-ce-id-only-9508.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-31-b-ce-id-only-9508

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9509.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9509.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9509

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9510.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9510.tf

request: add client files for create-oidc-2-team-9510

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9511.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9511.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9511

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9512.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9512.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9512

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9513.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9513.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9513

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9514.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9514.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9514

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-31-git-hub-only-9515.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-31-git-hub-only-9515.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-31-git-hub-only-9515.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-31-git-hub-only-9515

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-10-31-b-ce-id-and-git-hub-9516.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-10-31-b-ce-id-and-git-hub-9516.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-10-31-b-ce-id-and-git-hub-9516.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-10-31-b-ce-id-and-git-hub-9516

---

terraform-v2/keycloak-dev/standard-clients/bceid-prod-9517.tf
terraform-v2/keycloak-prod/standard-clients/bceid-prod-9517.tf

<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://example</li>
</ul>
</details>

request: add client files for bceid-prod-9517

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9518.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9518.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9518

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9519.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9519.tf

request: add client files for create-oidc-2-team-9519

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9520.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9520.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9520

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9521.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9521.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9521

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9522.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9522.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9522

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9523.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9523.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9523

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9524.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9524.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9524

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9525.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9525.tf

request: add client files for create-oidc-2-team-9525

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9526.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9526.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9526

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9527.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9527.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9527

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9528.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9528.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9528

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9529.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9529.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9529

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9530.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9530.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9530

---

terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2278-9430.tf

request: delete client files for service-account-for-team-2278-9430

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9531.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9531.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9531

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9532.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9532.tf

request: add client files for create-oidc-2-team-9532

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9533.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9533.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9533

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9534.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9534.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9534

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9536.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9536.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9536

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9537.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9537.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9537

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9538.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9538.tf

request: add client files for create-oidc-2-team-9538

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9539.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9539.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9539

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9540.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9540.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9540

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9541.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9541.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9541

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9542.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9542.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9542

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9544.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9544.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9544

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9545.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9545.tf

request: add client files for create-oidc-2-team-9545

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9546.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9546.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9546

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9547.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9547.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9547

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9548.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9548.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9548

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9549.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9549.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9549

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9551.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9551.tf

request: add client files for create-oidc-2-team-9551

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9553.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9553.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9553

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9554.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9554.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9554

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9555.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9555.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9555

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9556.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9556.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9556

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9557.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9557.tf

request: add client files for create-oidc-2-team-9557

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9559.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9559.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9559

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9560.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9560.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9560

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9561.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9561.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9561

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9562.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9562.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9562

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9563.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9563.tf

request: add client files for create-oidc-2-team-9563

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9564.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9564.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9564

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9565.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9565.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9565

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9566.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9566.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9566

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9567.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9567.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9567

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9568.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9568.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9568

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9569.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9569.tf

request: add client files for create-oidc-2-team-9569

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9570.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9570.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9570

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9571.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9571.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9571

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9572.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9572.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9572

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9573.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9573.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9573

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9575.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9575.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9575

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9576.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9576.tf

request: add client files for create-oidc-2-team-9576

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9577.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9577.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9577

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9578.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9578.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9578

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9579.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9579.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9579

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9580.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9580.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9580

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9581.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9581.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9581

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9582.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9582.tf

request: add client files for create-oidc-2-team-9582

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9583.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9583.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9583

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9584.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9584.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9584

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9585.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9585.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9585

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9586.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9586.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9586

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9587.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9587.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9587

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9588.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9588.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9588

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9589.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9589.tf

request: add client files for create-oidc-2-team-9589

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9590.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9590.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9590

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9591.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9591.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9591

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9592.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9592.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9592

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-1-dc-9593.tf

request: add client files for tians-testing-11-1-dc-9593

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9601.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9601.tf

<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://dev.com</li><li>https://test.com</li>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9601

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9602.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9602.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9602

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9603.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9603.tf

request: add client files for create-oidc-2-team-9603

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9604.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9604.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9604

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9605.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9605.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9605

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9606.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9606.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9606

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9607.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9607.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9607

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9608.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9608.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9608

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9609.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9609.tf

request: add client files for create-oidc-2-team-9609

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9610.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9610.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9610

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9611.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9611.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9611

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9612.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9612.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9612

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9614.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9614.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9614

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9616.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9616.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9616

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9618.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9618.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9618

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9620.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9620.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9620

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9621.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9621.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9621

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9622.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9622.tf

request: add client files for create-oidc-2-team-9622

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9623.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9623.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9623

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9624.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9624.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9624

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9625.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9625.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9625

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9627.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9627.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9627

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9628.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9628.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9628

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9629.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9629.tf

request: add client files for create-oidc-2-team-9629

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9630.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9630.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9630

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9631.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9631.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9631

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9632.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9632.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9632

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9633.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9633.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9633

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9634.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9634.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9634

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9635.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9635.tf

request: add client files for create-oidc-2-team-9635

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9636.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9636.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9636

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9637.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9637.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9637

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9638.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9638.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9638

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9640.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9640.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9640

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9641.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9641.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9641

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9642.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9642.tf

request: add client files for create-oidc-2-team-9642

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9643.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9643.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9643

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9644.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9644.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9644

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9645.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9645.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9645

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9646.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9646.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9646

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9647.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9647.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9647

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9648.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9648.tf

request: add client files for create-oidc-2-team-9648

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9649.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9649.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9649

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9650.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9650.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9650

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9651.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9651.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9651

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-2-dc-only-9652.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-2-dc-only-9652.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-11-2-dc-only-9652.tf

<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-2-dc-only-9652

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-2-idir-only-9653.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-2-idir-only-9653.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-11-2-idir-only-9653.tf

<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-2-idir-only-9653

---

terraform-v2/keycloak-dev/standard-clients/vc-bceid-github-9654.tf
terraform-v2/keycloak-prod/standard-clients/vc-bceid-github-9654.tf

<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://a</li>
</ul>
</details>

request: add client files for vc-bceid-github-9654

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9655.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9655.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9655

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9656.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9656.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9656

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9657.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9657.tf

request: add client files for create-oidc-2-team-9657

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9658.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9658.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9658

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9659.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9659.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9659

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9660.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9660.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9660

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-2-dc-only-9661.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-2-dc-only-9661.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-11-2-dc-only-9661.tf

<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>https://bcgov.github.io/keycloak-example-apps/*</li>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-2-dc-only-9661

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-2-dc-b-ce-id-git-hub-9662.tf

request: add client files for tians-testing-11-2-dc-b-ce-id-git-hub-9662

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-2-git-hub-only-9663.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-2-git-hub-only-9663.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-11-2-git-hub-only-9663.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-2-git-hub-only-9663

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9664.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9664.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9664

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9665.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9665.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9665

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9666.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9666.tf

request: add client files for create-oidc-2-team-9666

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9667.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9667.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9667

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9668.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9668.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9668

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9669.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9669.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9669

---

terraform-v2/keycloak-dev/standard-clients/idir-conf-9670.tf

<details>
<ul>✔️ Valid Redirect Urls<li>*</li><li>http://localhost:3000</li>
</ul>
</details>

request: add client files for idir-conf-9670

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9671.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9671.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9671

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9672.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9672.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9672

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9673.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9673.tf

request: add client files for create-oidc-2-team-9673

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9674.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9674.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9674

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9675.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9675.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9675

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9676.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9676.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9676

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-2-dc-only-2-9677.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-2-dc-only-2-9677.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-2-dc-only-2-9677

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9678.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9678.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9678

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9679.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9679.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9679

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9680.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9680.tf

request: add client files for create-oidc-2-team-9680

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9681.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9681.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9681

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9682.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9682.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9682

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9683.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9683.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9683

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9684.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9684.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9684

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9685.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9685.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9685

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9686.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9686.tf

request: add client files for create-oidc-2-team-9686

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9687.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9687.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9687

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9688.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9688.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9688

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9689.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9689.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9689

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9690.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9690.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9690

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9691.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9691.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9691

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9692.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9692.tf

request: add client files for create-oidc-2-team-9692

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9693.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9693.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9693

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9694.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9694.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9694

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9695.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9695.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9695

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9696.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9696.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9696

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9698.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9698.tf

request: add client files for create-oidc-2-team-9698

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9697.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9697.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9697

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9699.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9699.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9699

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9700.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9700.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9700

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9701.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9701.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9701

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9702.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9702.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9702

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9703.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9703.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9703

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9704.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9704.tf

request: add client files for create-oidc-2-team-9704

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9705.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9705.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9705

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9706.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9706.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9706

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9707.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9707.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9707

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9708.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9708.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9708

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9709.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9709.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9709

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9710.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9710.tf

request: add client files for create-oidc-2-team-9710

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9711.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9711.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9711

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9712.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9712.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9712

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9713.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9713.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9713

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-3-b-ce-id-only-9714.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-3-b-ce-id-only-9714.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-11-3-b-ce-id-only-9714.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-3-b-ce-id-only-9714

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9715.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9715.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9715

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9716.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9716.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9716

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9717.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9717.tf

request: add client files for create-oidc-2-team-9717

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9718.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9718.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9718

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9719.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9719.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9719

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9720.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9720.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9720

---

terraform-v2/keycloak-dev/standard-clients/vc-bceid-9721.tf
terraform-v2/keycloak-prod/standard-clients/vc-bceid-9721.tf

<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://a</li>
</ul>
</details>

request: add client files for vc-bceid-9721

---

terraform-v2/keycloak-dev/standard-clients/tians-testing-11-3-idir-b-ce-id-git-hub-dc-9722.tf
terraform-v2/keycloak-prod/standard-clients/tians-testing-11-3-idir-b-ce-id-git-hub-dc-9722.tf
terraform-v2/keycloak-test/standard-clients/tians-testing-11-3-idir-b-ce-id-git-hub-dc-9722.tf

<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for tians-testing-11-3-idir-b-ce-id-git-hub-dc-9722

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9723.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9723.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9723

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9724.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9724.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9724

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9725.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9725.tf

request: add client files for create-oidc-2-team-9725

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9726.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9726.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9726

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9727.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9727.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9727

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9728.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9728.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9728

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9729.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9729.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9729

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9730.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9730.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9730

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9731.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9731.tf

request: add client files for create-oidc-2-team-9731

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9732.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9732.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9732

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9733.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9733.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9733

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9734.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9734.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9734

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9735.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9735.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9735

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9737.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9737.tf

request: add client files for create-oidc-2-team-9737

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9738.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9738.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9738

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9739.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9739.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9739

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9740.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9740.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9740

---

terraform-v2/keycloak-dev/standard-clients/jon-vc-confidential-test-2-9741.tf

request: add client files for jon-vc-confidential-test-2-9741

---

terraform-v2/keycloak-dev/standard-clients/jon-standard-dc-test-9743.tf

request: add client files for jon-standard-dc-test-9743

---

terraform-v2/keycloak-dev/standard-clients/vc-test-jonl-9747.tf
terraform-v2/keycloak-prod/standard-clients/vc-test-jonl-9747.tf

<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://a</li>
</ul>
</details>

request: add client files for vc-test-jonl-9747

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9750.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9750.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9750

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9751.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9751.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9751

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9752.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9752.tf

request: add client files for create-oidc-2-team-9752

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9753.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9753.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9753

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9754.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9754.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9754

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9755.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9755.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9755

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9758.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9758.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9758

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9759.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9759.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9759

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9760.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9760.tf

request: add client files for create-oidc-2-team-9760

---

terraform-v2-custom/keycloak-dev/custom-realms/nk-realm.tf
terraform-v2-custom/keycloak-prod/custom-realms/nk-realm.tf
terraform-v2-custom/keycloak-test/custom-realms/nk-realm.tf

Created through request created at realm registry for a custom realm nk-realm

feat: create custom realm nk-realm

---

terraform-v2-custom/keycloak-dev/custom-realms/nk-test-realm.tf
terraform-v2-custom/keycloak-prod/custom-realms/nk-test-realm.tf
terraform-v2-custom/keycloak-test/custom-realms/nk-test-realm.tf

Created through request created at realm registry for a custom realm nk-test-realm

feat: create custom realm nk-test-realm

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9765.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9765.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9765

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9766.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9766.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9766

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9767.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9767.tf

request: add client files for create-oidc-2-team-9767

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9768.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9768.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9768

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9770.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9770.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9770

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9771.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9771.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9771

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9772.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9772.tf

request: add client files for create-oidc-2-team-9772

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9773.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9773.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9773

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9774.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9774.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9774

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9776.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9776.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9776

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9777.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9777.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9777

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9778.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9778.tf

request: add client files for create-oidc-2-team-9778

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9779.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9779.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9779

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9780.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9780.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9780

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9781.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9781.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9781

---

terraform-v2-custom/keycloak-dev/custom-realms/nk-realm-01.tf
terraform-v2-custom/keycloak-prod/custom-realms/nk-realm-01.tf
terraform-v2-custom/keycloak-test/custom-realms/nk-realm-01.tf

Created through request created at realm registry for a custom realm nk-realm-01

feat: create custom realm nk-realm-01

---

terraform-v2/keycloak-dev/standard-clients/test-nov-15-9782.tf

request: add client files for test-nov-15-9782

---

terraform-v2-custom/keycloak-dev/custom-realms/jon-test-1.tf

Created through request created at realm registry for a custom realm jon-test-1

feat: create custom realm jon-test-1

---

terraform-v2/keycloak-dev/standard-clients/roland-test-9783.tf
terraform-v2/keycloak-test/standard-clients/roland-test-9783.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for roland-test-9783

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9784.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9784.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-no-team-9784

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9785.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9785.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-no-team-9785

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-9787.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-9787.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-no-team-9787

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9788.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9788.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-no-team-9788

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9789.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9789.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-no-team-to-team-9789

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9790.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9790.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9790

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9791.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9791.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9791

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9792.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9792.tf

request: add client files for create-oidc-2-team-9792

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9793.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9793.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9793

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9794.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9794.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9794

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9795.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9795.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9795

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9796.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9796.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-no-team-9796

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9797.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9797.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-no-team-to-team-9797

---

terraform-v2/keycloak-dev/standard-clients/rstens-serviceaccount-9799.tf

request: add client files for rstens-serviceaccount-9799

---

terraform-v2/keycloak-dev/standard-clients/roland-test-9800.tf

request: add client files for roland-test-9800

---

terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm.tf
terraform-v2-custom/keycloak-test/custom-realms/tian-test-realm.tf

Created through request created at realm registry for a custom realm tian-test-realm

feat: create custom realm tian-test-realm

---

terraform-v2-custom/keycloak-dev/custom-realms/tian-realm-11-17.tf
terraform-v2-custom/keycloak-test/custom-realms/tian-realm-11-17.tf

Created through request created at realm registry for a custom realm tian-realm-11-17

feat: create custom realm tian-realm-11-17

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9801.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9801.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9801

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9802.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9802.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9802

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9803.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9803.tf

request: add client files for create-oidc-2-team-9803

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9805.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9805.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9805

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9806.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9806.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9806

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9807.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9807.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9807

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9808.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9808.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-no-team-9808

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9809.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9809.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-no-team-to-team-9809

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9810.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9810.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-team-9810

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9811.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9811.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-public-team-confidential-9811

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9812.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9812.tf

request: add client files for create-oidc-2-team-9812

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9813.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9813.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-3-team-9813

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9814.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9814.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-team-9814

---

terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9815.tf
terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9815.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-2-team-9815

---

terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9816.tf
terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9816.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-oidc-1-no-team-9816

---

terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9817.tf
terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9817.tf

<details>
</ul>
</details>
<details>
</ul>
</details>

request: add client files for create-saml-1-no-team-to-team-9817
