bcgov/sso-terraform-dev

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9818.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9818.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9818

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9819.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9819.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9819

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9820.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9820.tf
> request: add client files for create-oidc-2-team-9820

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9821.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9821.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9821

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9822.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9822.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9822

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9823.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9823.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9823

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9824.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9824.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9824

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9825.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9825.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9825

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9826.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9826.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9826

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9827.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9827.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9827

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9828.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9828.tf
> request: add client files for create-oidc-2-team-9828

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9829.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9829.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9829

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9830.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9830.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9830

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9831.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9831.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9831

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9832.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9832.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9832

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9833.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9833.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9833

- terraform-v2/keycloak-dev/standard-clients/test-roland-9835.tf
> request: add client files for test-roland-9835

- terraform-v2-custom/keycloak-dev/custom-realms/tian-realm-11-20.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-realm-11-20.tf
Created through request created at realm registry for a custom realm tian-realm-11-20
> feat: create custom realm tian-realm-11-20

- terraform-v2-custom/keycloak-dev/custom-realms/tian-realm-11-21.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-realm-11-21.tf
Created through request created at realm registry for a custom realm tian-realm-11-21
> feat: create custom realm tian-realm-11-21

- terraform-v2-custom/keycloak-dev/custom-realms/tian-realm-admin-test.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-realm-admin-test.tf
Created through request created at realm registry for a custom realm tian-realm-admin-test
> feat: create custom realm tian-realm-admin-test

- terraform-v2-custom/keycloak-dev/custom-realms/tian-admin-test-1121.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-admin-test-1121.tf
Created through request created at realm registry for a custom realm tian-admin-test-1121
> feat: create custom realm tian-admin-test-1121

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2379-9839.tf
> request: add client files for service-account-for-team-2379-9839

- terraform-v2/keycloak-dev/standard-clients/test-automation-do-not-delete-9840.tf
> request: add client files for test-automation-do-not-delete-9840

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2788-9841.tf
> request: add client files for service-account-for-team-2788-9841

- terraform-v2-custom/keycloak-prod/custom-realms/tian-test-realm-prod-1121.tf
Created through request created at realm registry for a custom realm tian-test-realm-prod-1121
> feat: create custom realm tian-test-realm-prod-1121

- terraform-v2-custom/keycloak-dev/custom-realms/nov-21-test-1.tf
- terraform-v2-custom/keycloak-prod/custom-realms/nov-21-test-1.tf
Created through request created at realm registry for a custom realm nov-21-test-1
> feat: create custom realm nov-21-test-1

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9843.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9843.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9843

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9844.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9844.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9844

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9845.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9845.tf
> request: add client files for create-oidc-2-team-9845

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9846.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9846.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9846

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9847.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9847.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9847

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9848.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9848.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9848

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9849.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9849.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9849

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9850.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9850.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9850

- terraform-v2/keycloak-dev/standard-clients/demo-test-9851.tf
> request: add client files for demo-test-9851

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9852.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9852.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9852

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9853.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9853.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9853

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9854.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9854.tf
> request: add client files for create-oidc-2-team-9854

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9855.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9855.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9855

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9856.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9856.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9856

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9857.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9857.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9857

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9858.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9858.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9858

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9859.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9859.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9859

- terraform-v2-custom/keycloak-dev/custom-realms/new-test.tf
Created through request created at realm registry for a custom realm new-test
> feat: create custom realm new-test

- terraform-v2/keycloak-dev/standard-clients/jon-test-9860.tf
> request: add client files for jon-test-9860

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-2736-9862.tf
> request: add client files for service-account-for-team-2736-9862

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9863.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9863.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9863

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9864.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9864.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9864

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9865.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9865.tf
> request: add client files for create-oidc-2-team-9865

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9866.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9866.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9866

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9867.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9867.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9867

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9868.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9868.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9868

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9869.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9869.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9869

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9870.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9870.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9870

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-1122-approve.tf
Created through request created at realm registry for a custom realm tian-test-realm-1122-approve
> feat: create custom realm tian-test-realm-1122-approve

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9871.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9871.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9871

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9872.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9872.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9872

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9873.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9873.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9873

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9874.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9874.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9874

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9875.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9875.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9875

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9876.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9876.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9876

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9877.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9877.tf
> request: add client files for create-oidc-2-team-9877

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9878.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9878.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9878

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9880.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9880.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9880

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9881.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9881.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9881

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9882.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9882.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9882

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9883.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9883.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9883

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9884.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9884.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9884

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9885.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9885.tf
> request: add client files for create-oidc-2-team-9885

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9886.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9886.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9886

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9887.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9887.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9887

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9888.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9888.tf
> request: add client files for create-oidc-2-team-9888

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9889.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9889.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9889

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9890.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9890.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9890

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9891.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9891.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9891

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9892.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9892.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9892

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9893.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9893.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9893

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9894.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9894.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9894

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9895.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9895.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9895

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9896.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9896.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9896

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9897.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9897.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9897

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9898.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9898.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9898

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9899.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9899.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9899

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9900.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9900.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9900

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9901.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9901.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9901

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9903.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9903.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9903

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9904.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9904.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9904

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9905.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9905.tf
> request: add client files for create-oidc-2-team-9905

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9906.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9906.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9906

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9908.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9908.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9908

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9909.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9909.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9909

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9910.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9910.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9910

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9911.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9911.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9911

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9912.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9912.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9912

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9913.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9913.tf
> request: add client files for create-oidc-2-team-9913

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9914.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9914.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9914

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9915.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9915.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9915

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9916.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9916.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9916

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9917.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9917.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9917

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9918.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9918.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9918

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9920.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9920.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9920

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9921.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9921.tf
> request: add client files for create-oidc-2-team-9921

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9922.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9922.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9922

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9923.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9923.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9923

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9924.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9924.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9924

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9925.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9925.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9925

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9926.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9926.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9926

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9927.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9927.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9927

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9928.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9928.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9928

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9929.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9929.tf
> request: add client files for create-oidc-2-team-9929

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9930.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9930.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9930

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9931.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9931.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9931

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9932.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9932.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9932

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9933.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9933.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9933

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9934.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9934.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9934

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9935.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9935.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9935

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9936.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9936.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9936

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9937.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9937.tf
> request: add client files for create-oidc-2-team-9937

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9938.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9938.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9938

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9939.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9939.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9939

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9940.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9940.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9940

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9941.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9941.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9941

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9942.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9942.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9942

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-23-23-additional-field-9944.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-23-23-additional-field-9944.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-11-23-23-additional-field-9944

- terraform-v2/keycloak-dev/standard-clients/empty-other-9945.tf
> request: add client files for empty-other-9945

- terraform-v2/keycloak-dev/standard-clients/tians-another-test-11-23-23-9946.tf
- terraform-v2/keycloak-prod/standard-clients/tians-another-test-11-23-23-9946.tf
- terraform-v2/keycloak-test/standard-clients/tians-another-test-11-23-23-9946.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-another-test-11-23-23-9946

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-23-23-additional-field-2-9947.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-11-23-23-additional-field-2-9947.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-11-23-23-additional-field-2-9947.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-11-23-23-additional-field-2-9947

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-11-24.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-test-realm-11-24.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-test-realm-11-24.tf
Created through request created at realm registry for a custom realm tian-test-realm-11-24
> feat: create custom realm tian-test-realm-11-24

- terraform-v2/keycloak-dev/standard-clients/demo-11-29-9948.tf
> request: add client files for demo-11-29-9948

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9950.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9950.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9950

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9951.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9951.tf
> request: add client files for create-oidc-2-team-9951

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9955.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9955.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9955

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9956.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9956.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9956

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9957.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9957.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9957

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9958.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9958.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9958

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9959.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9959.tf
> request: add client files for create-oidc-2-team-9959

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9962.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9962.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9962

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9963.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9963.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9963

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9964.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9964.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9964

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9966.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9966.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9966

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9968.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9968.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9968

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9969.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9969.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9969

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9970.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9970.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9970

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9971.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9971.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9971

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9972.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9972.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9972

- terraform-v2/keycloak-dev/standard-clients/tians-testing-11-27-service-account-9973.tf
> request: add client files for tians-testing-11-27-service-account-9973

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9974.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9974.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9974

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9975.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9975.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9975

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9976.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9976.tf
> request: add client files for create-oidc-2-team-9976

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9977.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9977.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9977

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9978.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9978.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9978

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9979.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9979.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9979

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9980.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9980.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9980

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9981.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9981.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9981

- terraform-v2/keycloak-dev/standard-clients/test-9982.tf
> request: add client files for test-9982

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9983.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9983.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9983

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9984.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9984.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9984

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9985.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9985.tf
> request: add client files for create-oidc-2-team-9985

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9986.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9986.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9986

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9987.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9987.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9987

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-9988.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-9988.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-9988

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-9989.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-9989.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-9989

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-9990.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-9990.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-9990

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-9995.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-9995.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-9995

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-9996.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-9996.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-9996

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-9997.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-9997.tf
> request: add client files for create-oidc-2-team-9997

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-9998.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-9998.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-9998

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-9999.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-9999.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-9999

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10001.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10001.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10001

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10002.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10002.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10002

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10003.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10003.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10003

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10005.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10005.tf
> request: add client files for create-oidc-2-team-10005

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10006.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10006.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10006

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10007.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10007.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10007

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10008.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10008.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10008

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10009.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10009.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10009

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10010.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10010.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10010

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10011.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10011.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10011

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10012.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10012.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10012

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10013.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10013.tf
> request: add client files for create-oidc-2-team-10013

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10014.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10014.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10014

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10015.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10015.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10015

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10016.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10016.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10016

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10017.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10017.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10017

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10018.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10018.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10018

- terraform-v2/keycloak-dev/standard-clients/test-10019.tf
> request: add client files for test-10019

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10022.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10022.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10022

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10023.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10023.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10023

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10024.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10024.tf
> request: add client files for create-oidc-2-team-10024

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10025.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10025.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10025

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10026.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10026.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10026

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10028.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10028.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10028

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10029.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10029.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10029

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10030.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10030.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10030

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10031.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10031.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10031

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10032.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10032.tf
> request: add client files for create-oidc-2-team-10032

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10033.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10033.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10033

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10034.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10034.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10034

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10035.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10035.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10035

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10036.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10036.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10036

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10037.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10037.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10037

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-11-30.tf
Created through request created at realm registry for a custom realm tian-test-realm-11-30
> feat: create custom realm tian-test-realm-11-30

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10043.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10043.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10043

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10044.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10044.tf
> request: add client files for create-oidc-2-team-10044

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10045.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10045.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10045

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10046.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10046.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10046

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10048.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10048.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10048

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10049.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10049.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10049

- terraform-v2/keycloak-dev/standard-clients/roles-0001-azure-browser-oidc-10050.tf
> request: add client files for roles-0001-azure-browser-oidc-10050

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10051.tf
> request: add client files for roles-0002-azure-browser-oidc-10051

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10053.tf
> request: add client files for roles-0002-azure-browser-oidc-10053

- terraform-v2/keycloak-dev/standard-clients/roles-0001-azure-browser-oidc-10054.tf
> request: add client files for roles-0001-azure-browser-oidc-10054

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10055.tf
> request: add client files for roles-0002-azure-browser-oidc-10055

- terraform-v2/keycloak-dev/standard-clients/azureidirtest-10056.tf
> request: add client files for azureidirtest-10056

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10059.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10059.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10059

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10060.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10060.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10060

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10061.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10061.tf
> request: add client files for create-oidc-2-team-10061

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10062.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10062.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10062

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10063.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10063.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10063

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10064.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10064.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10064

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10065.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10065.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10065

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10066.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10066.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10066

- terraform-v2/keycloak-dev/standard-clients/roles-0001-azure-browser-oidc-10067.tf
> request: add client files for roles-0001-azure-browser-oidc-10067

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10068.tf
> request: add client files for roles-0002-azure-browser-oidc-10068

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10070.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10070.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10070

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10072.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10072.tf
> request: add client files for create-oidc-2-team-10072

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10074.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10074.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10074

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10077.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10077.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10077

- terraform-v2/keycloak-dev/standard-clients/roles-0001-azure-browser-oidc-10079.tf
> request: add client files for roles-0001-azure-browser-oidc-10079

- terraform-v2/keycloak-dev/standard-clients/tians-testing-12-01-10069.tf
- terraform-v2/keycloak-prod/standard-clients/tians-testing-12-01-10069.tf
- terraform-v2/keycloak-test/standard-clients/tians-testing-12-01-10069.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for tians-testing-12-01-10069

- terraform-v2/keycloak-dev/standard-clients/roles-0001-azure-browser-oidc-10083.tf
> request: add client files for roles-0001-azure-browser-oidc-10083

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10084.tf
- terraform-v2/keycloak-prod/standard-clients/roles-0002-azure-browser-oidc-10084.tf
- terraform-v2/keycloak-test/standard-clients/roles-0002-azure-browser-oidc-10084.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://clear.biz</li>
</ul>
</details>
> request: add client files for roles-0002-azure-browser-oidc-10084

- terraform-v2/keycloak-dev/standard-clients/service-acct-10085.tf
> request: add client files for service-acct-10085

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10087.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10087.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10087

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10090.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10090.tf
> request: add client files for create-oidc-2-team-10090

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10091.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10091.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10091

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10092.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10092.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10092

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10095.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10095.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10095

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10097.tf
- terraform-v2/keycloak-prod/standard-clients/roles-0002-azure-browser-oidc-10097.tf
- terraform-v2/keycloak-test/standard-clients/roles-0002-azure-browser-oidc-10097.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://clear.biz</li>
</ul>
</details>
> request: add client files for roles-0002-azure-browser-oidc-10097

- terraform-v2/keycloak-dev/standard-clients/roles-0001-azure-browser-oidc-10098.tf
> request: add client files for roles-0001-azure-browser-oidc-10098

- terraform-v2/keycloak-dev/standard-clients/roles-0002-azure-browser-oidc-10099.tf
- terraform-v2/keycloak-prod/standard-clients/roles-0002-azure-browser-oidc-10099.tf
- terraform-v2/keycloak-test/standard-clients/roles-0002-azure-browser-oidc-10099.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://clear.biz</li>
</ul>
</details>
> request: add client files for roles-0002-azure-browser-oidc-10099

- terraform-v2/keycloak-dev/standard-clients/test-automation-do-not-delete-10100.tf
> request: add client files for test-automation-do-not-delete-10100

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10102.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10102.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10102

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10103.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10103.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10103

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10104.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10104.tf
> request: add client files for create-oidc-2-team-10104

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10105.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10105.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10105

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10106.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10106.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10106

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10107.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10107.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10107

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10109.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10109.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10109

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10111.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10111.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10111

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10113.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10113.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10113

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10114.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10114.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10114

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10115.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10115.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10115

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10117.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10117.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10117

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10118.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10118.tf
> request: add client files for create-oidc-2-team-10118

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10119.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10119.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10119

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10120.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10120.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10120

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10122.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10122.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10122

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10123.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10123.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10123

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-3.tf
Created through request created at realm registry for a custom realm jon-test-3
> feat: create custom realm jon-test-3

- terraform-v2/keycloak-dev/standard-clients/zorin-test-dec-4-10125.tf
> request: add client files for zorin-test-dec-4-10125

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10129.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10129.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10129

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10130.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10130.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10130

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10131.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10131.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10131

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10132.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10132.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-git-hub-bc-gov-10132

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10133.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10133.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10133

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10134.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10134.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10134

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10136.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10136.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-azure-i-10136

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10137.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10137.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10137

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-git-hub-10138.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-git-hub-10138.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-git-hub-10138

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10139.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10139.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10139

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-idir-10140.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-idir-10140.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-idir-10140

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10141.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10141.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10141

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10142.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10142.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10142

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10143.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10143.tf
> request: add client files for role-test-oidc-service-account-idir-10143

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10144.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10144.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10144

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-azure-idir-10145.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-azure-idir-10145.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-azure-idir-10145

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10148.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10148.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10148

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10149.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10149.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10149

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10150.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10150.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10150

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-azure-i-10151.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-azure-i-10151.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-azure-i-10151

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-git-hub-10153.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-git-hub-10153.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-git-hub-10153

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10154.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10154.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10154

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-idir-10155.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-idir-10155.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-idir-10155

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-service-account-azure-idir-10156.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-service-account-azure-idir-10156.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-service-account-azure-idir-10156

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10159.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10159.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10159

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10160.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10160.tf
> request: add client files for create-oidc-2-team-10160

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10161.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10161.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10161

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10162.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10162.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10162

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10163.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10163.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10163

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10164.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10164.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10164

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10165.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10165.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10165

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10166.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10166.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10166

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10167.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10167.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10167

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10169.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10169.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-git-hub-bc-gov-10169

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10170.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10170.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10170

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10171.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10171.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10171

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10172.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10172.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10172

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10173.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10173.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-azure-i-10173

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10174.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10174.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10174

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-idir-10177.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-idir-10177.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-idir-10177

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10179.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10179.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10179

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10181.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10181.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10181

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-azure-idir-10182.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-azure-idir-10182.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-azure-idir-10182

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10184.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10184.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10184

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10185.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10185.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10185

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10186.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10186.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10186

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10187.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10187.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10187

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-azure-i-10188.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-azure-i-10188.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-azure-i-10188

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10189.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10189.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10189

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-git-hub-10190.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-git-hub-10190.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-git-hub-10190

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10191.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10191.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10191

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-idir-10192.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-idir-10192.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-idir-10192

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-azure-idir-10193.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-azure-idir-10193.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-azure-idir-10193

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-git-hub-bc-gov-10194.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-git-hub-bc-gov-10194.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-git-hub-bc-gov-10194

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10196.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10196.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10196

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10197.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10197.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10197

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10198.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10198.tf
> request: add client files for create-oidc-2-team-10198

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10199.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10199.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10199

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10200.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10200.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10200

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10201.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10201.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10201

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10202.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10202.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10202

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10203.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10203.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10203

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10204.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10204.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10204

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10205.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10205.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10205

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10206.tf
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10206

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10207.tf
> request: add client files for role-test-oidc-both-confidential-git-hub-bc-gov-10207

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10208.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10208.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10208

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10209.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10209.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10209

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10210.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10210.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10210

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10211.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10211.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-azure-i-10211

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10212.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10212

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-git-hub-10213.tf
> request: add client files for role-test-oidc-browser-login-confidential-git-hub-10213

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10214.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10214.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10214

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-idir-10215.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-idir-10215.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-idir-10215

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10216.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10216.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10216

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10218.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10218.tf
> request: add client files for role-test-oidc-service-account-idir-10218

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10219.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10219.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10219

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-azure-idir-10220.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-azure-idir-10220.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-azure-idir-10220

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-git-hub-bc-gov-10221.tf
> request: add client files for role-test-saml-both-public-git-hub-bc-gov-10221

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10222.tf
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10222

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10223.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10223.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10223

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10224.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10224.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10224

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10225.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10225.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10225

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10227.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10227

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-git-hub-10228.tf
> request: add client files for role-test-saml-browser-login-confidential-git-hub-10228

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10229.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10229.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10229

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-azure-idir-10231.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-azure-idir-10231.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-azure-idir-10231

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-git-hub-bc-gov-10232.tf
> request: add client files for role-test-saml-git-hub-bc-gov-10232

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10235.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10235.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10235

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10236.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10236.tf
> request: add client files for create-oidc-2-team-10236

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10237.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10237.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10237

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10238.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10238.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10238

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10239.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10239.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10239

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10240.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10240.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10240

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10242.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10242.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10242

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10243.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10243.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10243

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10244.tf
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10244

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10245.tf
> request: add client files for role-test-oidc-both-confidential-git-hub-bc-gov-10245

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10246.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10246.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10246

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10247.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10247.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10247

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10248.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10248.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10248

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10249.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10249.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-azure-i-10249

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-idir-10253.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-idir-10253.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-idir-10253

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10254.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10254.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10254

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10255.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10255

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10256.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10256.tf
> request: add client files for role-test-oidc-service-account-idir-10256

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10257.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10257.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10257

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-azure-idir-10258.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-azure-idir-10258.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-azure-idir-10258

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-git-hub-bc-gov-10259.tf
> request: add client files for role-test-saml-both-public-git-hub-bc-gov-10259

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10260.tf
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10260

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10261.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10261.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10261

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10262.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10262.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10262

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10263.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10263.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10263

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-azure-i-10264.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-azure-i-10264.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-azure-i-10264

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10265.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10265

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-git-hub-10266.tf
> request: add client files for role-test-saml-browser-login-confidential-git-hub-10266

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10267.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10267.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10267

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-azure-idir-10269.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-azure-idir-10269.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-azure-idir-10269

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-git-hub-bc-gov-10270.tf
> request: add client files for role-test-saml-git-hub-bc-gov-10270

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-idir-10271.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-idir-10271.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-idir-10271

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10272.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10272.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10272

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10273.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10273.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10273

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10274.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10274.tf
> request: add client files for create-oidc-2-team-10274

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10276.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10276.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10276

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10277.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10277.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10277

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10278.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10278.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10278

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10279.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10279.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10279

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10281.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10281.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10281

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10282.tf
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10282

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10284.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10284.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10284

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10285.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10285.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10285

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10287.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10287.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-azure-i-10287

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10288.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10288

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-git-hub-10289.tf
> request: add client files for role-test-oidc-browser-login-confidential-git-hub-10289

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10290.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10290.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10290

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10292.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10292.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10292

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10293.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10293

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10295.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10295.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10295

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-azure-idir-10296.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-azure-idir-10296.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-azure-idir-10296

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-git-hub-bc-gov-10297.tf
> request: add client files for role-test-saml-both-public-git-hub-bc-gov-10297

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10298.tf
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10298

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10299.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10299.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10299

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10300.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10300.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10300

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-azure-i-10302.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-azure-i-10302.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-azure-i-10302

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10303.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10303

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-git-hub-10304.tf
> request: add client files for role-test-saml-browser-login-confidential-git-hub-10304

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10305.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10305.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10305

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-idir-10306.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-idir-10306.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-idir-10306

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-azure-idir-10307.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-azure-idir-10307.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-azure-idir-10307

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-git-hub-bc-gov-10308.tf
> request: add client files for role-test-saml-git-hub-bc-gov-10308

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-idir-10309.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-idir-10309.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-idir-10309

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10310.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10310.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10310

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10311.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10311.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10311

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10312.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10312.tf
> request: add client files for create-oidc-2-team-10312

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10313.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10313.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10313

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10314.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10314.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10314

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10315.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10315.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10315

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10316.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10316.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10316

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10317.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10317.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10317

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10318.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10318.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10318

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10319.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10319.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10319

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10320.tf
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10320

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-git-hub-bc-gov-10321.tf
> request: add client files for role-test-oidc-both-confidential-git-hub-bc-gov-10321

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10322.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10322.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10322

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10323.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10323.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10323

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10324.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10324.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10324

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10325.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-azure-i-10325.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-azure-i-10325

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10326.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10326

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-git-hub-10327.tf
> request: add client files for role-test-oidc-browser-login-confidential-git-hub-10327

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10328.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10328.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10328

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-idir-10329.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-idir-10329.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-idir-10329

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10330.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10330.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10330

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10331.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10331

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10332.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10332.tf
> request: add client files for role-test-oidc-service-account-idir-10332

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10333.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10333.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10333

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-azure-idir-10334.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-azure-idir-10334.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-azure-idir-10334

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-git-hub-bc-gov-10335.tf
> request: add client files for role-test-saml-both-public-git-hub-bc-gov-10335

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10336.tf
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10336

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10338.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10338.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10338

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10339.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10339.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10339

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-azure-i-10340.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-azure-i-10340.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-azure-i-10340

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10341.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10341

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-git-hub-10342.tf
> request: add client files for role-test-saml-browser-login-confidential-git-hub-10342

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10343.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10343.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10343

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-idir-10344.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-idir-10344.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-idir-10344

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-git-hub-bc-gov-10346.tf
> request: add client files for role-test-saml-git-hub-bc-gov-10346

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-idir-10347.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-idir-10347.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-idir-10347

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10348.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10348.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10348

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10349.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10349.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10349

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10350.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10350.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10350

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10351.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10351.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10351

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10352.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10352.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10352

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10353.tf
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10353

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10355.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10355.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10355

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10356.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10356.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10356

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10359.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10359

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10361.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10361.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10361

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-idir-10362.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-confidential-idir-10362.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-confidential-idir-10362

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10363.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10363.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10363

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10364.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10364

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10365.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10365.tf
> request: add client files for role-test-oidc-service-account-idir-10365

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10366.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10366.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10366

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10369.tf
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10369

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10370.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10370.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10370

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10371.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10371.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10371

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10372.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10372.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10372

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-azure-idir-10374.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-azure-idir-10374.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-azure-idir-10374

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-azure-idir-10375.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-azure-idir-10375.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-azure-idir-10375

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-git-hub-bc-gov-10376.tf
> request: add client files for role-test-oidc-both-public-git-hub-bc-gov-10376

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-public-idir-10378.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-public-idir-10378.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-public-idir-10378

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-both-confidential-idir-10379.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-both-confidential-idir-10379.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-both-confidential-idir-10379

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10380.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10380.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10380

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10382.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10382

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-confidential-git-hub-10383.tf
> request: add client files for role-test-oidc-browser-login-confidential-git-hub-10383

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10384.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10384.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10384

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10386.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10386.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10386

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10387.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10387

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-azure-idir-10389.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-azure-idir-10389.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-azure-idir-10389

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-git-hub-bc-gov-10392.tf
> request: add client files for role-test-saml-both-confidential-git-hub-bc-gov-10392

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-public-idir-10393.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-public-idir-10393.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-public-idir-10393

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-both-confidential-idir-10394.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-both-confidential-idir-10394.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-both-confidential-idir-10394

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10395.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10395.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10395

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-azure-i-10396.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-azure-i-10396.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-azure-i-10396

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10397.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10397

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-confidential-idir-10400.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-confidential-idir-10400.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-confidential-idir-10400

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-azure-idir-10401.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-azure-idir-10401.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-azure-idir-10401

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10406.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10406.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10406

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10407.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10407.tf
> request: add client files for create-oidc-2-team-10407

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10408.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10408.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10408

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10409.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10409.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10409

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10410.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10410.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10410

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10411.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10411.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10411

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10412.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10412.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10412

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10414.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10414

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10415.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10415.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10415

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10416.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10416.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10416

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10417.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10417

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10419.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10419.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10419

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10420.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10420

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10421.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10421.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10421

- terraform-v2/keycloak-dev/standard-clients/test-automation-do-not-delete-10422.tf
- terraform-v2/keycloak-test/standard-clients/test-automation-do-not-delete-10422.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for test-automation-do-not-delete-10422

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10423.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10423.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10423

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10424.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10424

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10425.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10425.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10425

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10426.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10426.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10426

- terraform-v2/keycloak-prod/standard-service-accounts/service-account-team-1453-10429.tf
> request: add client files for service-account-for-team-1453-10429

- terraform-v2/keycloak-dev/standard-clients/dec-8-zorin-test-10430.tf
> request: add client files for dec-8-zorin-test-10430

- terraform-v2/keycloak-dev/standard-clients/test-github-bcgov-nk-10431.tf
- terraform-v2/keycloak-prod/standard-clients/test-github-bcgov-nk-10431.tf
- terraform-v2/keycloak-test/standard-clients/test-github-bcgov-nk-10431.tf
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li>
</ul>
</details>
<details>
<ul>✔️ Valid Redirect Urls<li>http://localhost:3000/*</li>
</ul>
</details>
> request: add client files for test-github-bcgov-nk-10431

- terraform-v2/keycloak-dev/standard-clients/tians-testing-12-08-git-hub-10432.tf
> request: add client files for tians-testing-12-08-git-hub-10432

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10463.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10463.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10463

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10464.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10464.tf
> request: add client files for create-oidc-2-team-10464

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10467.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10467.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10467

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10465.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10465.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10465

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10468.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10468.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10468

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10469.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10469.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10469

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10470.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10470.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10470

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10471.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10471

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10472.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10472.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10472

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10473.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10473.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10473

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10475.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10475.tf
> request: add client files for role-test-oidc-service-account-idir-10475

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10476.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10476.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10476

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10477.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10477

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10478.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10478.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10478

- terraform-v2/keycloak-dev/standard-clients/zorin-test-dec-13-10479.tf
> request: add client files for zorin-test-dec-13-10479

- terraform-v2/keycloak-dev/standard-clients/simple-idir-10480.tf
> request: add client files for simple-idir-10480

- terraform-v2-custom/keycloak-dev/custom-realms/aaadsds.tf
disabled through request disabled at realm registry for a custom realm aaadsds
> feat: disable custom realm aaadsds

- terraform-v2-custom/keycloak-dev/custom-realms/new-test.tf
disabled through request disabled at realm registry for a custom realm new-test
> feat: disable custom realm new-test

- terraform-v2-custom/keycloak-dev/custom-realms/full-test-jon.tf
- terraform-v2-custom/keycloak-prod/custom-realms/full-test-jon.tf
- terraform-v2-custom/keycloak-test/custom-realms/full-test-jon.tf
created through request created at realm registry for a custom realm full-test-jon
> feat: create custom realm full-test-jon

- terraform-v2-custom/keycloak-dev/custom-realms/full-test-jon.tf
- terraform-v2-custom/keycloak-prod/custom-realms/full-test-jon.tf
- terraform-v2-custom/keycloak-test/custom-realms/full-test-jon.tf
disabled through request disabled at realm registry for a custom realm full-test-jon
> feat: disable custom realm full-test-jon

- terraform-v2-custom/keycloak-dev/custom-realms/aaaq.tf
disabled through request disabled at realm registry for a custom realm aaaq
> feat: disable custom realm aaaq

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-delete.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-delete.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-delete.tf
created through request created at realm registry for a custom realm jon-test-delete
> feat: create custom realm jon-test-delete

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-delete.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-delete.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-delete.tf
disabled through request disabled at realm registry for a custom realm jon-test-delete
> feat: disable custom realm jon-test-delete

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-delete-2.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-delete-2.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-delete-2.tf
created through request created at realm registry for a custom realm jon-test-delete-2
> feat: create custom realm jon-test-delete-2

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-delete-2.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-delete-2.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-delete-2.tf
disabled through request disabled at realm registry for a custom realm jon-test-delete-2
> feat: disable custom realm jon-test-delete-2

- terraform-v2-custom/keycloak-dev/custom-realms/test-email-workflow-nk-01.tf
- terraform-v2-custom/keycloak-prod/custom-realms/test-email-workflow-nk-01.tf
- terraform-v2-custom/keycloak-test/custom-realms/test-email-workflow-nk-01.tf
created through request created at realm registry for a custom realm test-email-workflow-nk-01
> feat: create custom realm test-email-workflow-nk-01

- terraform-v2-custom/keycloak-dev/custom-realms/test-email-workflow-nk-01.tf
- terraform-v2-custom/keycloak-prod/custom-realms/test-email-workflow-nk-01.tf
- terraform-v2-custom/keycloak-test/custom-realms/test-email-workflow-nk-01.tf
disabled through request disabled at realm registry for a custom realm test-email-workflow-nk-01
> feat: disable custom realm test-email-workflow-nk-01

- terraform-v2-custom/keycloak-dev/custom-realms/dec-18-testcreation-2.tf
- terraform-v2-custom/keycloak-prod/custom-realms/dec-18-testcreation-2.tf
- terraform-v2-custom/keycloak-test/custom-realms/dec-18-testcreation-2.tf
created through request created at realm registry for a custom realm dec-18-testcreation-2
> feat: create custom realm dec-18-testcreation-2

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-5.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-5.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-5.tf
created through request created at realm registry for a custom realm jon-test-5
> feat: create custom realm jon-test-5

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-7.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-7.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-7.tf
created through request created at realm registry for a custom realm jon-test-7
> feat: create custom realm jon-test-7

- terraform-v2/keycloak-dev/standard-clients/test-api-10481.tf
> request: add client files for test-api-10481

- terraform-v2/keycloak-dev/standard-clients/single-sign-on-test-1-a-10482.tf
> request: add client files for single-sign-on-test-1-a-10482

- terraform-v2/keycloak-dev/standard-clients/single-sign-on-test-1-b-10483.tf
> request: add client files for single-sign-on-test-1-b-10483

- terraform-v2-custom/keycloak-dev/custom-realms/dec-18-testcreation-2.tf
- terraform-v2-custom/keycloak-prod/custom-realms/dec-18-testcreation-2.tf
- terraform-v2-custom/keycloak-test/custom-realms/dec-18-testcreation-2.tf
disabled through request disabled at realm registry for a custom realm dec-18-testcreation-2
> feat: disable custom realm dec-18-testcreation-2

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-8.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-8.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-8.tf
created through request created at realm registry for a custom realm jon-test-8
> feat: create custom realm jon-test-8

- terraform-v2-custom/keycloak-dev/custom-realms/dec-18-testcreation.tf
- terraform-v2-custom/keycloak-prod/custom-realms/dec-18-testcreation.tf
- terraform-v2-custom/keycloak-test/custom-realms/dec-18-testcreation.tf
created through request created at realm registry for a custom realm dec-18-testcreation
> feat: create custom realm dec-18-testcreation

- terraform-v2-custom/keycloak-dev/custom-realms/test-icons-nk-01.tf
- terraform-v2-custom/keycloak-prod/custom-realms/test-icons-nk-01.tf
- terraform-v2-custom/keycloak-test/custom-realms/test-icons-nk-01.tf
created through request created at realm registry for a custom realm test-icons-nk-01
> feat: create custom realm test-icons-nk-01

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10484.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10484.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10484

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10485.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10485.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10485

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10486.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10486.tf
> request: add client files for create-oidc-2-team-10486

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10488.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10488.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10488

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10487.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10487.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10487

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10489.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10489.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10489

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10490.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10490.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10490

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10491.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10491.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10491

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10492.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10492.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10492

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10493.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10493

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10494.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10494.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10494

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10495.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10495.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10495

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10496.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10496

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10497.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10497.tf
> request: add client files for role-test-oidc-service-account-idir-10497

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10498.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10498.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10498

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10499.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10499

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10500.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10500.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10500

- terraform-v2-custom/keycloak-dev/custom-realms/sandbox-test-dec-27.tf
- terraform-v2-custom/keycloak-prod/custom-realms/sandbox-test-dec-27.tf
- terraform-v2-custom/keycloak-test/custom-realms/sandbox-test-dec-27.tf
created through request created at realm registry for a custom realm sandbox-test-dec-27
> feat: create custom realm sandbox-test-dec-27

- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-2.tf
created through request created at realm registry for a custom realm jon-test-2
> feat: create custom realm jon-test-2

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10502.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10502.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10502

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10503.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10503.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10503

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10504.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10504.tf
> request: add client files for create-oidc-2-team-10504

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10505.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10505.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10505

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10506.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10506.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10506

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10507.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10507.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10507

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10508.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10508.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10508

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10509.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10509.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10509

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10510.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10510.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10510

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10511.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10511

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10512.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10512.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10512

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10513.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10513.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10513

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10514.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10514

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10515.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10515.tf
> request: add client files for role-test-oidc-service-account-idir-10515

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10516.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10516.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10516

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10517.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10517

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10518.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10518.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10518

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10519.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10519.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10519

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10520.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10520.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10520

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10521.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10521.tf
> request: add client files for create-oidc-2-team-10521

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10522.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10522.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10522

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10523.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10523.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10523

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10524.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10524.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10524

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10525.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10525.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10525

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10526.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10526.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10526

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10527.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10527.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10527

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10528.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10528

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10529.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10529.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10529

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10530.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10530.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10530

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10531.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10531

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10532.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10532.tf
> request: add client files for role-test-oidc-service-account-idir-10532

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10533.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10533.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10533

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10534.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10534

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10535.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10535.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10535

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10536.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10536.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10536

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10537.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10537.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10537

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10538.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10538.tf
> request: add client files for create-oidc-2-team-10538

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10539.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10539.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10539

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10540.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10540.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10540

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10541.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10541.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10541

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10542.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10542.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10542

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10543.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10543.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10543

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-team-10544.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-team-10544.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-team-10544

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-public-team-confidential-10545.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-public-team-confidential-10545.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-public-team-confidential-10545

- terraform-v2/keycloak-dev/standard-clients/create-oidc-2-team-10546.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-2-team-10546.tf
> request: add client files for create-oidc-2-team-10546

- terraform-v2/keycloak-dev/standard-clients/create-oidc-3-team-10547.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-3-team-10547.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-3-team-10547

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-team-10548.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-team-10548.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-team-10548

- terraform-v2/keycloak-dev/standard-clients/create-saml-2-team-10549.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-2-team-10549.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-2-team-10549

- terraform-v2/keycloak-dev/standard-clients/create-oidc-1-no-team-10550.tf
- terraform-v2/keycloak-test/standard-clients/create-oidc-1-no-team-10550.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-oidc-1-no-team-10550

- terraform-v2/keycloak-dev/standard-clients/create-saml-1-no-team-to-team-10551.tf
- terraform-v2/keycloak-test/standard-clients/create-saml-1-no-team-to-team-10551.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for create-saml-1-no-team-to-team-10551

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-azure-idir-10552.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-azure-idir-10552.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-azure-idir-10552

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-git-hub-bc-gov-10553.tf
> request: add client files for role-test-oidc-browser-login-public-git-hub-bc-gov-10553

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-browser-login-public-idir-10554.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-browser-login-public-idir-10554.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-oidc-browser-login-public-idir-10554

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-azure-idir-10555.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-azure-idir-10555.tf
> request: add client files for role-test-oidc-service-account-azure-idir-10555

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-git-hub-bc-gov-10556.tf
> request: add client files for role-test-oidc-service-account-git-hub-bc-gov-10556

- terraform-v2/keycloak-dev/standard-clients/role-test-oidc-service-account-idir-10557.tf
- terraform-v2/keycloak-test/standard-clients/role-test-oidc-service-account-idir-10557.tf
> request: add client files for role-test-oidc-service-account-idir-10557

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-azure-idir-10558.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-azure-idir-10558.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-azure-idir-10558

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-git-hub-bc-gov-10559.tf
> request: add client files for role-test-saml-browser-login-public-git-hub-bc-gov-10559

- terraform-v2/keycloak-dev/standard-clients/role-test-saml-browser-login-public-idir-10560.tf
- terraform-v2/keycloak-test/standard-clients/role-test-saml-browser-login-public-idir-10560.tf
<details>
</ul>
</details>
<details>
</ul>
</details>
> request: add client files for role-test-saml-browser-login-public-idir-10560

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-11-30.tf
disabled through request disabled at realm registry for a custom realm tian-test-realm-11-30
> feat: disable custom realm tian-test-realm-11-30

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-11-24.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-test-realm-11-24.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-test-realm-11-24.tf
disabled through request disabled at realm registry for a custom realm tian-test-realm-11-24
> feat: disable custom realm tian-test-realm-11-24

- terraform-v2-custom/keycloak-dev/custom-realms/tian-admin-test-1121.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-admin-test-1121.tf
disabled through request disabled at realm registry for a custom realm tian-admin-test-1121
> feat: disable custom realm tian-admin-test-1121

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-2024-01-05-a.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-test-realm-2024-01-05-a.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-test-realm-2024-01-05-a.tf
created through request created at realm registry for a custom realm tian-test-realm-2024-01-05-a
> feat: create custom realm tian-test-realm-2024-01-05-a

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-2024-01-10-a.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-test-realm-2024-01-10-a.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-test-realm-2024-01-10-a.tf
created through request created at realm registry for a custom realm tian-test-realm-2024-01-10-a
> feat: create custom realm tian-test-realm-2024-01-10-a

- terraform-v2-custom/keycloak-dev/custom-realms/aaadsds.tf
- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-1.tf
- terraform-v2-custom/keycloak-dev/custom-realms/jon-test-5.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-test-5.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-test-5.tf
remove junk realms for token size, I cleared 3 of them which has the token working again
> chore: cleanup junk realms

- terraform-v2-custom/keycloak-dev/custom-realms/tian-test-realm-2024-01-15-admin-test.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-test-realm-2024-01-15-admin-test.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-test-realm-2024-01-15-admin-test.tf
created through request created at realm registry for a custom realm tian-test-realm-2024-01-15-admin-test
> feat: create custom realm tian-test-realm-2024-01-15-admin-test

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240116-admin-test.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240116-admin-test.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240116-admin-test.tf
created through request created at realm registry for a custom realm tian-20240116-admin-test
> feat: create custom realm tian-20240116-admin-test

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240118-edit-admin.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240118-edit-admin.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240118-edit-admin.tf
created through request created at realm registry for a custom realm tian-20240118-edit-admin
> feat: create custom realm tian-20240118-edit-admin

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240118-no-edit.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240118-no-edit.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240118-no-edit.tf
created through request created at realm registry for a custom realm tian-20240118-no-edit
> feat: create custom realm tian-20240118-no-edit

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240108-pr-success-edit.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240108-pr-success-edit.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240108-pr-success-edit.tf
created through request created at realm registry for a custom realm tian-20240108-pr-success-edit
> feat: create custom realm tian-20240108-pr-success-edit

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240118-pr-success-edit-a.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240118-pr-success-edit-a.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240118-pr-success-edit-a.tf
created through request created at realm registry for a custom realm tian-20240118-pr-success-edit-a
> feat: create custom realm tian-20240118-pr-success-edit-a

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240118-pr-success-edit-b.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240118-pr-success-edit-b.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240118-pr-success-edit-b.tf
created through request created at realm registry for a custom realm tian-20240118-pr-success-edit-b
> feat: create custom realm tian-20240118-pr-success-edit-b

- terraform-v2-custom/keycloak-dev/custom-realms/tian-20240119-pr-success-edit.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-20240119-pr-success-edit.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-20240119-pr-success-edit.tf
created through request created at realm registry for a custom realm tian-20240119-pr-success-edit
> feat: create custom realm tian-20240119-pr-success-edit

- terraform-v2-custom/keycloak-dev/custom-realms/tian-pr-success-20240119.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-pr-success-20240119.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-pr-success-20240119.tf
created through request created at realm registry for a custom realm tian-pr-success-20240119
> feat: create custom realm tian-pr-success-20240119

- terraform-v2-custom/keycloak-dev/custom-realms/tian-119-attemp-1.tf
- terraform-v2-custom/keycloak-prod/custom-realms/tian-119-attemp-1.tf
- terraform-v2-custom/keycloak-test/custom-realms/tian-119-attemp-1.tf
created through request created at realm registry for a custom realm tian-119-attemp-1
> feat: create custom realm tian-119-attemp-1

- terraform-v2/keycloak-dev/main.tf
- terraform-v2/keycloak-prod/main.tf
- terraform-v2/keycloak-test/main.tf
change display name for idir with mfa in the master realm
> chore: idir mfa display name in master

- terraform-v2-custom/keycloak-dev/custom-realms/jan-29-zs.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jan-29-zs.tf
- terraform-v2-custom/keycloak-test/custom-realms/jan-29-zs.tf
created through request created at realm registry for a custom realm jan-29-zs
> feat: create custom realm jan-29-zs

- terraform-v2-custom/keycloak-dev/custom-realms/jon-l-wiki-email-test.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jon-l-wiki-email-test.tf
- terraform-v2-custom/keycloak-test/custom-realms/jon-l-wiki-email-test.tf
created through request created at realm registry for a custom realm jon-l-wiki-email-test
> feat: create custom realm jon-l-wiki-email-test

- .github/workflows/prune-branches.yaml
> chore: action cleanup

- terraform-v2/keycloak-dev/main.tf
- terraform-v2/keycloak-prod/main.tf
- terraform-v2/keycloak-test/main.tf
update tf resources for new dc setup
> chore: update terraform

- terraform-v2-custom/keycloak-dev/custom-realms/jonl-restore-test.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jonl-restore-test.tf
- terraform-v2-custom/keycloak-test/custom-realms/jonl-restore-test.tf
created through request created at realm registry for a custom realm jonl-restore-test
> feat: create custom realm jonl-restore-test

- terraform-v2-custom/keycloak-dev/custom-realms/jonl-restore-test.tf
- terraform-v2-custom/keycloak-prod/custom-realms/jonl-restore-test.tf
- terraform-v2-custom/keycloak-test/custom-realms/jonl-restore-test.tf
disabled through request disabled at realm registry for a custom realm jonl-restore-test
> feat: disable custom realm jonl-restore-test

- terraform-v2-custom/keycloak-dev/custom-realms/sharman.tf
- terraform-v2-custom/keycloak-prod/custom-realms/sharman.tf
- terraform-v2-custom/keycloak-test/custom-realms/sharman.tf
created through request created at realm registry for a custom realm sharman
> feat: create custom realm sharman

- terraform-v2-custom/keycloak-dev/custom-realms/sharman.tf
- terraform-v2-custom/keycloak-prod/custom-realms/sharman.tf
- terraform-v2-custom/keycloak-test/custom-realms/sharman.tf
disabled through request disabled at realm registry for a custom realm sharman
> feat: disable custom realm sharman

- terraform-v2/keycloak-dev/main.tf
- terraform-v2/keycloak-prod/main.tf
- terraform-v2/keycloak-test/main.tf
remove ms login from master realm
> chore: microsoft login

- .github/workflows/terraform-v2-apply.yml
- terraform-v2/keycloak-dev/main.tf
- terraform-v2/keycloak-dev/variables.tf
- terraform-v2/keycloak-prod/main.tf
- terraform-v2/keycloak-prod/variables.tf
- terraform-v2/keycloak-test/main.tf
- terraform-v2/keycloak-test/variables.tf
- terraform-v2/main.tf
- terraform-v2/variables.tf
> feat: apple login
